package Padre::Plugin::Nopaste::FBP::Preferences;

## no critic

# This module was generated by Padre::Plugin::FormBuilder::Perl.
# To change this module edit the original .fbp file and regenerate.
# DO NOT MODIFY THIS FILE BY HAND!

use 5.008005;
use utf8;
use strict;
use warnings;
use Padre::Wx ();
use Padre::Wx::Role::Main ();

our $VERSION = '0.04';
our @ISA     = qw{
	Padre::Wx::Role::Main
	Wx::Dialog
};

sub new {
	my $class  = shift;
	my $parent = shift;

	my $self = $class->SUPER::new(
		$parent,
		-1,
		Wx::gettext("nopaste preferences"),
		Wx::DefaultPosition,
		Wx::DefaultSize,
		Wx::DEFAULT_DIALOG_STYLE | Wx::RESIZE_BORDER,
	);

	$self->{config_nickname} = Wx::StaticText->new(
		$self,
		-1,
		Wx::gettext("config_nickname"),
	);

	$self->{nopaste_server} = Wx::Choice->new(
		$self,
		-1,
		Wx::DefaultPosition,
		[ 220, -1 ],
		[],
	);
	$self->{nopaste_server}->SetSelection(0);

	Wx::Event::EVT_CHOICE(
		$self,
		$self->{nopaste_server},
		sub {
			shift->on_server_chosen(@_);
		},
	);

	$self->{nopaste_channel} = Wx::Choice->new(
		$self,
		-1,
		Wx::DefaultPosition,
		[ 220, -1 ],
		[],
	);
	$self->{nopaste_channel}->SetSelection(0);

	$self->{m_sdbSizer1_save} = Wx::Button->new(
		$self,
		Wx::ID_SAVE,
	);

	Wx::Event::EVT_BUTTON(
		$self,
		$self->{m_sdbSizer1_save},
		sub {
			shift->_on_button_save_clicked(@_);
		},
	);

	$self->{m_sdbSizer1_cancel} = Wx::Button->new(
		$self,
		Wx::ID_CANCEL,
	);

	my $sbSizer2 = Wx::StaticBoxSizer->new(
		Wx::StaticBox->new(
			$self,
			-1,
			Wx::gettext("Nick Name"),
		),
		Wx::VERTICAL,
	);
	$sbSizer2->Add( $self->{config_nickname}, 0, Wx::ALL, 5 );

	$self->{sbSizer4} = Wx::StaticBoxSizer->new(
		Wx::StaticBox->new(
			$self,
			-1,
			Wx::gettext("Nopaste Server"),
		),
		Wx::VERTICAL,
	);
	$self->{sbSizer4}->Add( $self->{nopaste_server}, 0, Wx::ALL, 5 );

	$self->{sbSizer41} = Wx::StaticBoxSizer->new(
		Wx::StaticBox->new(
			$self,
			-1,
			Wx::gettext("Nopaste Channel"),
		),
		Wx::VERTICAL,
	);
	$self->{sbSizer41}->Add( $self->{nopaste_channel}, 0, Wx::ALL, 5 );

	$self->{m_sdbSizer1} = Wx::StdDialogButtonSizer->new;
	$self->{m_sdbSizer1}->AddButton( $self->{m_sdbSizer1_save} );
	$self->{m_sdbSizer1}->AddButton( $self->{m_sdbSizer1_cancel} );
	$self->{m_sdbSizer1}->Realize;

	my $bSizer1 = Wx::BoxSizer->new(Wx::VERTICAL);
	$bSizer1->Add( $sbSizer2, 1, Wx::EXPAND, 5 );
	$bSizer1->Add( $self->{sbSizer4}, 1, Wx::ALL | Wx::EXPAND, 5 );
	$bSizer1->Add( $self->{sbSizer41}, 1, Wx::ALL | Wx::EXPAND, 5 );
	$bSizer1->Add( $self->{m_sdbSizer1}, 0, Wx::ALL | Wx::EXPAND, 5 );

	$self->SetSizerAndFit($bSizer1);
	$self->Layout;

	return $self;
}

sub config_nickname {
	$_[0]->{config_nickname};
}

sub nopaste_server {
	$_[0]->{nopaste_server};
}

sub nopaste_channel {
	$_[0]->{nopaste_channel};
}

sub on_server_chosen {
	$_[0]->main->error('Handler method on_server_chosen for event nopaste_server.OnChoice not implemented');
}

sub _on_button_ok_clicked {
	$_[0]->main->error('Handler method _on_button_ok_clicked for event m_sdbSizer1.OnOKButtonClick not implemented');
}

sub _on_button_save_clicked {
	$_[0]->main->error('Handler method _on_button_save_clicked for event m_sdbSizer1.OnSaveButtonClick not implemented');
}

1;

# Copyright 2008-2012 The Padre development team as listed in Padre.pm.
# LICENSE
# This program is free software; you can redistribute it and/or
# modify it under the same terms as Perl 5 itself.

