---
name: Padre-Plugin-Alarm
version: 0.07
author:
  - 'Fayland Lam <fayland@gmail.com>'
abstract: Alarm Clock in Padre
license: perl
resources:
  homepage: http://padre.perlide.org/
  license: http://dev.perl.org/licenses/
  repository: http://svn.perlide.org/padre/trunk/Padre-Plugin-Alarm/
requires:
  Audio::Beep: 0
  Padre: 0.26
  Padre::Wx::Dialog: 0
build_requires:
  Test::More: 0
provides:
  Padre::Plugin::Alarm:
    file: lib/Padre/Plugin/Alarm.pm
    version: 0.07
generated_by: Module::Build version 0.33
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: 1.4
