---
name: Padre-Plugin-Alarm
version: 0.03
author:
  - 'Fayland Lam <fayland@gmail.com>'
abstract: Alarm Clock in Padre
license: perl
resources:
  license: http://dev.perl.org/licenses/
configure_requires:
  Padre::PluginBuilder: 0.12
requires:
  Audio::Beep: 0
  Padre: 0.26
  Padre::Wx::Dialog: 0
build_requires:
  Test::More: 0
provides:
  Padre::Plugin::Alarm:
    file: lib/Padre/Plugin/Alarm.pm
    version: 0.03
generated_by: Module::Build version 0.31
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.2.html
  version: 1.2
