package Padre::Plugin::Moose::FBP::Moose;

## no critic

# This module was generated by Padre::Plugin::FormBuilder::Perl.
# To change this module edit the original .fbp file and regenerate.
# DO NOT MODIFY THIS FILE BY HAND!

use 5.008005;
use utf8;
use strict;
use warnings;
use Padre::Wx ();
use Padre::Wx::Role::Main ();

our $VERSION = '0.02';
our @ISA     = qw{
	Padre::Wx::Role::Main
	Wx::Dialog
};

sub new {
	my $class  = shift;
	my $parent = shift;

	my $self = $class->SUPER::new(
		$parent,
		-1,
		Wx::gettext("Moose!"),
		Wx::DefaultPosition,
		[ 560, 566 ],
		Wx::DEFAULT_DIALOG_STYLE,
	);

	$self->{action_list} = Wx::ListBox->new(
		$self,
		-1,
		Wx::DefaultPosition,
		Wx::DefaultSize,
		[
			"Class",
			"Role",
			"Attribute",
			"Subtype",
		],
	);

	$self->{help_text} = Wx::TextCtrl->new(
		$self,
		-1,
		"",
		Wx::DefaultPosition,
		Wx::DefaultSize,
		Wx::TE_MULTILINE,
	);

	$self->{panel} = Wx::Panel->new(
		$self,
		-1,
		Wx::DefaultPosition,
		Wx::DefaultSize,
		Wx::TAB_TRAVERSAL,
	);

	$self->{preview_panel} = Wx::Panel->new(
		$self,
		-1,
		Wx::DefaultPosition,
		Wx::DefaultSize,
		Wx::TAB_TRAVERSAL,
	);

	$self->{ok_button} = Wx::Button->new(
		$self,
		-1,
		Wx::gettext("OK"),
		Wx::DefaultPosition,
		Wx::DefaultSize,
	);

	Wx::Event::EVT_BUTTON(
		$self,
		$self->{ok_button},
		sub {
			shift->on_ok_clicked(@_);
		},
	);

	$self->{cancel_button} = Wx::Button->new(
		$self,
		-1,
		Wx::gettext("Cancel"),
		Wx::DefaultPosition,
		Wx::DefaultSize,
	);

	Wx::Event::EVT_BUTTON(
		$self,
		$self->{cancel_button},
		sub {
			shift->on_cancel_clicked(@_);
		},
	);

	my $left_sizer = Wx::BoxSizer->new(Wx::VERTICAL);
	$left_sizer->Add( $self->{action_list}, 1, Wx::ALL | Wx::EXPAND, 5 );
	$left_sizer->Add( $self->{help_text}, 2, Wx::ALL | Wx::EXPAND, 5 );
	$left_sizer->Add( $self->{panel}, 3, Wx::EXPAND | Wx::ALL, 5 );

	my $top_sizer = Wx::BoxSizer->new(Wx::HORIZONTAL);
	$top_sizer->Add( $left_sizer, 1, Wx::EXPAND, 5 );
	$top_sizer->Add( $self->{preview_panel}, 2, Wx::EXPAND | Wx::ALL, 5 );

	my $buttons_sizer = Wx::BoxSizer->new(Wx::HORIZONTAL);
	$buttons_sizer->Add( 20, 0, 1, Wx::EXPAND, 5 );
	$buttons_sizer->Add( $self->{ok_button}, 0, Wx::ALL, 2 );
	$buttons_sizer->Add( $self->{cancel_button}, 0, Wx::ALL, 2 );

	my $vsizer = Wx::BoxSizer->new(Wx::VERTICAL);
	$vsizer->Add( $top_sizer, 1, Wx::EXPAND, 5 );
	$vsizer->Add( $buttons_sizer, 0, Wx::EXPAND, 5 );

	my $hsizer = Wx::BoxSizer->new(Wx::HORIZONTAL);
	$hsizer->Add( $vsizer, 1, Wx::ALL | Wx::EXPAND, 5 );

	$self->SetSizer($hsizer);
	$self->Layout;

	return $self;
}

sub ok_button {
	$_[0]->{ok_button};
}

sub on_ok_clicked {
	$_[0]->main->error('Handler method on_ok_clicked for event ok_button.OnButtonClick not implemented');
}

sub on_cancel_clicked {
	$_[0]->main->error('Handler method on_cancel_clicked for event cancel_button.OnButtonClick not implemented');
}

1;

# Copyright 2008-2012 The Padre development team as listed in Padre.pm.
# LICENSE
# This program is free software; you can redistribute it and/or
# modify it under the same terms as Perl 5 itself.

