package Padre::Plugin::Moose::FBP::NewAttribute;

## no critic

# This module was generated by Padre::Plugin::FormBuilder::Perl.
# To change this module edit the original .fbp file and regenerate.
# DO NOT MODIFY THIS FILE BY HAND!

use 5.008005;
use utf8;
use strict;
use warnings;
use Padre::Wx ();
use Padre::Wx::Role::Main ();

our $VERSION = '0.02';
our @ISA     = qw{
	Padre::Wx::Role::Main
	Wx::Panel
};

sub new {
	my $class  = shift;
	my $parent = shift;

	my $self = $class->SUPER::new(
		$parent,
		-1,
		Wx::DefaultPosition,
		[ 500, 300 ],
		Wx::TAB_TRAVERSAL,
	);

	my $attribute_label = Wx::StaticText->new(
		$self,
		-1,
		Wx::gettext("Attribute:"),
	);

	$self->{attribute_text} = Wx::TextCtrl->new(
		$self,
		-1,
		"",
		Wx::DefaultPosition,
		Wx::DefaultSize,
	);

	my $type_label = Wx::StaticText->new(
		$self,
		-1,
		Wx::gettext("Type:"),
	);

	$self->{type_choice} = Wx::Choice->new(
		$self,
		-1,
		Wx::DefaultPosition,
		Wx::DefaultSize,
		[
			"Any",
			"Item",
			"Bool",
			"Maybe",
			"Undef",
			"Defined",
			"Value",
			"Str",
			"Num",
			"Int",
			"ClassName",
			"RoleName",
			"Ref",
			"ScalarRef",
			"ArrayRef",
			"HashRef",
			"CodeRef",
			"RegexpRef",
			"GlobRef",
			"FileHandle",
			"Object",
		],
	);
	$self->{type_choice}->SetSelection(0);

	my $property_label = Wx::StaticText->new(
		$self,
		-1,
		Wx::gettext("Property:"),
	);

	$self->{property_choice} = Wx::Choice->new(
		$self,
		-1,
		Wx::DefaultPosition,
		Wx::DefaultSize,
		[
			"Read-Write",
			"Read-Only",
			"Bare",
		],
	);
	$self->{property_choice}->SetSelection(0);

	my $trigger_label = Wx::StaticText->new(
		$self,
		-1,
		Wx::gettext("Trigger:"),
	);

	$self->{trigger_text} = Wx::TextCtrl->new(
		$self,
		-1,
		"",
		Wx::DefaultPosition,
		Wx::DefaultSize,
	);

	$self->{required_checbox} = Wx::CheckBox->new(
		$self,
		-1,
		Wx::gettext("Required?"),
		Wx::DefaultPosition,
		Wx::DefaultSize,
	);

	my $content_sizer = Wx::FlexGridSizer->new( 2, 2, 0, 0 );
	$content_sizer->SetFlexibleDirection(Wx::BOTH);
	$content_sizer->SetNonFlexibleGrowMode(Wx::FLEX_GROWMODE_SPECIFIED);
	$content_sizer->Add( $attribute_label, 0, Wx::ALIGN_CENTER_VERTICAL | Wx::LEFT | Wx::RIGHT | Wx::TOP, 5 );
	$content_sizer->Add( $self->{attribute_text}, 0, Wx::ALL, 5 );
	$content_sizer->Add( $type_label, 0, Wx::ALIGN_CENTER_VERTICAL | Wx::LEFT | Wx::RIGHT | Wx::TOP, 5 );
	$content_sizer->Add( $self->{type_choice}, 0, Wx::ALL, 5 );
	$content_sizer->Add( $property_label, 0, Wx::ALIGN_CENTER_VERTICAL | Wx::LEFT | Wx::RIGHT | Wx::TOP, 5 );
	$content_sizer->Add( $self->{property_choice}, 0, Wx::ALL, 5 );
	$content_sizer->Add( $trigger_label, 0, Wx::ALIGN_CENTER_VERTICAL | Wx::LEFT | Wx::RIGHT | Wx::TOP, 5 );
	$content_sizer->Add( $self->{trigger_text}, 0, Wx::ALL, 5 );
	$content_sizer->Add( $self->{required_checbox}, 0, Wx::ALL, 5 );

	$self->SetSizer($content_sizer);
	$self->Layout;

	return $self;
}

1;

# Copyright 2008-2012 The Padre development team as listed in Padre.pm.
# LICENSE
# This program is free software; you can redistribute it and/or
# modify it under the same terms as Perl 5 itself.

