package Padre::Plugin::Moose::FBP::NewSubType;

## no critic

# This module was generated by Padre::Plugin::FormBuilder::Perl.
# To change this module edit the original .fbp file and regenerate.
# DO NOT MODIFY THIS FILE BY HAND!

use 5.008005;
use utf8;
use strict;
use warnings;
use Padre::Wx ();
use Padre::Wx::Role::Main ();

our $VERSION = '0.02';
our @ISA     = qw{
	Padre::Wx::Role::Main
	Wx::Dialog
};

sub new {
	my $class  = shift;
	my $parent = shift;

	my $self = $class->SUPER::new(
		$parent,
		-1,
		Wx::gettext("New Subtype"),
		Wx::DefaultPosition,
		[ 391, 258 ],
		Wx::DEFAULT_DIALOG_STYLE,
	);

	my $subtype_label = Wx::StaticText->new(
		$self,
		-1,
		Wx::gettext("Subtype:"),
	);

	$self->{role_text} = Wx::TextCtrl->new(
		$self,
		-1,
		"",
		Wx::DefaultPosition,
		Wx::DefaultSize,
	);

	my $constraint_label = Wx::StaticText->new(
		$self,
		-1,
		Wx::gettext("Constraint:"),
	);

	$self->{constraint_text} = Wx::TextCtrl->new(
		$self,
		-1,
		"",
		Wx::DefaultPosition,
		Wx::DefaultSize,
	);

	my $error_message_label = Wx::StaticText->new(
		$self,
		-1,
		Wx::gettext("Error Message:"),
	);

	$self->{error_message_text} = Wx::TextCtrl->new(
		$self,
		-1,
		"",
		Wx::DefaultPosition,
		Wx::DefaultSize,
	);

	$self->{ok_button} = Wx::Button->new(
		$self,
		-1,
		Wx::gettext("OK"),
		Wx::DefaultPosition,
		Wx::DefaultSize,
	);

	Wx::Event::EVT_BUTTON(
		$self,
		$self->{ok_button},
		sub {
			shift->on_ok_clicked(@_);
		},
	);

	$self->{cancel_button} = Wx::Button->new(
		$self,
		-1,
		Wx::gettext("Cancel"),
		Wx::DefaultPosition,
		Wx::DefaultSize,
	);

	Wx::Event::EVT_BUTTON(
		$self,
		$self->{cancel_button},
		sub {
			shift->on_cancel_clicked(@_);
		},
	);

	my $content_sizer = Wx::FlexGridSizer->new( 2, 2, 0, 0 );
	$content_sizer->SetFlexibleDirection(Wx::BOTH);
	$content_sizer->SetNonFlexibleGrowMode(Wx::FLEX_GROWMODE_SPECIFIED);
	$content_sizer->Add( $subtype_label, 0, Wx::ALIGN_CENTER_VERTICAL | Wx::LEFT | Wx::RIGHT | Wx::TOP, 5 );
	$content_sizer->Add( $self->{role_text}, 0, Wx::ALL, 5 );
	$content_sizer->Add( $constraint_label, 0, Wx::ALIGN_CENTER_VERTICAL | Wx::LEFT | Wx::RIGHT | Wx::TOP, 5 );
	$content_sizer->Add( $self->{constraint_text}, 0, Wx::ALL, 5 );
	$content_sizer->Add( $error_message_label, 0, Wx::ALIGN_CENTER_VERTICAL | Wx::LEFT | Wx::RIGHT | Wx::TOP, 5 );
	$content_sizer->Add( $self->{error_message_text}, 0, Wx::ALL, 5 );

	my $buttons_sizer = Wx::BoxSizer->new(Wx::HORIZONTAL);
	$buttons_sizer->Add( 20, 0, 1, Wx::EXPAND, 5 );
	$buttons_sizer->Add( $self->{ok_button}, 0, Wx::ALL, 2 );
	$buttons_sizer->Add( $self->{cancel_button}, 0, Wx::ALL, 2 );

	my $vsizer = Wx::BoxSizer->new(Wx::VERTICAL);
	$vsizer->Add( $content_sizer, 1, Wx::EXPAND, 5 );
	$vsizer->Add( $buttons_sizer, 0, Wx::EXPAND, 5 );

	my $hsizer = Wx::BoxSizer->new(Wx::HORIZONTAL);
	$hsizer->Add( $vsizer, 1, Wx::ALL | Wx::EXPAND, 5 );

	$self->SetSizer($hsizer);
	$self->Layout;

	return $self;
}

sub ok_button {
	$_[0]->{ok_button};
}

sub on_ok_clicked {
	$_[0]->main->error('Handler method on_ok_clicked for event ok_button.OnButtonClick not implemented');
}

sub on_cancel_clicked {
	$_[0]->main->error('Handler method on_cancel_clicked for event cancel_button.OnButtonClick not implemented');
}

1;

# Copyright 2008-2012 The Padre development team as listed in Padre.pm.
# LICENSE
# This program is free software; you can redistribute it and/or
# modify it under the same terms as Perl 5 itself.

