package Padre::Plugin::Moose::FBP::Preferences;

## no critic

# This module was generated by Padre::Plugin::FormBuilder::Perl.
# To change this module edit the original .fbp file and regenerate.
# DO NOT MODIFY THIS FILE BY HAND!

use 5.008005;
use utf8;
use strict;
use warnings;
use Padre::Wx ();
use Padre::Wx::Role::Main ();

our $VERSION = '0.16';
our @ISA     = qw{
	Padre::Wx::Role::Main
	Wx::Dialog
};

sub new {
	my $class  = shift;
	my $parent = shift;

	my $self = $class->SUPER::new(
		$parent,
		-1,
		Wx::gettext("Moose Preferences"),
		Wx::DefaultPosition,
		[ 354, 154 ],
		Wx::DEFAULT_DIALOG_STYLE,
	);

	my $m_staticText6 = Wx::StaticText->new(
		$self,
		-1,
		Wx::gettext("Code Generator Options"),
	);
	$m_staticText6->SetFont(
		Wx::Font->new( Wx::NORMAL_FONT->GetPointSize, 70, 90, 92, 0, "" )
	);

	$self->{generated_code_label} = Wx::StaticText->new(
		$self,
		-1,
		Wx::gettext("Type:"),
	);

	$self->{generated_code_combo} = Wx::ComboBox->new(
		$self,
		-1,
		"Moose",
		Wx::DefaultPosition,
		Wx::DefaultSize,
		[
			"Moose",
			"Mouse",
			"MooseX::Declare",
		],
		Wx::CB_READONLY,
	);

	Wx::Event::EVT_COMBOBOX(
		$self,
		$self->{generated_code_combo},
		sub {
			shift->on_generated_code_combo(@_);
		},
	);

	$self->{sample_code_checkbox} = Wx::CheckBox->new(
		$self,
		-1,
		Wx::gettext("Generate Sample code?"),
		Wx::DefaultPosition,
		Wx::DefaultSize,
	);

	Wx::Event::EVT_CHECKBOX(
		$self,
		$self->{sample_code_checkbox},
		sub {
			shift->on_sample_code_checkbox(@_);
		},
	);

	$self->{comments_checkbox} = Wx::CheckBox->new(
		$self,
		-1,
		Wx::gettext("Generate Comments?"),
		Wx::DefaultPosition,
		Wx::DefaultSize,
	);

	Wx::Event::EVT_CHECKBOX(
		$self,
		$self->{comments_checkbox},
		sub {
			shift->on_comments_checkbox(@_);
		},
	);

	$self->{ok_button} = Wx::Button->new(
		$self,
		-1,
		Wx::gettext("OK"),
		Wx::DefaultPosition,
		Wx::DefaultSize,
	);

	$self->{cancel_button} = Wx::Button->new(
		$self,
		Wx::ID_CANCEL,
		Wx::gettext("Cancel"),
		Wx::DefaultPosition,
		Wx::DefaultSize,
	);

	my $generated_code_sizer = Wx::BoxSizer->new(Wx::HORIZONTAL);
	$generated_code_sizer->Add( $self->{generated_code_label}, 0, Wx::ALIGN_CENTER_VERTICAL | Wx::ALL, 5 );
	$generated_code_sizer->Add( $self->{generated_code_combo}, 0, Wx::ALL, 5 );

	my $bSizer13 = Wx::BoxSizer->new(Wx::VERTICAL);
	$bSizer13->Add( $self->{sample_code_checkbox}, 0, Wx::ALIGN_CENTER_VERTICAL | Wx::ALL | Wx::EXPAND, 5 );
	$bSizer13->Add( $self->{comments_checkbox}, 0, Wx::ALIGN_CENTER_VERTICAL | Wx::ALL | Wx::EXPAND, 5 );

	my $button_sizer = Wx::BoxSizer->new(Wx::HORIZONTAL);
	$button_sizer->Add( 0, 0, 1, Wx::EXPAND, 5 );
	$button_sizer->Add( $self->{ok_button}, 0, Wx::ALL, 5 );
	$button_sizer->Add( $self->{cancel_button}, 0, Wx::ALL, 5 );

	my $sizer = Wx::BoxSizer->new(Wx::VERTICAL);
	$sizer->Add( $m_staticText6, 0, Wx::EXPAND | Wx::LEFT | Wx::RIGHT | Wx::TOP, 5 );
	$sizer->Add( $generated_code_sizer, 0, Wx::EXPAND, 5 );
	$sizer->Add( $bSizer13, 1, Wx::EXPAND, 5 );
	$sizer->Add( $button_sizer, 0, Wx::EXPAND, 5 );

	$self->SetSizer($sizer);
	$self->Layout;

	return $self;
}

sub on_generated_code_combo {
	$_[0]->main->error('Handler method on_generated_code_combo for event generated_code_combo.OnCombobox not implemented');
}

		'Handler method on_sample_code_checkbox for event sample_code_checkbox.OnCheckBox not implemented');
	$_[0]->main->error('Handler method on_sample_code_checkbox for event sample_code_checkbox.OnCheckBox not implemented');
}

sub on_comments_checkbox {
	$_[0]->main->error('Handler method on_comments_checkbox for event comments_checkbox.OnCheckBox not implemented');
}

1;

# Copyright 2008-2012 The Padre development team as listed in Padre.pm.
# LICENSE
# This program is free software; you can redistribute it and/or
# modify it under the same terms as Perl 5 itself.

