package configSrv::Model::padreDB;

use strict;
use base 'Catalyst::Model::DBIC::Schema';

__PACKAGE__->config(
    schema_class => 'ConfigSrv::Schema',
    
    connect_info => {
        dsn => 'dbi:SQLite:db/data.db',
        user => '',
        password => '',
    }
);

=head1 NAME

configSrv::Model::padreDB - Catalyst DBIC Schema Model

=head1 SYNOPSIS

See L<configSrv>

=head1 DESCRIPTION

L<Catalyst::Model::DBIC::Schema> Model using schema L<ConfigSrv::Schema>

=head1 GENERATED BY

Catalyst::Helper::Model::DBIC::Schema - 0.4

=head1 AUTHOR



=head1 LICENSE

This library is free software, you can redistribute it and/or modify
it under the same terms as Perl itself.

=cut

1;
