---
name: Padre-Plugin-PerlCritic
version: 0.06
author:
  - 'Kaare Rasmussen <kaare@cpan.org>'
abstract: Analyze perl files with Perl::Critic
license: perl
resources:
  license: http://dev.perl.org/licenses/
requires:
  Padre: 0.25
  Perl::Critic: 0
  perl: 5.008
build_requires:
  Test::More: 0.47
provides:
  Padre::Plugin::PerlCritic:
    file: lib/Padre/Plugin/PerlCritic.pm
    version: 0.06
generated_by: Module::Build version 0.280801
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.2.html
  version: 1.2
