package Padre::Plugin::Snippet::FBP::Manager;

## no critic

# This module was generated by Padre::Plugin::FormBuilder::Perl.
# To change this module edit the original .fbp file and regenerate.
# DO NOT MODIFY THIS FILE BY HAND!

use 5.008005;
use utf8;
use strict;
use warnings;
use Padre::Wx             ();
use Padre::Wx::Role::Main ();
use Padre::Wx::Editor     ();

our $VERSION = '0.01';
our @ISA     = qw{
	Padre::Wx::Role::Main
	Wx::Dialog
};

sub new {
	my $class  = shift;
	my $parent = shift;

	my $self = $class->SUPER::new(
		$parent,
		-1,
		Wx::gettext("Snippet Manager"),
		Wx::DefaultPosition,
		[ 441, 275 ],
		Wx::DEFAULT_DIALOG_STYLE,
	);

	$self->{tree} = Wx::TreeCtrl->new(
		$self,
		-1,
		Wx::DefaultPosition,
		Wx::DefaultSize,
		Wx::TR_DEFAULT_STYLE,
	);

	$self->{trigger_label} = Wx::StaticText->new(
		$self,
		-1,
		Wx::gettext("Trigger:"),
	);
	$self->{trigger_label}->SetFont( Wx::Font->new( Wx::NORMAL_FONT->GetPointSize, 70, 90, 92, 0, "" ) );

	$self->{trigger_text} = Wx::TextCtrl->new(
		$self,
		-1,
		"",
		Wx::DefaultPosition,
		Wx::DefaultSize,
	);

	$self->{scope_label} = Wx::StaticText->new(
		$self,
		-1,
		Wx::gettext("Scope:"),
	);
	$self->{scope_label}->SetFont( Wx::Font->new( Wx::NORMAL_FONT->GetPointSize, 70, 90, 92, 0, "" ) );

	$self->{scope_combo} = Wx::ComboBox->new(
		$self,
		-1,
		"Combo!",
		Wx::DefaultPosition,
		Wx::DefaultSize,
		[],
	);

	$self->{snippet_label} = Wx::StaticText->new(
		$self,
		-1,
		Wx::gettext("Snippet:"),
	);
	$self->{snippet_label}->SetFont( Wx::Font->new( Wx::NORMAL_FONT->GetPointSize, 70, 90, 92, 0, "" ) );

	$self->{snippet_editor} = Padre::Wx::Editor->new(
		$self,
		-1,
	);

	$self->{save_button} = Wx::Button->new(
		$self,
		-1,
		Wx::gettext("&OK"),
		Wx::DefaultPosition,
		Wx::DefaultSize,
	);

	$self->{cancel_button} = Wx::Button->new(
		$self,
		Wx::ID_CANCEL,
		Wx::gettext("&Cancel"),
		Wx::DefaultPosition,
		Wx::DefaultSize,
	);

	my $left_sizer = Wx::BoxSizer->new(Wx::VERTICAL);
	$left_sizer->Add( $self->{tree}, 1, Wx::ALL, 5 );

	my $fgSizer1 = Wx::FlexGridSizer->new( 2, 2, 0, 0 );
	$fgSizer1->SetFlexibleDirection(Wx::BOTH);
	$fgSizer1->SetNonFlexibleGrowMode(Wx::FLEX_GROWMODE_SPECIFIED);
	$fgSizer1->Add( $self->{trigger_label}, 0, Wx::ALIGN_CENTER_VERTICAL | Wx::ALL, 5 );
	$fgSizer1->Add( $self->{trigger_text},  0, Wx::ALL,                             5 );
	$fgSizer1->Add( $self->{scope_label},   0, Wx::ALIGN_CENTER_VERTICAL | Wx::ALL, 5 );
	$fgSizer1->Add( $self->{scope_combo},   0, Wx::ALL,                             5 );

	my $right_sizer = Wx::BoxSizer->new(Wx::VERTICAL);
	$right_sizer->Add( $fgSizer1,               0, Wx::EXPAND,           5 );
	$right_sizer->Add( $self->{snippet_label},  0, Wx::ALL,              5 );
	$right_sizer->Add( $self->{snippet_editor}, 1, Wx::ALL | Wx::EXPAND, 5 );

	my $bSizer4 = Wx::BoxSizer->new(Wx::HORIZONTAL);
	$bSizer4->Add( $left_sizer,  0, Wx::EXPAND, 5 );
	$bSizer4->Add( $right_sizer, 1, Wx::EXPAND, 5 );

	my $button_sizer = Wx::BoxSizer->new(Wx::HORIZONTAL);
	$button_sizer->Add( 0, 0, 1, Wx::EXPAND, 5 );
	$button_sizer->Add( $self->{save_button},   0, Wx::ALL, 5 );
	$button_sizer->Add( $self->{cancel_button}, 0, Wx::ALL, 5 );

	my $bSizer7 = Wx::BoxSizer->new(Wx::VERTICAL);
	$bSizer7->Add( $bSizer4,      1, Wx::EXPAND, 5 );
	$bSizer7->Add( $button_sizer, 0, Wx::EXPAND, 5 );

	$self->SetSizer($bSizer7);
	$self->Layout;

	return $self;
}

1;

# Copyright 2008-2012 The Padre development team as listed in Padre.pm.
# LICENSE
# This program is free software; you can redistribute it and/or
# modify it under the same terms as Perl 5 itself.

