#!/usr/bin/perl
use strict;
use warnings;

# temporary tool to create executable using PAR

my $libs    = libs();
my $modules = modules();
my $cmd     = "pp -o padre -I lib  script/padre $modules $libs";
print "$cmd\n";
system $cmd;


sub libs {
    my @libs = qw(
                libwx_gtk2_adv-2.8.so.0
                libwx_gtk2_core-2.8.so.0
                libwx_base-2.8.so.0
                libwx_base_net-2.8.so.0
                libwx_gtk2_stc-2.8.so.0
                libwx_gtk2_html-2.8.so.0
    );
    my $c = '';
    $c .= "-l /home/gabor/perl5lib/lib/perl/5.8.8/Alien/wxWidgets/gtk_2_8_7/lib/$_ " for @libs;

    return $c;
}



sub modules {
    my @modules;
    open my $fh, '<', 'MANIFEST' or die $!;
    while (my $line = <$fh>) {
        chomp $line;
        if ($line =~ m{^lib/}) {
            $line = substr($line, 4, -3);
            $line =~ s{/}{::}g;
            push @modules, $line;
        }
    }
    my $m = '';
    $m .= "-M $_ " for @modules;

    return $m;
}


