---
name: Padre-Plugin-AcmePlayCode
version: 0.09
author:
  - 'Fayland Lam <fayland@gmail.com>'
abstract: 'L<Acme::PlayCode> Plugin for L<Padre>'
license: perl
resources:
  license: http://dev.perl.org/licenses/
requires:
  Acme::PlayCode: 0
  Padre: 0.26
build_requires:
  Test::More: 0
provides:
  Padre::Plugin::AcmePlayCode:
    file: lib/Padre/Plugin/AcmePlayCode.pm
    version: 0.09
generated_by: Module::Build version 0.33
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: 1.4
