package Padre::Plugin::Patch::FBP::MainFB;

## no critic

# This module was generated by Padre::Plugin::FormBuilder::Perl.
# To change this module edit the original .fbp file and regenerate.
# DO NOT MODIFY THIS FILE BY HAND!

use 5.008;
use strict;
use warnings;
use Padre::Wx ();
use Padre::Wx::Role::Main ();

our $VERSION = '0.02';
our @ISA     = qw{
	Padre::Wx::Role::Main
	Wx::Dialog
};

sub new {
	my $class  = shift;
	my $parent = shift;

	my $self = $class->SUPER::new(
		$parent,
		-1,
		Wx::gettext("Main"),
		Wx::wxDefaultPosition,
		[ 670, 200 ],
		Wx::wxDEFAULT_DIALOG_STYLE | Wx::wxRESIZE_BORDER,
	);

	my $package_name = Wx::StaticText->new(
		$self,
		-1,
		Wx::gettext("Padre Patch"),
	);
	$package_name->SetFont(
		Wx::Font->new( 14, 70, 90, 92, 0, "" )
	);

	my $m_staticline1_1 = Wx::StaticLine->new(
		$self,
		-1,
		Wx::wxDefaultPosition,
		Wx::wxDefaultSize,
		Wx::wxLI_HORIZONTAL,
	);

	my $label1 = Wx::StaticText->new(
		$self,
		-1,
		Wx::gettext("File-1"),
	);

	my $file1 = Wx::Choice->new(
		$self,
		-1,
		Wx::wxDefaultPosition,
		Wx::wxDefaultSize,
		[],
	);
	$file1->SetSelection(0);
	$file1->SetMinSize( [ 600, -1 ] );

	my $m_staticline1_2 = Wx::StaticLine->new(
		$self,
		-1,
		Wx::wxDefaultPosition,
		Wx::wxDefaultSize,
		Wx::wxLI_HORIZONTAL,
	);

	my $label2 = Wx::StaticText->new(
		$self,
		-1,
		Wx::gettext("File-2"),
	);

	my $file2 = Wx::Choice->new(
		$self,
		-1,
		Wx::wxDefaultPosition,
		Wx::wxDefaultSize,
		[],
	);
	$file2->SetSelection(0);
	$file2->SetMinSize( [ 600, -1 ] );

	my $m_staticline3 = Wx::StaticLine->new(
		$self,
		-1,
		Wx::wxDefaultPosition,
		Wx::wxDefaultSize,
		Wx::wxLI_HORIZONTAL,
	);

	my $action = Wx::RadioBox->new(
		$self,
		-1,
		Wx::gettext("Action"),
		Wx::wxDefaultPosition,
		Wx::wxDefaultSize,
		[
			"Patch",
			"Diff",
		],
		1,
		Wx::wxRA_SPECIFY_ROWS,
	);
	$action->SetSelection(0);

	my $file2svn = Wx::RadioBox->new(
		$self,
		-1,
		Wx::gettext("File-2 or SVN::Class"),
		Wx::wxDefaultPosition,
		Wx::wxDefaultSize,
		[
			"File",
			"SVN",
		],
		1,
		Wx::wxRA_SPECIFY_ROWS,
	);
	$file2svn->SetSelection(0);

	my $process = Wx::Button->new(
		$self,
		-1,
		Wx::gettext("Process"),
		Wx::wxDefaultPosition,
		Wx::wxDefaultSize,
	);

	Wx::Event::EVT_BUTTON(
		$self,
		$process,
		sub {
			shift->process_clicked(@_);
		},
	);

	my $close_button = Wx::Button->new(
		$self,
		Wx::wxID_CANCEL,
		Wx::gettext("Close"),
		Wx::wxDefaultPosition,
		Wx::wxDefaultSize,
	);
	$close_button->SetDefault;

	my $bSizer1 = Wx::BoxSizer->new(Wx::wxHORIZONTAL);
	$bSizer1->Add( $package_name, 0, Wx::wxALL, 5 );
	$bSizer1->Add( 0, 0, 1, Wx::wxEXPAND, 5 );

	my $bSizer5 = Wx::BoxSizer->new(Wx::wxHORIZONTAL);
	$bSizer5->Add( $label1, 0, Wx::wxALL, 5 );
	$bSizer5->Add( $file1, 1, Wx::wxALL, 5 );

	my $bSizer51 = Wx::BoxSizer->new(Wx::wxHORIZONTAL);
	$bSizer51->Add( $label2, 0, Wx::wxALL, 5 );
	$bSizer51->Add( $file2, 1, Wx::wxALL, 5 );

	my $buttons = Wx::BoxSizer->new(Wx::wxHORIZONTAL);
	$buttons->Add( $action, 0, Wx::wxALL, 5 );
	$buttons->Add( $file2svn, 0, Wx::wxALL, 5 );
	$buttons->Add( 0, 0, 1, Wx::wxEXPAND, 5 );
	$buttons->Add( $process, 0, Wx::wxALL, 5 );
	$buttons->Add( 0, 0, 1, Wx::wxEXPAND, 5 );
	$buttons->Add( $close_button, 0, Wx::wxALL, 5 );

	my $vsizer = Wx::BoxSizer->new(Wx::wxVERTICAL);
	$vsizer->Add( $bSizer1, 0, Wx::wxEXPAND, 3 );
	$vsizer->Add( $m_staticline1_1, 0, Wx::wxEXPAND | Wx::wxALL, 1 );
	$vsizer->Add( $bSizer5, 1, Wx::wxALL | Wx::wxEXPAND, 1 );
	$vsizer->Add( $m_staticline1_2, 0, Wx::wxALL | Wx::wxEXPAND, 1 );
	$vsizer->Add( $bSizer51, 1, Wx::wxEXPAND, 5 );
	$vsizer->Add( $m_staticline3, 0, Wx::wxEXPAND | Wx::wxALL, 5 );
	$vsizer->Add( $buttons, 0, Wx::wxEXPAND, 3 );

	my $sizer = Wx::BoxSizer->new(Wx::wxHORIZONTAL);
	$sizer->Add( $vsizer, 0, Wx::wxALL, 1 );

	$self->SetSizer($sizer);
	$self->Layout;

	$self->{package_name} = $package_name->GetId;
	$self->{file1} = $file1->GetId;
	$self->{file2} = $file2->GetId;
	$self->{action} = $action->GetId;
	$self->{file2svn} = $file2svn->GetId;
	$self->{process} = $process->GetId;

	return $self;
}

sub package_name {
	Wx::Window::FindWindowById($_[0]->{package_name});
}

sub file1 {
	Wx::Window::FindWindowById($_[0]->{file1});
}

sub file2 {
	Wx::Window::FindWindowById($_[0]->{file2});
}

sub action {
	Wx::Window::FindWindowById($_[0]->{action});
}

sub file2svn {
	Wx::Window::FindWindowById($_[0]->{file2svn});
}

sub process {
	Wx::Window::FindWindowById($_[0]->{process});
}

sub process_clicked {
	$_[0]->main->error('Handler method process_clicked for event process.OnButtonClick not implemented');
}

1;

# Copyright 2008-2011 The Padre development team as listed in Padre.pm.
# LICENSE
# This program is free software; you can redistribute it and/or
# modify it under the same terms as Perl 5 itself.

