package Padre::Plugin::Patch::FBP::MainFB;

## no critic

# This module was generated by Padre::Plugin::FormBuilder::Perl.
# To change this module edit the original .fbp file and regenerate.
# DO NOT MODIFY THIS FILE BY HAND!

use 5.008;
use strict;
use warnings;
use Padre::Wx ();
use Padre::Wx::Role::Main ();

our $VERSION = '0.03';
our @ISA     = qw{
	Padre::Wx::Role::Main
	Wx::Dialog
};

sub new {
	my $class  = shift;
	my $parent = shift;

	my $self = $class->SUPER::new(
		$parent,
		-1,
		Wx::gettext("Patch"),
		Wx::wxDefaultPosition,
		Wx::wxDefaultSize,
		Wx::wxDEFAULT_DIALOG_STYLE | Wx::wxRESIZE_BORDER,
	);

	my $file1 = Wx::Choice->new(
		$self,
		-1,
		Wx::wxDefaultPosition,
		[ 200, -1 ],
		[],
	);
	$file1->SetSelection(0);

	my $action = Wx::RadioBox->new(
		$self,
		-1,
		Wx::gettext("Action"),
		Wx::wxDefaultPosition,
		Wx::wxDefaultSize,
		[
			"Patch",
			"Diff",
		],
		1,
		Wx::wxRA_SPECIFY_COLS,
	);
	$action->SetSelection(0);

	Wx::Event::EVT_RADIOBOX(
		$self,
		$action,
		sub {
			shift->on_action(@_);
		},
	);

	my $against = Wx::RadioBox->new(
		$self,
		-1,
		Wx::gettext("Against"),
		Wx::wxDefaultPosition,
		Wx::wxDefaultSize,
		[
			"File-2",
			"SVN",
			"Git",
		],
		2,
		Wx::wxRA_SPECIFY_COLS,
	);
	$against->SetSelection(0);
	$against->Disable;

	Wx::Event::EVT_RADIOBOX(
		$self,
		$against,
		sub {
			shift->on_against(@_);
		},
	);

	my $file2 = Wx::Choice->new(
		$self,
		-1,
		Wx::wxDefaultPosition,
		Wx::wxDefaultSize,
		[],
	);
	$file2->SetSelection(0);
	$file2->SetMinSize( [ 200, -1 ] );

	my $process = Wx::Button->new(
		$self,
		-1,
		Wx::gettext("Process"),
		Wx::wxDefaultPosition,
		Wx::wxDefaultSize,
	);

	Wx::Event::EVT_BUTTON(
		$self,
		$process,
		sub {
			shift->process_clicked(@_);
		},
	);

	my $close_button = Wx::Button->new(
		$self,
		Wx::wxID_CANCEL,
		Wx::gettext("Close"),
		Wx::wxDefaultPosition,
		Wx::wxDefaultSize,
	);
	$close_button->SetDefault;

	my $m_staticline5 = Wx::StaticLine->new(
		$self,
		-1,
		Wx::wxDefaultPosition,
		Wx::wxDefaultSize,
		Wx::wxLI_HORIZONTAL,
	);

	my $file_1 = Wx::StaticBoxSizer->new(
		Wx::StaticBox->new(
			$self,
			-1,
			Wx::gettext("File-1"),
		),
		Wx::wxVERTICAL,
	);
	$file_1->Add( $file1, 0, Wx::wxALL, 5 );

	my $sbSizer2 = Wx::StaticBoxSizer->new(
		Wx::StaticBox->new(
			$self,
			-1,
			Wx::gettext("Options"),
		),
		Wx::wxHORIZONTAL,
	);
	$sbSizer2->Add( 0, 0, 1, Wx::wxEXPAND, 5 );
	$sbSizer2->Add( $action, 0, Wx::wxALL, 5 );
	$sbSizer2->Add( 0, 0, 1, Wx::wxEXPAND, 5 );
	$sbSizer2->Add( $against, 0, Wx::wxALL, 5 );

	my $file_2 = Wx::StaticBoxSizer->new(
		Wx::StaticBox->new(
			$self,
			-1,
			Wx::gettext("File-2"),
		),
		Wx::wxVERTICAL,
	);
	$file_2->Add( $file2, 1, Wx::wxALL, 5 );

	my $buttons = Wx::BoxSizer->new(Wx::wxHORIZONTAL);
	$buttons->Add( 0, 0, 1, Wx::wxEXPAND, 5 );
	$buttons->Add( $process, 0, Wx::wxALL, 5 );
	$buttons->Add( 0, 0, 1, Wx::wxEXPAND, 5 );
	$buttons->Add( $close_button, 0, Wx::wxALL, 5 );

	my $vsizer = Wx::BoxSizer->new(Wx::wxVERTICAL);
	$vsizer->Add( $file_1, 0, Wx::wxEXPAND, 5 );
	$vsizer->Add( $sbSizer2, 1, Wx::wxEXPAND, 5 );
	$vsizer->Add( $file_2, 0, Wx::wxEXPAND, 5 );
	$vsizer->Add( $buttons, 0, Wx::wxEXPAND, 3 );
	$vsizer->Add( $m_staticline5, 0, Wx::wxEXPAND | Wx::wxALL, 5 );

	my $sizer = Wx::BoxSizer->new(Wx::wxHORIZONTAL);
	$sizer->Add( $vsizer, 0, Wx::wxALL, 1 );

	$self->SetSizerAndFit($sizer);
	$self->Layout;

	$self->{file1} = $file1->GetId;
	$self->{action} = $action->GetId;
	$self->{against} = $against->GetId;
	$self->{file2} = $file2->GetId;
	$self->{process} = $process->GetId;

	return $self;
}

sub file1 {
	Wx::Window::FindWindowById($_[0]->{file1});
}

sub action {
	Wx::Window::FindWindowById($_[0]->{action});
}

sub against {
	Wx::Window::FindWindowById($_[0]->{against});
}

sub file2 {
	Wx::Window::FindWindowById($_[0]->{file2});
}

sub process {
	Wx::Window::FindWindowById($_[0]->{process});
}

sub on_action {
	$_[0]->main->error('Handler method on_action for event action.OnRadioBox not implemented');
}

sub on_against {
	$_[0]->main->error('Handler method on_against for event against.OnRadioBox not implemented');
}

sub process_clicked {
	$_[0]->main->error('Handler method process_clicked for event process.OnButtonClick not implemented');
}

1;

# Copyright 2008-2011 The Padre development team as listed in Padre.pm.
# LICENSE
# This program is free software; you can redistribute it and/or
# modify it under the same terms as Perl 5 itself.

