---
name: Padre-Plugin-Encrypt
version: 0.03
author:
  - 'Fayland Lam <fayland@gmail.com>'
abstract: encrypt/decrypt file in Padre
license: perl
resources:
  license: http://dev.perl.org/licenses/
build_requires:
  Crypt::Blowfish: 0
  Crypt::CBC: 0
  Padre: 0.18
  Padre::Wx::Dialog: 0
  Test::More: 0
provides:
  Padre::Plugin::Encrypt:
    file: lib/Padre/Plugin/Encrypt.pm
    version: 0.03
generated_by: Module::Build version 0.3
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.2.html
  version: 1.2
