---
name: Padre-Plugin-LaTeX
version: 0.02
author:
  - 'Zeno Gantner <ZENOG@cpan.org>'
abstract: L<Padre> and LaTeX
license: perl
resources:
  homepage: http://padre.perlide.org/
  license: http://dev.perl.org/licenses/
  repository: http://svn.perlide.org/padre/trunk/Padre-Plugin-LaTeX/
requires:
  Padre: 0.64
build_requires:
  Test::More: 0
provides:
  Padre::Document::LaTeX:
    file: lib/Padre/Document/LaTeX.pm
    version: 0.02
  Padre::Plugin::LaTeX:
    file: lib/Padre/Plugin/LaTeX.pm
    version: 0.02
generated_by: Module::Build version 0.33
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: 1.4
