---
# Copyright 2008 Gabor Szabo.
# LICENSE
# This program is free software; you can redistribute it and/or
# modify it under the same terms as Perl 5 itself.
plain:
 foregrounds:
  0: 00007f
 current_line_foreground: 000000
 current_line_background: FFFF04
perl:
 brace_highlight: 00FF00
 background: ffffff
 colors:
  wxSTC_PL_DEFAULT:        000000
  wxSTC_PL_ERROR:          ff0000
  wxSTC_PL_COMMENTLINE:    007f00
  wxSTC_PL_POD:            7f7f7f
  wxSTC_PL_NUMBER:         007f7f
  wxSTC_PL_WORD:           00007f
  wxSTC_PL_STRING:         ff7f00
  wxSTC_PL_CHARACTER:      7f007f
  wxSTC_PL_PUNCTUATION:    000000
  wxSTC_PL_PREPROCESSOR:   7f7f7f
  wxSTC_PL_OPERATOR:       00007f
  wxSTC_PL_IDENTIFIER:     0000ff
  wxSTC_PL_SCALAR:         7f007f
  wxSTC_PL_ARRAY:          4080ff
  wxSTC_PL_HASH:           0080ff
  wxSTC_PL_SYMBOLTABLE:    00ff00
# missing SCE_PL_VARIABLE_INDEXER (16)
  wxSTC_PL_REGEX:          ff007f
  wxSTC_PL_REGSUBST:       7f7f00
  wxSTC_PL_LONGQUOTE:      ff7f00
  wxSTC_PL_BACKTICKS:      ffaa00
  wxSTC_PL_DATASECTION:    ff7f00
  wxSTC_PL_HERE_DELIM:     ff7f00
  wxSTC_PL_HERE_Q:         7f007f
  wxSTC_PL_HERE_QQ:        ff7f00
  wxSTC_PL_HERE_QX:        ffaa00
  wxSTC_PL_STRING_Q:       7f007f
  wxSTC_PL_STRING_QQ:      ff7f00
  wxSTC_PL_STRING_QX:      ffaa00
  wxSTC_PL_STRING_QR:      ff007f
  wxSTC_PL_STRING_QW:      7f007f
# missing:
#define SCE_PL_POD_VERB 31
#define SCE_PL_SUB_PROTOTYPE 40
#define SCE_PL_FORMAT_IDENT 41
#define SCE_PL_FORMAT 42
padre:
 brace_highlight: 00FF00
 background: ffffff
 colors:
  PADRE_BLACK:          000000
  PADRE_BLUE:           000099
  PADRE_RED:      990000
  PADRE_GREEN:    00AA00
  PADRE_MAGENTA:  8b008b
  PADRE_ORANGE:   ff8228
  PADRE_CRIMSON:        dc143c
  PADRE_BROWN:          a52a2a
