---
name: Padre-Plugin-XML
version: 0.03
author:
  - 'Fayland Lam <fayland@gmail.com>'
abstract: L<Padre> and XML
license: perl
resources:
  license: http://dev.perl.org/licenses/
build_requires:
  Padre: 0.22
  Test::More: 0
  XML::LibXML: 1.67
  XML::Tidy: 0
provides:
  Padre::Document::XML:
    file: lib/Padre/Document/XML.pm
    version: 0.03
  Padre::Plugin::XML:
    file: lib/Padre/Plugin/XML.pm
    version: 0.03
  Padre::Task::SyntaxChecker::XML:
    file: lib/Padre/Task/SyntaxChecker/XML.pm
    version: 0.01
generated_by: Module::Build version 0.31
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.2.html
  version: 1.2
