---
name: Padre-Plugin-SpellCheck
version: 0.01
author:
  - 'Jerome Quelin <jquelin@gmail.com>'
abstract: Spell Check in Padre
license: perl
resources:
  license: http://dev.perl.org/licenses/
requires:
  File::Basename: 0
  File::Spec::Functions: 0
  Module::Util: 0
  Padre: 0.30
build_requires:
  Test::More: 0
generated_by: Module::Build version 0.32
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.2.html
  version: 1.2
