---
name: Padre-Plugin-SpellCheck
version: 1.1.0
author:
  - 'Jerome Quelin <jquelin@gmail.com>'
abstract: check spelling in Padre
license: perl
resources:
  license: http://dev.perl.org/licenses/
requires:
  Class::XSAccessor: 0
  File::Basename: 0
  File::Spec::Functions: 0
  Module::Util: 0
  Padre: 0.26
  Text::Aspell: 0
build_requires:
  Test::More: 0
provides:
  Padre::Plugin::SpellCheck:
    file: lib/Padre/Plugin/SpellCheck.pm
    version: 1.1.0
  Padre::Plugin::SpellCheck::Dialog:
    file: lib/Padre/Plugin/SpellCheck/Dialog.pm
  Padre::Plugin::SpellCheck::Engine:
    file: lib/Padre/Plugin/SpellCheck/Engine.pm
  Padre::Plugin::SpellCheck::Preferences:
    file: lib/Padre/Plugin/SpellCheck/Preferences.pm
generated_by: Module::Build version 0.32
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.2.html
  version: 1.2
