---
name: Padre-Plugin-SpellCheck
version: 1.1.2
author:
  - 'Jerome Quelin <jquelin@gmail.com>'
abstract: check spelling in Padre
license: perl
resources:
  homepage: http://padre.perlide.org/
  license: http://dev.perl.org/licenses/
  repository: http://svn.perlide.org/padre/trunk/Padre-Plugin-SpellCheck/
requires:
  Class::XSAccessor: 0
  File::Basename: 0
  File::Spec::Functions: 0
  Module::Util: 0
  Padre: 0.43
  Text::Aspell: 0
build_requires:
  Test::More: 0
generated_by: Module::Build version 0.33
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: 1.4
