package Wx::Scintilla;

use strict;
use warnings;
use Wx;
use Carp;

our $VERSION = '0.31_02';

# Define Perl 6 lexer
use constant wxSCINTILLA_LEX_PERL6  => 102;
use constant wxSCINTILLA_P6_DEFAULT => 0;
use constant wxSCINTILLA_P6_COMMENT => 1;
use constant wxSCINTILLA_P6_STRING  => 2;

use constant {
	wxSTC_INVALID_POSITION                => -1,
	wxSTC_START                           => 2000,
	wxSTC_OPTIONAL_START                  => 3000,
	wxSTC_LEXER_START                     => 4000,
	wxSTC_WS_INVISIBLE                    => 0,
	wxSTC_WS_VISIBLEALWAYS                => 1,
	wxSTC_WS_VISIBLEAFTERINDENT           => 2,
	wxSTC_EOL_CRLF                        => 0,
	wxSTC_EOL_CR                          => 1,
	wxSTC_EOL_LF                          => 2,
	wxSTC_CP_UTF8                         => 65001,
	wxSTC_CP_DBCS                         => 1,
	wxSTC_MARKER_MAX                      => 31,
	wxSTC_MARK_CIRCLE                     => 0,
	wxSTC_MARK_ROUNDRECT                  => 1,
	wxSTC_MARK_ARROW                      => 2,
	wxSTC_MARK_SMALLRECT                  => 3,
	wxSTC_MARK_SHORTARROW                 => 4,
	wxSTC_MARK_EMPTY                      => 5,
	wxSTC_MARK_ARROWDOWN                  => 6,
	wxSTC_MARK_MINUS                      => 7,
	wxSTC_MARK_PLUS                       => 8,
	wxSTC_MARK_VLINE                      => 9,
	wxSTC_MARK_LCORNER                    => 10,
	wxSTC_MARK_TCORNER                    => 11,
	wxSTC_MARK_BOXPLUS                    => 12,
	wxSTC_MARK_BOXPLUSCONNECTED           => 13,
	wxSTC_MARK_BOXMINUS                   => 14,
	wxSTC_MARK_BOXMINUSCONNECTED          => 15,
	wxSTC_MARK_LCORNERCURVE               => 16,
	wxSTC_MARK_TCORNERCURVE               => 17,
	wxSTC_MARK_CIRCLEPLUS                 => 18,
	wxSTC_MARK_CIRCLEPLUSCONNECTED        => 19,
	wxSTC_MARK_CIRCLEMINUS                => 20,
	wxSTC_MARK_CIRCLEMINUSCONNECTED       => 21,
	wxSTC_MARK_BACKGROUND                 => 22,
	wxSTC_MARK_DOTDOTDOT                  => 23,
	wxSTC_MARK_ARROWS                     => 24,
	wxSTC_MARK_PIXMAP                     => 25,
	wxSTC_MARK_FULLRECT                   => 26,
	wxSTC_MARK_LEFTRECT                   => 27,
	wxSTC_MARK_AVAILABLE                  => 28,
	wxSTC_MARK_UNDERLINE                  => 29,
	wxSTC_MARK_CHARACTER                  => 10000,
	wxSTC_MARKNUM_FOLDEREND               => 25,
	wxSTC_MARKNUM_FOLDEROPENMID           => 26,
	wxSTC_MARKNUM_FOLDERMIDTAIL           => 27,
	wxSTC_MARKNUM_FOLDERTAIL              => 28,
	wxSTC_MARKNUM_FOLDERSUB               => 29,
	wxSTC_MARKNUM_FOLDER                  => 30,
	wxSTC_MARKNUM_FOLDEROPEN              => 31,
	wxSTC_MASK_FOLDERS                    => 0xFE000000,
	wxSTC_MARGIN_SYMBOL                   => 0,
	wxSTC_MARGIN_NUMBER                   => 1,
	wxSTC_MARGIN_BACK                     => 2,
	wxSTC_MARGIN_FORE                     => 3,
	wxSTC_MARGIN_TEXT                     => 4,
	wxSTC_MARGIN_RTEXT                    => 5,
	wxSTC_STYLE_DEFAULT                   => 32,
	wxSTC_STYLE_LINENUMBER                => 33,
	wxSTC_STYLE_BRACELIGHT                => 34,
	wxSTC_STYLE_BRACEBAD                  => 35,
	wxSTC_STYLE_CONTROLCHAR               => 36,
	wxSTC_STYLE_INDENTGUIDE               => 37,
	wxSTC_STYLE_CALLTIP                   => 38,
	wxSTC_STYLE_LASTPREDEFINED            => 39,
	wxSTC_STYLE_MAX                       => 255,
	wxSTC_CHARSET_ANSI                    => 0,
	wxSTC_CHARSET_DEFAULT                 => 1,
	wxSTC_CHARSET_BALTIC                  => 186,
	wxSTC_CHARSET_CHINESEBIG5             => 136,
	wxSTC_CHARSET_EASTEUROPE              => 238,
	wxSTC_CHARSET_GB2312                  => 134,
	wxSTC_CHARSET_GREEK                   => 161,
	wxSTC_CHARSET_HANGUL                  => 129,
	wxSTC_CHARSET_MAC                     => 77,
	wxSTC_CHARSET_OEM                     => 255,
	wxSTC_CHARSET_RUSSIAN                 => 204,
	wxSTC_CHARSET_CYRILLIC                => 1251,
	wxSTC_CHARSET_SHIFTJIS                => 128,
	wxSTC_CHARSET_SYMBOL                  => 2,
	wxSTC_CHARSET_TURKISH                 => 162,
	wxSTC_CHARSET_JOHAB                   => 130,
	wxSTC_CHARSET_HEBREW                  => 177,
	wxSTC_CHARSET_ARABIC                  => 178,
	wxSTC_CHARSET_VIETNAMESE              => 163,
	wxSTC_CHARSET_THAI                    => 222,
	wxSTC_CHARSET_8859_15                 => 1000,
	wxSTC_CASE_MIXED                      => 0,
	wxSTC_CASE_UPPER                      => 1,
	wxSTC_CASE_LOWER                      => 2,
	wxSTC_INDIC_PLAIN                     => 0,
	wxSTC_INDIC_SQUIGGLE                  => 1,
	wxSTC_INDIC_TT                        => 2,
	wxSTC_INDIC_DIAGONAL                  => 3,
	wxSTC_INDIC_STRIKE                    => 4,
	wxSTC_INDIC_HIDDEN                    => 5,
	wxSTC_INDIC_BOX                       => 6,
	wxSTC_INDIC_ROUNDBOX                  => 7,
	wxSTC_INDIC_STRAIGHTBOX               => 8,
	wxSTC_INDIC_DASH                      => 9,
	wxSTC_INDIC_DOTS                      => 10,
	wxSTC_INDIC_SQUIGGLELOW               => 11,
	wxSTC_INDIC_DOTBOX                    => 12,
	wxSTC_INDIC_MAX                       => 31,
	wxSTC_INDIC_CONTAINER                 => 8,
	wxSTC_INDIC0_MASK                     => 0x20,
	wxSTC_INDIC1_MASK                     => 0x40,
	wxSTC_INDIC2_MASK                     => 0x80,
	wxSTC_INDICS_MASK                     => 0xE0,
	wxSTC_IV_NONE                         => 0,
	wxSTC_IV_REAL                         => 1,
	wxSTC_IV_LOOKFORWARD                  => 2,
	wxSTC_IV_LOOKBOTH                     => 3,
	wxSTC_PRINT_NORMAL                    => 0,
	wxSTC_PRINT_INVERTLIGHT               => 1,
	wxSTC_PRINT_BLACKONWHITE              => 2,
	wxSTC_PRINT_COLOURONWHITE             => 3,
	wxSTC_PRINT_COLOURONWHITEDEFAULTBG    => 4,
	wxSTC_FIND_WHOLEWORD                  => 2,
	wxSTC_FIND_MATCHCASE                  => 4,
	wxSTC_FIND_WORDSTART                  => 0x00100000,
	wxSTC_FIND_REGEXP                     => 0x00200000,
	wxSTC_FIND_POSIX                      => 0x00400000,
	wxSTC_FOLDLEVELBASE                   => 0x400,
	wxSTC_FOLDLEVELWHITEFLAG              => 0x1000,
	wxSTC_FOLDLEVELHEADERFLAG             => 0x2000,
	wxSTC_FOLDLEVELNUMBERMASK             => 0x0FFF,
	wxSTC_FOLDFLAG_LINEBEFORE_EXPANDED    => 0x0002,
	wxSTC_FOLDFLAG_LINEBEFORE_CONTRACTED  => 0x0004,
	wxSTC_FOLDFLAG_LINEAFTER_EXPANDED     => 0x0008,
	wxSTC_FOLDFLAG_LINEAFTER_CONTRACTED   => 0x0010,
	wxSTC_FOLDFLAG_LEVELNUMBERS           => 0x0040,
	wxSTC_TIME_FOREVER                    => 10000000,
	wxSTC_WRAP_NONE                       => 0,
	wxSTC_WRAP_WORD                       => 1,
	wxSTC_WRAP_CHAR                       => 2,
	wxSTC_WRAPVISUALFLAG_NONE             => 0x0000,
	wxSTC_WRAPVISUALFLAG_END              => 0x0001,
	wxSTC_WRAPVISUALFLAG_START            => 0x0002,
	wxSTC_WRAPVISUALFLAGLOC_DEFAULT       => 0x0000,
	wxSTC_WRAPVISUALFLAGLOC_END_BY_TEXT   => 0x0001,
	wxSTC_WRAPVISUALFLAGLOC_START_BY_TEXT => 0x0002,
	wxSTC_WRAPINDENT_FIXED                => 0,
	wxSTC_WRAPINDENT_SAME                 => 1,
	wxSTC_WRAPINDENT_INDENT               => 2,
	wxSTC_CACHE_NONE                      => 0,
	wxSTC_CACHE_CARET                     => 1,
	wxSTC_CACHE_PAGE                      => 2,
	wxSTC_CACHE_DOCUMENT                  => 3,
	wxSTC_EFF_QUALITY_MASK                => 0xF,
	wxSTC_EFF_QUALITY_DEFAULT             => 0,
	wxSTC_EFF_QUALITY_NON_ANTIALIASED     => 1,
	wxSTC_EFF_QUALITY_ANTIALIASED         => 2,
	wxSTC_EFF_QUALITY_LCD_OPTIMIZED       => 3,
	wxSTC_EDGE_NONE                       => 0,
	wxSTC_EDGE_LINE                       => 1,
	wxSTC_EDGE_BACKGROUND                 => 2,
	wxSTC_STATUS_OK                       => 0,
	wxSTC_STATUS_FAILURE                  => 1,
	wxSTC_STATUS_BADALLOC                 => 2,
	wxSTC_CURSORNORMAL                    => -1,
	wxSTC_CURSORWAIT                      => 4,
	wxSTC_VISIBLE_SLOP                    => 0x01,
	wxSTC_VISIBLE_STRICT                  => 0x04,
	wxSTC_CARET_SLOP                      => 0x01,
	wxSTC_CARET_STRICT                    => 0x04,
	wxSTC_CARET_JUMPS                     => 0x10,
	wxSTC_CARET_EVEN                      => 0x08,
	wxSTC_SEL_STREAM                      => 0,
	wxSTC_SEL_RECTANGLE                   => 1,
	wxSTC_SEL_LINES                       => 2,
	wxSTC_SEL_THIN                        => 3,
	wxSTC_ALPHA_TRANSPARENT               => 0,
	wxSTC_ALPHA_OPAQUE                    => 255,
	wxSTC_ALPHA_NOALPHA                   => 256,
	wxSTC_CARETSTYLE_INVISIBLE            => 0,
	wxSTC_CARETSTYLE_LINE                 => 1,
	wxSTC_CARETSTYLE_BLOCK                => 2,
	wxSTC_ANNOTATION_HIDDEN               => 0,
	wxSTC_ANNOTATION_STANDARD             => 1,
	wxSTC_ANNOTATION_BOXED                => 2,
	wxSTC_UNDO_MAY_COALESCE               => 1,
	wxSTC_SCVS_NONE                       => 0,
	wxSTC_SCVS_RECTANGULARSELECTION       => 1,
	wxSTC_SCVS_USERACCESSIBLE             => 2,
	wxSTC_KEYWORDSET_MAX                  => 8,
	wxSTC_MOD_INSERTTEXT                  => 0x1,
	wxSTC_MOD_DELETETEXT                  => 0x2,
	wxSTC_MOD_CHANGESTYLE                 => 0x4,
	wxSTC_MOD_CHANGEFOLD                  => 0x8,
	wxSTC_PERFORMED_USER                  => 0x10,
	wxSTC_PERFORMED_UNDO                  => 0x20,
	wxSTC_PERFORMED_REDO                  => 0x40,
	wxSTC_MULTISTEPUNDOREDO               => 0x80,
	wxSTC_LASTSTEPINUNDOREDO              => 0x100,
	wxSTC_MOD_CHANGEMARKER                => 0x200,
	wxSTC_MOD_BEFOREINSERT                => 0x400,
	wxSTC_MOD_BEFOREDELETE                => 0x800,
	wxSTC_MULTILINEUNDOREDO               => 0x1000,
	wxSTC_STARTACTION                     => 0x2000,
	wxSTC_MOD_CHANGEINDICATOR             => 0x4000,
	wxSTC_MOD_CHANGELINESTATE             => 0x8000,
	wxSTC_MOD_CHANGEMARGIN                => 0x10000,
	wxSTC_MOD_CHANGEANNOTATION            => 0x20000,
	wxSTC_MOD_CONTAINER                   => 0x40000,
	wxSTC_MODEVENTMASKALL                 => 0x7FFFF,
	wxSTC_KEY_DOWN                        => 300,
	wxSTC_KEY_UP                          => 301,
	wxSTC_KEY_LEFT                        => 302,
	wxSTC_KEY_RIGHT                       => 303,
	wxSTC_KEY_HOME                        => 304,
	wxSTC_KEY_END                         => 305,
	wxSTC_KEY_PRIOR                       => 306,
	wxSTC_KEY_NEXT                        => 307,
	wxSTC_KEY_DELETE                      => 308,
	wxSTC_KEY_INSERT                      => 309,
	wxSTC_KEY_ESCAPE                      => 7,
	wxSTC_KEY_BACK                        => 8,
	wxSTC_KEY_TAB                         => 9,
	wxSTC_KEY_RETURN                      => 13,
	wxSTC_KEY_ADD                         => 310,
	wxSTC_KEY_SUBTRACT                    => 311,
	wxSTC_KEY_DIVIDE                      => 312,
	wxSTC_KEY_WIN                         => 313,
	wxSTC_KEY_RWIN                        => 314,
	wxSTC_KEY_MENU                        => 315,
	wxSTC_SCMOD_NORM                      => 0,
	wxSTC_SCMOD_SHIFT                     => 1,
	wxSTC_SCMOD_CTRL                      => 2,
	wxSTC_SCMOD_ALT                       => 4,
	wxSTC_SCMOD_SUPER                     => 8,
	wxSTC_LEX_CONTAINER                   => 0,
	wxSTC_LEX_NULL                        => 1,
	wxSTC_LEX_PYTHON                      => 2,
	wxSTC_LEX_CPP                         => 3,
	wxSTC_LEX_HTML                        => 4,
	wxSTC_LEX_XML                         => 5,
	wxSTC_LEX_PERL                        => 6,
	wxSTC_LEX_SQL                         => 7,
	wxSTC_LEX_VB                          => 8,
	wxSTC_LEX_PROPERTIES                  => 9,
	wxSTC_LEX_ERRORLIST                   => 10,
	wxSTC_LEX_MAKEFILE                    => 11,
	wxSTC_LEX_BATCH                       => 12,
	wxSTC_LEX_XCODE                       => 13,
	wxSTC_LEX_LATEX                       => 14,
	wxSTC_LEX_LUA                         => 15,
	wxSTC_LEX_DIFF                        => 16,
	wxSTC_LEX_CONF                        => 17,
	wxSTC_LEX_PASCAL                      => 18,
	wxSTC_LEX_AVE                         => 19,
	wxSTC_LEX_ADA                         => 20,
	wxSTC_LEX_LISP                        => 21,
	wxSTC_LEX_RUBY                        => 22,
	wxSTC_LEX_EIFFEL                      => 23,
	wxSTC_LEX_EIFFELKW                    => 24,
	wxSTC_LEX_TCL                         => 25,
	wxSTC_LEX_NNCRONTAB                   => 26,
	wxSTC_LEX_BULLANT                     => 27,
	wxSTC_LEX_VBSCRIPT                    => 28,
	wxSTC_LEX_BAAN                        => 31,
	wxSTC_LEX_MATLAB                      => 32,
	wxSTC_LEX_SCRIPTOL                    => 33,
	wxSTC_LEX_ASM                         => 34,
	wxSTC_LEX_CPPNOCASE                   => 35,
	wxSTC_LEX_FORTRAN                     => 36,
	wxSTC_LEX_F77                         => 37,
	wxSTC_LEX_CSS                         => 38,
	wxSTC_LEX_POV                         => 39,
	wxSTC_LEX_LOUT                        => 40,
	wxSTC_LEX_ESCRIPT                     => 41,
	wxSTC_LEX_PS                          => 42,
	wxSTC_LEX_NSIS                        => 43,
	wxSTC_LEX_MMIXAL                      => 44,
	wxSTC_LEX_CLW                         => 45,
	wxSTC_LEX_CLWNOCASE                   => 46,
	wxSTC_LEX_LOT                         => 47,
	wxSTC_LEX_YAML                        => 48,
	wxSTC_LEX_TEX                         => 49,
	wxSTC_LEX_METAPOST                    => 50,
	wxSTC_LEX_POWERBASIC                  => 51,
	wxSTC_LEX_FORTH                       => 52,
	wxSTC_LEX_ERLANG                      => 53,
	wxSTC_LEX_OCTAVE                      => 54,
	wxSTC_LEX_MSSQL                       => 55,
	wxSTC_LEX_VERILOG                     => 56,
	wxSTC_LEX_KIX                         => 57,
	wxSTC_LEX_GUI4CLI                     => 58,
	wxSTC_LEX_SPECMAN                     => 59,
	wxSTC_LEX_AU3                         => 60,
	wxSTC_LEX_APDL                        => 61,
	wxSTC_LEX_BASH                        => 62,
	wxSTC_LEX_ASN1                        => 63,
	wxSTC_LEX_VHDL                        => 64,
	wxSTC_LEX_CAML                        => 65,
	wxSTC_LEX_BLITZBASIC                  => 66,
	wxSTC_LEX_PUREBASIC                   => 67,
	wxSTC_LEX_HASKELL                     => 68,
	wxSTC_LEX_PHPSCRIPT                   => 69,
	wxSTC_LEX_TADS3                       => 70,
	wxSTC_LEX_REBOL                       => 71,
	wxSTC_LEX_SMALLTALK                   => 72,
	wxSTC_LEX_FLAGSHIP                    => 73,
	wxSTC_LEX_CSOUND                      => 74,
	wxSTC_LEX_FREEBASIC                   => 75,
	wxSTC_LEX_INNOSETUP                   => 76,
	wxSTC_LEX_OPAL                        => 77,
	wxSTC_LEX_SPICE                       => 78,
	wxSTC_LEX_D                           => 79,
	wxSTC_LEX_CMAKE                       => 80,
	wxSTC_LEX_GAP                         => 81,
	wxSTC_LEX_PLM                         => 82,
	wxSTC_LEX_PROGRESS                    => 83,
	wxSTC_LEX_ABAQUS                      => 84,
	wxSTC_LEX_ASYMPTOTE                   => 85,
	wxSTC_LEX_R                           => 86,
	wxSTC_LEX_MAGIK                       => 87,
	wxSTC_LEX_POWERSHELL                  => 88,
	wxSTC_LEX_MYSQL                       => 89,
	wxSTC_LEX_PO                          => 90,
	wxSTC_LEX_TAL                         => 91,
	wxSTC_LEX_COBOL                       => 92,
	wxSTC_LEX_TACL                        => 93,
	wxSTC_LEX_SORCUS                      => 94,
	wxSTC_LEX_POWERPRO                    => 95,
	wxSTC_LEX_NIMROD                      => 96,
	wxSTC_LEX_SML                         => 97,
	wxSTC_LEX_MARKDOWN                    => 98,
	wxSTC_LEX_AUTOMATIC                   => 1000,
	wxSTC_P_DEFAULT                       => 0,
	wxSTC_P_COMMENTLINE                   => 1,
	wxSTC_P_NUMBER                        => 2,
	wxSTC_P_STRING                        => 3,
	wxSTC_P_CHARACTER                     => 4,
	wxSTC_P_WORD                          => 5,
	wxSTC_P_TRIPLE                        => 6,
	wxSTC_P_TRIPLEDOUBLE                  => 7,
	wxSTC_P_CLASSNAME                     => 8,
	wxSTC_P_DEFNAME                       => 9,
	wxSTC_P_OPERATOR                      => 10,
	wxSTC_P_IDENTIFIER                    => 11,
	wxSTC_P_COMMENTBLOCK                  => 12,
	wxSTC_P_STRINGEOL                     => 13,
	wxSTC_P_WORD2                         => 14,
	wxSTC_P_DECORATOR                     => 15,
	wxSTC_C_DEFAULT                       => 0,
	wxSTC_C_COMMENT                       => 1,
	wxSTC_C_COMMENTLINE                   => 2,
	wxSTC_C_COMMENTDOC                    => 3,
	wxSTC_C_NUMBER                        => 4,
	wxSTC_C_WORD                          => 5,
	wxSTC_C_STRING                        => 6,
	wxSTC_C_CHARACTER                     => 7,
	wxSTC_C_UUID                          => 8,
	wxSTC_C_PREPROCESSOR                  => 9,
	wxSTC_C_OPERATOR                      => 10,
	wxSTC_C_IDENTIFIER                    => 11,
	wxSTC_C_STRINGEOL                     => 12,
	wxSTC_C_VERBATIM                      => 13,
	wxSTC_C_REGEX                         => 14,
	wxSTC_C_COMMENTLINEDOC                => 15,
	wxSTC_C_WORD2                         => 16,
	wxSTC_C_COMMENTDOCKEYWORD             => 17,
	wxSTC_C_COMMENTDOCKEYWORDERROR        => 18,
	wxSTC_C_GLOBALCLASS                   => 19,
	wxSTC_D_DEFAULT                       => 0,
	wxSTC_D_COMMENT                       => 1,
	wxSTC_D_COMMENTLINE                   => 2,
	wxSTC_D_COMMENTDOC                    => 3,
	wxSTC_D_COMMENTNESTED                 => 4,
	wxSTC_D_NUMBER                        => 5,
	wxSTC_D_WORD                          => 6,
	wxSTC_D_WORD2                         => 7,
	wxSTC_D_WORD3                         => 8,
	wxSTC_D_TYPEDEF                       => 9,
	wxSTC_D_STRING                        => 10,
	wxSTC_D_STRINGEOL                     => 11,
	wxSTC_D_CHARACTER                     => 12,
	wxSTC_D_OPERATOR                      => 13,
	wxSTC_D_IDENTIFIER                    => 14,
	wxSTC_D_COMMENTLINEDOC                => 15,
	wxSTC_D_COMMENTDOCKEYWORD             => 16,
	wxSTC_D_COMMENTDOCKEYWORDERROR        => 17,
	wxSTC_D_STRINGB                       => 18,
	wxSTC_D_STRINGR                       => 19,
	wxSTC_D_WORD5                         => 20,
	wxSTC_D_WORD6                         => 21,
	wxSTC_D_WORD7                         => 22,
	wxSTC_TCL_DEFAULT                     => 0,
	wxSTC_TCL_COMMENT                     => 1,
	wxSTC_TCL_COMMENTLINE                 => 2,
	wxSTC_TCL_NUMBER                      => 3,
	wxSTC_TCL_WORD_IN_QUOTE               => 4,
	wxSTC_TCL_IN_QUOTE                    => 5,
	wxSTC_TCL_OPERATOR                    => 6,
	wxSTC_TCL_IDENTIFIER                  => 7,
	wxSTC_TCL_SUBSTITUTION                => 8,
	wxSTC_TCL_SUB_BRACE                   => 9,
	wxSTC_TCL_MODIFIER                    => 10,
	wxSTC_TCL_EXPAND                      => 11,
	wxSTC_TCL_WORD                        => 12,
	wxSTC_TCL_WORD2                       => 13,
	wxSTC_TCL_WORD3                       => 14,
	wxSTC_TCL_WORD4                       => 15,
	wxSTC_TCL_WORD5                       => 16,
	wxSTC_TCL_WORD6                       => 17,
	wxSTC_TCL_WORD7                       => 18,
	wxSTC_TCL_WORD8                       => 19,
	wxSTC_TCL_COMMENT_BOX                 => 20,
	wxSTC_TCL_BLOCK_COMMENT               => 21,
	wxSTC_H_DEFAULT                       => 0,
	wxSTC_H_TAG                           => 1,
	wxSTC_H_TAGUNKNOWN                    => 2,
	wxSTC_H_ATTRIBUTE                     => 3,
	wxSTC_H_ATTRIBUTEUNKNOWN              => 4,
	wxSTC_H_NUMBER                        => 5,
	wxSTC_H_DOUBLESTRING                  => 6,
	wxSTC_H_SINGLESTRING                  => 7,
	wxSTC_H_OTHER                         => 8,
	wxSTC_H_COMMENT                       => 9,
	wxSTC_H_ENTITY                        => 10,
	wxSTC_H_TAGEND                        => 11,
	wxSTC_H_XMLSTART                      => 12,
	wxSTC_H_XMLEND                        => 13,
	wxSTC_H_SCRIPT                        => 14,
	wxSTC_H_ASP                           => 15,
	wxSTC_H_ASPAT                         => 16,
	wxSTC_H_CDATA                         => 17,
	wxSTC_H_QUESTION                      => 18,
	wxSTC_H_VALUE                         => 19,
	wxSTC_H_XCCOMMENT                     => 20,
	wxSTC_H_SGML_DEFAULT                  => 21,
	wxSTC_H_SGML_COMMAND                  => 22,
	wxSTC_H_SGML_1ST_PARAM                => 23,
	wxSTC_H_SGML_DOUBLESTRING             => 24,
	wxSTC_H_SGML_SIMPLESTRING             => 25,
	wxSTC_H_SGML_ERROR                    => 26,
	wxSTC_H_SGML_SPECIAL                  => 27,
	wxSTC_H_SGML_ENTITY                   => 28,
	wxSTC_H_SGML_COMMENT                  => 29,
	wxSTC_H_SGML_1ST_PARAM_COMMENT        => 30,
	wxSTC_H_SGML_BLOCK_DEFAULT            => 31,
	wxSTC_HJ_START                        => 40,
	wxSTC_HJ_DEFAULT                      => 41,
	wxSTC_HJ_COMMENT                      => 42,
	wxSTC_HJ_COMMENTLINE                  => 43,
	wxSTC_HJ_COMMENTDOC                   => 44,
	wxSTC_HJ_NUMBER                       => 45,
	wxSTC_HJ_WORD                         => 46,
	wxSTC_HJ_KEYWORD                      => 47,
	wxSTC_HJ_DOUBLESTRING                 => 48,
	wxSTC_HJ_SINGLESTRING                 => 49,
	wxSTC_HJ_SYMBOLS                      => 50,
	wxSTC_HJ_STRINGEOL                    => 51,
	wxSTC_HJ_REGEX                        => 52,
	wxSTC_HJA_START                       => 55,
	wxSTC_HJA_DEFAULT                     => 56,
	wxSTC_HJA_COMMENT                     => 57,
	wxSTC_HJA_COMMENTLINE                 => 58,
	wxSTC_HJA_COMMENTDOC                  => 59,
	wxSTC_HJA_NUMBER                      => 60,
	wxSTC_HJA_WORD                        => 61,
	wxSTC_HJA_KEYWORD                     => 62,
	wxSTC_HJA_DOUBLESTRING                => 63,
	wxSTC_HJA_SINGLESTRING                => 64,
	wxSTC_HJA_SYMBOLS                     => 65,
	wxSTC_HJA_STRINGEOL                   => 66,
	wxSTC_HJA_REGEX                       => 67,
	wxSTC_HB_START                        => 70,
	wxSTC_HB_DEFAULT                      => 71,
	wxSTC_HB_COMMENTLINE                  => 72,
	wxSTC_HB_NUMBER                       => 73,
	wxSTC_HB_WORD                         => 74,
	wxSTC_HB_STRING                       => 75,
	wxSTC_HB_IDENTIFIER                   => 76,
	wxSTC_HB_STRINGEOL                    => 77,
	wxSTC_HBA_START                       => 80,
	wxSTC_HBA_DEFAULT                     => 81,
	wxSTC_HBA_COMMENTLINE                 => 82,
	wxSTC_HBA_NUMBER                      => 83,
	wxSTC_HBA_WORD                        => 84,
	wxSTC_HBA_STRING                      => 85,
	wxSTC_HBA_IDENTIFIER                  => 86,
	wxSTC_HBA_STRINGEOL                   => 87,
	wxSTC_HP_START                        => 90,
	wxSTC_HP_DEFAULT                      => 91,
	wxSTC_HP_COMMENTLINE                  => 92,
	wxSTC_HP_NUMBER                       => 93,
	wxSTC_HP_STRING                       => 94,
	wxSTC_HP_CHARACTER                    => 95,
	wxSTC_HP_WORD                         => 96,
	wxSTC_HP_TRIPLE                       => 97,
	wxSTC_HP_TRIPLEDOUBLE                 => 98,
	wxSTC_HP_CLASSNAME                    => 99,
	wxSTC_HP_DEFNAME                      => 100,
	wxSTC_HP_OPERATOR                     => 101,
	wxSTC_HP_IDENTIFIER                   => 102,
	wxSTC_HPHP_COMPLEX_VARIABLE           => 104,
	wxSTC_HPA_START                       => 105,
	wxSTC_HPA_DEFAULT                     => 106,
	wxSTC_HPA_COMMENTLINE                 => 107,
	wxSTC_HPA_NUMBER                      => 108,
	wxSTC_HPA_STRING                      => 109,
	wxSTC_HPA_CHARACTER                   => 110,
	wxSTC_HPA_WORD                        => 111,
	wxSTC_HPA_TRIPLE                      => 112,
	wxSTC_HPA_TRIPLEDOUBLE                => 113,
	wxSTC_HPA_CLASSNAME                   => 114,
	wxSTC_HPA_DEFNAME                     => 115,
	wxSTC_HPA_OPERATOR                    => 116,
	wxSTC_HPA_IDENTIFIER                  => 117,
	wxSTC_HPHP_DEFAULT                    => 118,
	wxSTC_HPHP_HSTRING                    => 119,
	wxSTC_HPHP_SIMPLESTRING               => 120,
	wxSTC_HPHP_WORD                       => 121,
	wxSTC_HPHP_NUMBER                     => 122,
	wxSTC_HPHP_VARIABLE                   => 123,
	wxSTC_HPHP_COMMENT                    => 124,
	wxSTC_HPHP_COMMENTLINE                => 125,
	wxSTC_HPHP_HSTRING_VARIABLE           => 126,
	wxSTC_HPHP_OPERATOR                   => 127,
	wxSTC_PL_DEFAULT                      => 0,
	wxSTC_PL_ERROR                        => 1,
	wxSTC_PL_COMMENTLINE                  => 2,
	wxSTC_PL_POD                          => 3,
	wxSTC_PL_NUMBER                       => 4,
	wxSTC_PL_WORD                         => 5,
	wxSTC_PL_STRING                       => 6,
	wxSTC_PL_CHARACTER                    => 7,
	wxSTC_PL_PUNCTUATION                  => 8,
	wxSTC_PL_PREPROCESSOR                 => 9,
	wxSTC_PL_OPERATOR                     => 10,
	wxSTC_PL_IDENTIFIER                   => 11,
	wxSTC_PL_SCALAR                       => 12,
	wxSTC_PL_ARRAY                        => 13,
	wxSTC_PL_HASH                         => 14,
	wxSTC_PL_SYMBOLTABLE                  => 15,
	wxSTC_PL_VARIABLE_INDEXER             => 16,
	wxSTC_PL_REGEX                        => 17,
	wxSTC_PL_REGSUBST                     => 18,
	wxSTC_PL_LONGQUOTE                    => 19,
	wxSTC_PL_BACKTICKS                    => 20,
	wxSTC_PL_DATASECTION                  => 21,
	wxSTC_PL_HERE_DELIM                   => 22,
	wxSTC_PL_HERE_Q                       => 23,
	wxSTC_PL_HERE_QQ                      => 24,
	wxSTC_PL_HERE_QX                      => 25,
	wxSTC_PL_STRING_Q                     => 26,
	wxSTC_PL_STRING_QQ                    => 27,
	wxSTC_PL_STRING_QX                    => 28,
	wxSTC_PL_STRING_QR                    => 29,
	wxSTC_PL_STRING_QW                    => 30,
	wxSTC_PL_POD_VERB                     => 31,
	wxSTC_PL_SUB_PROTOTYPE                => 40,
	wxSTC_PL_FORMAT_IDENT                 => 41,
	wxSTC_PL_FORMAT                       => 42,
	wxSTC_PL_STRING_VAR                   => 43,
	wxSTC_PL_XLAT                         => 44,
	wxSTC_PL_REGEX_VAR                    => 54,
	wxSTC_PL_REGSUBST_VAR                 => 55,
	wxSTC_PL_BACKTICKS_VAR                => 57,
	wxSTC_PL_HERE_QQ_VAR                  => 61,
	wxSTC_PL_HERE_QX_VAR                  => 62,
	wxSTC_PL_STRING_QQ_VAR                => 64,
	wxSTC_PL_STRING_QX_VAR                => 65,
	wxSTC_PL_STRING_QR_VAR                => 66,
	wxSTC_RB_DEFAULT                      => 0,
	wxSTC_RB_ERROR                        => 1,
	wxSTC_RB_COMMENTLINE                  => 2,
	wxSTC_RB_POD                          => 3,
	wxSTC_RB_NUMBER                       => 4,
	wxSTC_RB_WORD                         => 5,
	wxSTC_RB_STRING                       => 6,
	wxSTC_RB_CHARACTER                    => 7,
	wxSTC_RB_CLASSNAME                    => 8,
	wxSTC_RB_DEFNAME                      => 9,
	wxSTC_RB_OPERATOR                     => 10,
	wxSTC_RB_IDENTIFIER                   => 11,
	wxSTC_RB_REGEX                        => 12,
	wxSTC_RB_GLOBAL                       => 13,
	wxSTC_RB_SYMBOL                       => 14,
	wxSTC_RB_MODULE_NAME                  => 15,
	wxSTC_RB_INSTANCE_VAR                 => 16,
	wxSTC_RB_CLASS_VAR                    => 17,
	wxSTC_RB_BACKTICKS                    => 18,
	wxSTC_RB_DATASECTION                  => 19,
	wxSTC_RB_HERE_DELIM                   => 20,
	wxSTC_RB_HERE_Q                       => 21,
	wxSTC_RB_HERE_QQ                      => 22,
	wxSTC_RB_HERE_QX                      => 23,
	wxSTC_RB_STRING_Q                     => 24,
	wxSTC_RB_STRING_QQ                    => 25,
	wxSTC_RB_STRING_QX                    => 26,
	wxSTC_RB_STRING_QR                    => 27,
	wxSTC_RB_STRING_QW                    => 28,
	wxSTC_RB_WORD_DEMOTED                 => 29,
	wxSTC_RB_STDIN                        => 30,
	wxSTC_RB_STDOUT                       => 31,
	wxSTC_RB_STDERR                       => 40,
	wxSTC_RB_UPPER_BOUND                  => 41,
	wxSTC_B_DEFAULT                       => 0,
	wxSTC_B_COMMENT                       => 1,
	wxSTC_B_NUMBER                        => 2,
	wxSTC_B_KEYWORD                       => 3,
	wxSTC_B_STRING                        => 4,
	wxSTC_B_PREPROCESSOR                  => 5,
	wxSTC_B_OPERATOR                      => 6,
	wxSTC_B_IDENTIFIER                    => 7,
	wxSTC_B_DATE                          => 8,
	wxSTC_B_STRINGEOL                     => 9,
	wxSTC_B_KEYWORD2                      => 10,
	wxSTC_B_KEYWORD3                      => 11,
	wxSTC_B_KEYWORD4                      => 12,
	wxSTC_B_CONSTANT                      => 13,
	wxSTC_B_ASM                           => 14,
	wxSTC_B_LABEL                         => 15,
	wxSTC_B_ERROR                         => 16,
	wxSTC_B_HEXNUMBER                     => 17,
	wxSTC_B_BINNUMBER                     => 18,
	wxSTC_PROPS_DEFAULT                   => 0,
	wxSTC_PROPS_COMMENT                   => 1,
	wxSTC_PROPS_SECTION                   => 2,
	wxSTC_PROPS_ASSIGNMENT                => 3,
	wxSTC_PROPS_DEFVAL                    => 4,
	wxSTC_PROPS_KEY                       => 5,
	wxSTC_L_DEFAULT                       => 0,
	wxSTC_L_COMMAND                       => 1,
	wxSTC_L_TAG                           => 2,
	wxSTC_L_MATH                          => 3,
	wxSTC_L_COMMENT                       => 4,
	wxSTC_LUA_DEFAULT                     => 0,
	wxSTC_LUA_COMMENT                     => 1,
	wxSTC_LUA_COMMENTLINE                 => 2,
	wxSTC_LUA_COMMENTDOC                  => 3,
	wxSTC_LUA_NUMBER                      => 4,
	wxSTC_LUA_WORD                        => 5,
	wxSTC_LUA_STRING                      => 6,
	wxSTC_LUA_CHARACTER                   => 7,
	wxSTC_LUA_LITERALSTRING               => 8,
	wxSTC_LUA_PREPROCESSOR                => 9,
	wxSTC_LUA_OPERATOR                    => 10,
	wxSTC_LUA_IDENTIFIER                  => 11,
	wxSTC_LUA_STRINGEOL                   => 12,
	wxSTC_LUA_WORD2                       => 13,
	wxSTC_LUA_WORD3                       => 14,
	wxSTC_LUA_WORD4                       => 15,
	wxSTC_LUA_WORD5                       => 16,
	wxSTC_LUA_WORD6                       => 17,
	wxSTC_LUA_WORD7                       => 18,
	wxSTC_LUA_WORD8                       => 19,
	wxSTC_ERR_DEFAULT                     => 0,
	wxSTC_ERR_PYTHON                      => 1,
	wxSTC_ERR_GCC                         => 2,
	wxSTC_ERR_MS                          => 3,
	wxSTC_ERR_CMD                         => 4,
	wxSTC_ERR_BORLAND                     => 5,
	wxSTC_ERR_PERL                        => 6,
	wxSTC_ERR_NET                         => 7,
	wxSTC_ERR_LUA                         => 8,
	wxSTC_ERR_CTAG                        => 9,
	wxSTC_ERR_DIFF_CHANGED                => 10,
	wxSTC_ERR_DIFF_ADDITION               => 11,
	wxSTC_ERR_DIFF_DELETION               => 12,
	wxSTC_ERR_DIFF_MESSAGE                => 13,
	wxSTC_ERR_PHP                         => 14,
	wxSTC_ERR_ELF                         => 15,
	wxSTC_ERR_IFC                         => 16,
	wxSTC_ERR_IFORT                       => 17,
	wxSTC_ERR_ABSF                        => 18,
	wxSTC_ERR_TIDY                        => 19,
	wxSTC_ERR_JAVA_STACK                  => 20,
	wxSTC_ERR_VALUE                       => 21,
	wxSTC_BAT_DEFAULT                     => 0,
	wxSTC_BAT_COMMENT                     => 1,
	wxSTC_BAT_WORD                        => 2,
	wxSTC_BAT_LABEL                       => 3,
	wxSTC_BAT_HIDE                        => 4,
	wxSTC_BAT_COMMAND                     => 5,
	wxSTC_BAT_IDENTIFIER                  => 6,
	wxSTC_BAT_OPERATOR                    => 7,
	wxSTC_MAKE_DEFAULT                    => 0,
	wxSTC_MAKE_COMMENT                    => 1,
	wxSTC_MAKE_PREPROCESSOR               => 2,
	wxSTC_MAKE_IDENTIFIER                 => 3,
	wxSTC_MAKE_OPERATOR                   => 4,
	wxSTC_MAKE_TARGET                     => 5,
	wxSTC_MAKE_IDEOL                      => 9,
	wxSTC_DIFF_DEFAULT                    => 0,
	wxSTC_DIFF_COMMENT                    => 1,
	wxSTC_DIFF_COMMAND                    => 2,
	wxSTC_DIFF_HEADER                     => 3,
	wxSTC_DIFF_POSITION                   => 4,
	wxSTC_DIFF_DELETED                    => 5,
	wxSTC_DIFF_ADDED                      => 6,
	wxSTC_DIFF_CHANGED                    => 7,
	wxSTC_CONF_DEFAULT                    => 0,
	wxSTC_CONF_COMMENT                    => 1,
	wxSTC_CONF_NUMBER                     => 2,
	wxSTC_CONF_IDENTIFIER                 => 3,
	wxSTC_CONF_EXTENSION                  => 4,
	wxSTC_CONF_PARAMETER                  => 5,
	wxSTC_CONF_STRING                     => 6,
	wxSTC_CONF_OPERATOR                   => 7,
	wxSTC_CONF_IP                         => 8,
	wxSTC_CONF_DIRECTIVE                  => 9,
	wxSTC_AVE_DEFAULT                     => 0,
	wxSTC_AVE_COMMENT                     => 1,
	wxSTC_AVE_NUMBER                      => 2,
	wxSTC_AVE_WORD                        => 3,
	wxSTC_AVE_STRING                      => 6,
	wxSTC_AVE_ENUM                        => 7,
	wxSTC_AVE_STRINGEOL                   => 8,
	wxSTC_AVE_IDENTIFIER                  => 9,
	wxSTC_AVE_OPERATOR                    => 10,
	wxSTC_AVE_WORD1                       => 11,
	wxSTC_AVE_WORD2                       => 12,
	wxSTC_AVE_WORD3                       => 13,
	wxSTC_AVE_WORD4                       => 14,
	wxSTC_AVE_WORD5                       => 15,
	wxSTC_AVE_WORD6                       => 16,
	wxSTC_ADA_DEFAULT                     => 0,
	wxSTC_ADA_WORD                        => 1,
	wxSTC_ADA_IDENTIFIER                  => 2,
	wxSTC_ADA_NUMBER                      => 3,
	wxSTC_ADA_DELIMITER                   => 4,
	wxSTC_ADA_CHARACTER                   => 5,
	wxSTC_ADA_CHARACTEREOL                => 6,
	wxSTC_ADA_STRING                      => 7,
	wxSTC_ADA_STRINGEOL                   => 8,
	wxSTC_ADA_LABEL                       => 9,
	wxSTC_ADA_COMMENTLINE                 => 10,
	wxSTC_ADA_ILLEGAL                     => 11,
	wxSTC_BAAN_DEFAULT                    => 0,
	wxSTC_BAAN_COMMENT                    => 1,
	wxSTC_BAAN_COMMENTDOC                 => 2,
	wxSTC_BAAN_NUMBER                     => 3,
	wxSTC_BAAN_WORD                       => 4,
	wxSTC_BAAN_STRING                     => 5,
	wxSTC_BAAN_PREPROCESSOR               => 6,
	wxSTC_BAAN_OPERATOR                   => 7,
	wxSTC_BAAN_IDENTIFIER                 => 8,
	wxSTC_BAAN_STRINGEOL                  => 9,
	wxSTC_BAAN_WORD2                      => 10,
	wxSTC_LISP_DEFAULT                    => 0,
	wxSTC_LISP_COMMENT                    => 1,
	wxSTC_LISP_NUMBER                     => 2,
	wxSTC_LISP_KEYWORD                    => 3,
	wxSTC_LISP_KEYWORD_KW                 => 4,
	wxSTC_LISP_SYMBOL                     => 5,
	wxSTC_LISP_STRING                     => 6,
	wxSTC_LISP_STRINGEOL                  => 8,
	wxSTC_LISP_IDENTIFIER                 => 9,
	wxSTC_LISP_OPERATOR                   => 10,
	wxSTC_LISP_SPECIAL                    => 11,
	wxSTC_LISP_MULTI_COMMENT              => 12,
	wxSTC_EIFFEL_DEFAULT                  => 0,
	wxSTC_EIFFEL_COMMENTLINE              => 1,
	wxSTC_EIFFEL_NUMBER                   => 2,
	wxSTC_EIFFEL_WORD                     => 3,
	wxSTC_EIFFEL_STRING                   => 4,
	wxSTC_EIFFEL_CHARACTER                => 5,
	wxSTC_EIFFEL_OPERATOR                 => 6,
	wxSTC_EIFFEL_IDENTIFIER               => 7,
	wxSTC_EIFFEL_STRINGEOL                => 8,
	wxSTC_NNCRONTAB_DEFAULT               => 0,
	wxSTC_NNCRONTAB_COMMENT               => 1,
	wxSTC_NNCRONTAB_TASK                  => 2,
	wxSTC_NNCRONTAB_SECTION               => 3,
	wxSTC_NNCRONTAB_KEYWORD               => 4,
	wxSTC_NNCRONTAB_MODIFIER              => 5,
	wxSTC_NNCRONTAB_ASTERISK              => 6,
	wxSTC_NNCRONTAB_NUMBER                => 7,
	wxSTC_NNCRONTAB_STRING                => 8,
	wxSTC_NNCRONTAB_ENVIRONMENT           => 9,
	wxSTC_NNCRONTAB_IDENTIFIER            => 10,
	wxSTC_FORTH_DEFAULT                   => 0,
	wxSTC_FORTH_COMMENT                   => 1,
	wxSTC_FORTH_COMMENT_ML                => 2,
	wxSTC_FORTH_IDENTIFIER                => 3,
	wxSTC_FORTH_CONTROL                   => 4,
	wxSTC_FORTH_KEYWORD                   => 5,
	wxSTC_FORTH_DEFWORD                   => 6,
	wxSTC_FORTH_PREWORD1                  => 7,
	wxSTC_FORTH_PREWORD2                  => 8,
	wxSTC_FORTH_NUMBER                    => 9,
	wxSTC_FORTH_STRING                    => 10,
	wxSTC_FORTH_LOCALE                    => 11,
	wxSTC_MATLAB_DEFAULT                  => 0,
	wxSTC_MATLAB_COMMENT                  => 1,
	wxSTC_MATLAB_COMMAND                  => 2,
	wxSTC_MATLAB_NUMBER                   => 3,
	wxSTC_MATLAB_KEYWORD                  => 4,
	wxSTC_MATLAB_STRING                   => 5,
	wxSTC_MATLAB_OPERATOR                 => 6,
	wxSTC_MATLAB_IDENTIFIER               => 7,
	wxSTC_MATLAB_DOUBLEQUOTESTRING        => 8,
	wxSTC_SCRIPTOL_DEFAULT                => 0,
	wxSTC_SCRIPTOL_WHITE                  => 1,
	wxSTC_SCRIPTOL_COMMENTLINE            => 2,
	wxSTC_SCRIPTOL_PERSISTENT             => 3,
	wxSTC_SCRIPTOL_CSTYLE                 => 4,
	wxSTC_SCRIPTOL_COMMENTBLOCK           => 5,
	wxSTC_SCRIPTOL_NUMBER                 => 6,
	wxSTC_SCRIPTOL_STRING                 => 7,
	wxSTC_SCRIPTOL_CHARACTER              => 8,
	wxSTC_SCRIPTOL_STRINGEOL              => 9,
	wxSTC_SCRIPTOL_KEYWORD                => 10,
	wxSTC_SCRIPTOL_OPERATOR               => 11,
	wxSTC_SCRIPTOL_IDENTIFIER             => 12,
	wxSTC_SCRIPTOL_TRIPLE                 => 13,
	wxSTC_SCRIPTOL_CLASSNAME              => 14,
	wxSTC_SCRIPTOL_PREPROCESSOR           => 15,
	wxSTC_ASM_DEFAULT                     => 0,
	wxSTC_ASM_COMMENT                     => 1,
	wxSTC_ASM_NUMBER                      => 2,
	wxSTC_ASM_STRING                      => 3,
	wxSTC_ASM_OPERATOR                    => 4,
	wxSTC_ASM_IDENTIFIER                  => 5,
	wxSTC_ASM_CPUINSTRUCTION              => 6,
	wxSTC_ASM_MATHINSTRUCTION             => 7,
	wxSTC_ASM_REGISTER                    => 8,
	wxSTC_ASM_DIRECTIVE                   => 9,
	wxSTC_ASM_DIRECTIVEOPERAND            => 10,
	wxSTC_ASM_COMMENTBLOCK                => 11,
	wxSTC_ASM_CHARACTER                   => 12,
	wxSTC_ASM_STRINGEOL                   => 13,
	wxSTC_ASM_EXTINSTRUCTION              => 14,
	wxSTC_F_DEFAULT                       => 0,
	wxSTC_F_COMMENT                       => 1,
	wxSTC_F_NUMBER                        => 2,
	wxSTC_F_STRING1                       => 3,
	wxSTC_F_STRING2                       => 4,
	wxSTC_F_STRINGEOL                     => 5,
	wxSTC_F_OPERATOR                      => 6,
	wxSTC_F_IDENTIFIER                    => 7,
	wxSTC_F_WORD                          => 8,
	wxSTC_F_WORD2                         => 9,
	wxSTC_F_WORD3                         => 10,
	wxSTC_F_PREPROCESSOR                  => 11,
	wxSTC_F_OPERATOR2                     => 12,
	wxSTC_F_LABEL                         => 13,
	wxSTC_F_CONTINUATION                  => 14,
	wxSTC_CSS_DEFAULT                     => 0,
	wxSTC_CSS_TAG                         => 1,
	wxSTC_CSS_CLASS                       => 2,
	wxSTC_CSS_PSEUDOCLASS                 => 3,
	wxSTC_CSS_UNKNOWN_PSEUDOCLASS         => 4,
	wxSTC_CSS_OPERATOR                    => 5,
	wxSTC_CSS_IDENTIFIER                  => 6,
	wxSTC_CSS_UNKNOWN_IDENTIFIER          => 7,
	wxSTC_CSS_VALUE                       => 8,
	wxSTC_CSS_COMMENT                     => 9,
	wxSTC_CSS_ID                          => 10,
	wxSTC_CSS_IMPORTANT                   => 11,
	wxSTC_CSS_DIRECTIVE                   => 12,
	wxSTC_CSS_DOUBLESTRING                => 13,
	wxSTC_CSS_SINGLESTRING                => 14,
	wxSTC_CSS_IDENTIFIER2                 => 15,
	wxSTC_CSS_ATTRIBUTE                   => 16,
	wxSTC_CSS_IDENTIFIER3                 => 17,
	wxSTC_CSS_PSEUDOELEMENT               => 18,
	wxSTC_CSS_EXTENDED_IDENTIFIER         => 19,
	wxSTC_CSS_EXTENDED_PSEUDOCLASS        => 20,
	wxSTC_CSS_EXTENDED_PSEUDOELEMENT      => 21,
	wxSTC_POV_DEFAULT                     => 0,
	wxSTC_POV_COMMENT                     => 1,
	wxSTC_POV_COMMENTLINE                 => 2,
	wxSTC_POV_NUMBER                      => 3,
	wxSTC_POV_OPERATOR                    => 4,
	wxSTC_POV_IDENTIFIER                  => 5,
	wxSTC_POV_STRING                      => 6,
	wxSTC_POV_STRINGEOL                   => 7,
	wxSTC_POV_DIRECTIVE                   => 8,
	wxSTC_POV_BADDIRECTIVE                => 9,
	wxSTC_POV_WORD2                       => 10,
	wxSTC_POV_WORD3                       => 11,
	wxSTC_POV_WORD4                       => 12,
	wxSTC_POV_WORD5                       => 13,
	wxSTC_POV_WORD6                       => 14,
	wxSTC_POV_WORD7                       => 15,
	wxSTC_POV_WORD8                       => 16,
	wxSTC_LOUT_DEFAULT                    => 0,
	wxSTC_LOUT_COMMENT                    => 1,
	wxSTC_LOUT_NUMBER                     => 2,
	wxSTC_LOUT_WORD                       => 3,
	wxSTC_LOUT_WORD2                      => 4,
	wxSTC_LOUT_WORD3                      => 5,
	wxSTC_LOUT_WORD4                      => 6,
	wxSTC_LOUT_STRING                     => 7,
	wxSTC_LOUT_OPERATOR                   => 8,
	wxSTC_LOUT_IDENTIFIER                 => 9,
	wxSTC_LOUT_STRINGEOL                  => 10,
	wxSTC_ESCRIPT_DEFAULT                 => 0,
	wxSTC_ESCRIPT_COMMENT                 => 1,
	wxSTC_ESCRIPT_COMMENTLINE             => 2,
	wxSTC_ESCRIPT_COMMENTDOC              => 3,
	wxSTC_ESCRIPT_NUMBER                  => 4,
	wxSTC_ESCRIPT_WORD                    => 5,
	wxSTC_ESCRIPT_STRING                  => 6,
	wxSTC_ESCRIPT_OPERATOR                => 7,
	wxSTC_ESCRIPT_IDENTIFIER              => 8,
	wxSTC_ESCRIPT_BRACE                   => 9,
	wxSTC_ESCRIPT_WORD2                   => 10,
	wxSTC_ESCRIPT_WORD3                   => 11,
	wxSTC_PS_DEFAULT                      => 0,
	wxSTC_PS_COMMENT                      => 1,
	wxSTC_PS_DSC_COMMENT                  => 2,
	wxSTC_PS_DSC_VALUE                    => 3,
	wxSTC_PS_NUMBER                       => 4,
	wxSTC_PS_NAME                         => 5,
	wxSTC_PS_KEYWORD                      => 6,
	wxSTC_PS_LITERAL                      => 7,
	wxSTC_PS_IMMEVAL                      => 8,
	wxSTC_PS_PAREN_ARRAY                  => 9,
	wxSTC_PS_PAREN_DICT                   => 10,
	wxSTC_PS_PAREN_PROC                   => 11,
	wxSTC_PS_TEXT                         => 12,
	wxSTC_PS_HEXSTRING                    => 13,
	wxSTC_PS_BASE85STRING                 => 14,
	wxSTC_PS_BADSTRINGCHAR                => 15,
	wxSTC_NSIS_DEFAULT                    => 0,
	wxSTC_NSIS_COMMENT                    => 1,
	wxSTC_NSIS_STRINGDQ                   => 2,
	wxSTC_NSIS_STRINGLQ                   => 3,
	wxSTC_NSIS_STRINGRQ                   => 4,
	wxSTC_NSIS_FUNCTION                   => 5,
	wxSTC_NSIS_VARIABLE                   => 6,
	wxSTC_NSIS_LABEL                      => 7,
	wxSTC_NSIS_USERDEFINED                => 8,
	wxSTC_NSIS_SECTIONDEF                 => 9,
	wxSTC_NSIS_SUBSECTIONDEF              => 10,
	wxSTC_NSIS_IFDEFINEDEF                => 11,
	wxSTC_NSIS_MACRODEF                   => 12,
	wxSTC_NSIS_STRINGVAR                  => 13,
	wxSTC_NSIS_NUMBER                     => 14,
	wxSTC_NSIS_SECTIONGROUP               => 15,
	wxSTC_NSIS_PAGEEX                     => 16,
	wxSTC_NSIS_FUNCTIONDEF                => 17,
	wxSTC_NSIS_COMMENTBOX                 => 18,
	wxSTC_MMIXAL_LEADWS                   => 0,
	wxSTC_MMIXAL_COMMENT                  => 1,
	wxSTC_MMIXAL_LABEL                    => 2,
	wxSTC_MMIXAL_OPCODE                   => 3,
	wxSTC_MMIXAL_OPCODE_PRE               => 4,
	wxSTC_MMIXAL_OPCODE_VALID             => 5,
	wxSTC_MMIXAL_OPCODE_UNKNOWN           => 6,
	wxSTC_MMIXAL_OPCODE_POST              => 7,
	wxSTC_MMIXAL_OPERANDS                 => 8,
	wxSTC_MMIXAL_NUMBER                   => 9,
	wxSTC_MMIXAL_REF                      => 10,
	wxSTC_MMIXAL_CHAR                     => 11,
	wxSTC_MMIXAL_STRING                   => 12,
	wxSTC_MMIXAL_REGISTER                 => 13,
	wxSTC_MMIXAL_HEX                      => 14,
	wxSTC_MMIXAL_OPERATOR                 => 15,
	wxSTC_MMIXAL_SYMBOL                   => 16,
	wxSTC_MMIXAL_INCLUDE                  => 17,
	wxSTC_CLW_DEFAULT                     => 0,
	wxSTC_CLW_LABEL                       => 1,
	wxSTC_CLW_COMMENT                     => 2,
	wxSTC_CLW_STRING                      => 3,
	wxSTC_CLW_USER_IDENTIFIER             => 4,
	wxSTC_CLW_INTEGER_CONSTANT            => 5,
	wxSTC_CLW_REAL_CONSTANT               => 6,
	wxSTC_CLW_PICTURE_STRING              => 7,
	wxSTC_CLW_KEYWORD                     => 8,
	wxSTC_CLW_COMPILER_DIRECTIVE          => 9,
	wxSTC_CLW_RUNTIME_EXPRESSIONS         => 10,
	wxSTC_CLW_BUILTIN_PROCEDURES_FUNCTION => 11,
	wxSTC_CLW_STRUCTURE_DATA_TYPE         => 12,
	wxSTC_CLW_ATTRIBUTE                   => 13,
	wxSTC_CLW_STANDARD_EQUATE             => 14,
	wxSTC_CLW_ERROR                       => 15,
	wxSTC_CLW_DEPRECATED                  => 16,
	wxSTC_LOT_DEFAULT                     => 0,
	wxSTC_LOT_HEADER                      => 1,
	wxSTC_LOT_BREAK                       => 2,
	wxSTC_LOT_SET                         => 3,
	wxSTC_LOT_PASS                        => 4,
	wxSTC_LOT_FAIL                        => 5,
	wxSTC_LOT_ABORT                       => 6,
	wxSTC_YAML_DEFAULT                    => 0,
	wxSTC_YAML_COMMENT                    => 1,
	wxSTC_YAML_IDENTIFIER                 => 2,
	wxSTC_YAML_KEYWORD                    => 3,
	wxSTC_YAML_NUMBER                     => 4,
	wxSTC_YAML_REFERENCE                  => 5,
	wxSTC_YAML_DOCUMENT                   => 6,
	wxSTC_YAML_TEXT                       => 7,
	wxSTC_YAML_ERROR                      => 8,
	wxSTC_YAML_OPERATOR                   => 9,
	wxSTC_TEX_DEFAULT                     => 0,
	wxSTC_TEX_SPECIAL                     => 1,
	wxSTC_TEX_GROUP                       => 2,
	wxSTC_TEX_SYMBOL                      => 3,
	wxSTC_TEX_COMMAND                     => 4,
	wxSTC_TEX_TEXT                        => 5,
	wxSTC_METAPOST_DEFAULT                => 0,
	wxSTC_METAPOST_SPECIAL                => 1,
	wxSTC_METAPOST_GROUP                  => 2,
	wxSTC_METAPOST_SYMBOL                 => 3,
	wxSTC_METAPOST_COMMAND                => 4,
	wxSTC_METAPOST_TEXT                   => 5,
	wxSTC_METAPOST_EXTRA                  => 6,
	wxSTC_ERLANG_DEFAULT                  => 0,
	wxSTC_ERLANG_COMMENT                  => 1,
	wxSTC_ERLANG_VARIABLE                 => 2,
	wxSTC_ERLANG_NUMBER                   => 3,
	wxSTC_ERLANG_KEYWORD                  => 4,
	wxSTC_ERLANG_STRING                   => 5,
	wxSTC_ERLANG_OPERATOR                 => 6,
	wxSTC_ERLANG_ATOM                     => 7,
	wxSTC_ERLANG_FUNCTION_NAME            => 8,
	wxSTC_ERLANG_CHARACTER                => 9,
	wxSTC_ERLANG_MACRO                    => 10,
	wxSTC_ERLANG_RECORD                   => 11,
	wxSTC_ERLANG_PREPROC                  => 12,
	wxSTC_ERLANG_NODE_NAME                => 13,
	wxSTC_ERLANG_COMMENT_FUNCTION         => 14,
	wxSTC_ERLANG_COMMENT_MODULE           => 15,
	wxSTC_ERLANG_COMMENT_DOC              => 16,
	wxSTC_ERLANG_COMMENT_DOC_MACRO        => 17,
	wxSTC_ERLANG_ATOM_QUOTED              => 18,
	wxSTC_ERLANG_MACRO_QUOTED             => 19,
	wxSTC_ERLANG_RECORD_QUOTED            => 20,
	wxSTC_ERLANG_NODE_NAME_QUOTED         => 21,
	wxSTC_ERLANG_BIFS                     => 22,
	wxSTC_ERLANG_MODULES                  => 23,
	wxSTC_ERLANG_MODULES_ATT              => 24,
	wxSTC_ERLANG_UNKNOWN                  => 31,
	wxSTC_MSSQL_DEFAULT                   => 0,
	wxSTC_MSSQL_COMMENT                   => 1,
	wxSTC_MSSQL_LINE_COMMENT              => 2,
	wxSTC_MSSQL_NUMBER                    => 3,
	wxSTC_MSSQL_STRING                    => 4,
	wxSTC_MSSQL_OPERATOR                  => 5,
	wxSTC_MSSQL_IDENTIFIER                => 6,
	wxSTC_MSSQL_VARIABLE                  => 7,
	wxSTC_MSSQL_COLUMN_NAME               => 8,
	wxSTC_MSSQL_STATEMENT                 => 9,
	wxSTC_MSSQL_DATATYPE                  => 10,
	wxSTC_MSSQL_SYSTABLE                  => 11,
	wxSTC_MSSQL_GLOBAL_VARIABLE           => 12,
	wxSTC_MSSQL_FUNCTION                  => 13,
	wxSTC_MSSQL_STORED_PROCEDURE          => 14,
	wxSTC_MSSQL_DEFAULT_PREF_DATATYPE     => 15,
	wxSTC_MSSQL_COLUMN_NAME_2             => 16,
	wxSTC_V_DEFAULT                       => 0,
	wxSTC_V_COMMENT                       => 1,
	wxSTC_V_COMMENTLINE                   => 2,
	wxSTC_V_COMMENTLINEBANG               => 3,
	wxSTC_V_NUMBER                        => 4,
	wxSTC_V_WORD                          => 5,
	wxSTC_V_STRING                        => 6,
	wxSTC_V_WORD2                         => 7,
	wxSTC_V_WORD3                         => 8,
	wxSTC_V_PREPROCESSOR                  => 9,
	wxSTC_V_OPERATOR                      => 10,
	wxSTC_V_IDENTIFIER                    => 11,
	wxSTC_V_STRINGEOL                     => 12,
	wxSTC_V_USER                          => 19,
	wxSTC_KIX_DEFAULT                     => 0,
	wxSTC_KIX_COMMENT                     => 1,
	wxSTC_KIX_STRING1                     => 2,
	wxSTC_KIX_STRING2                     => 3,
	wxSTC_KIX_NUMBER                      => 4,
	wxSTC_KIX_VAR                         => 5,
	wxSTC_KIX_MACRO                       => 6,
	wxSTC_KIX_KEYWORD                     => 7,
	wxSTC_KIX_FUNCTIONS                   => 8,
	wxSTC_KIX_OPERATOR                    => 9,
	wxSTC_KIX_IDENTIFIER                  => 31,
	wxSTC_GC_DEFAULT                      => 0,
	wxSTC_GC_COMMENTLINE                  => 1,
	wxSTC_GC_COMMENTBLOCK                 => 2,
	wxSTC_GC_GLOBAL                       => 3,
	wxSTC_GC_EVENT                        => 4,
	wxSTC_GC_ATTRIBUTE                    => 5,
	wxSTC_GC_CONTROL                      => 6,
	wxSTC_GC_COMMAND                      => 7,
	wxSTC_GC_STRING                       => 8,
	wxSTC_GC_OPERATOR                     => 9,
	wxSTC_SN_DEFAULT                      => 0,
	wxSTC_SN_CODE                         => 1,
	wxSTC_SN_COMMENTLINE                  => 2,
	wxSTC_SN_COMMENTLINEBANG              => 3,
	wxSTC_SN_NUMBER                       => 4,
	wxSTC_SN_WORD                         => 5,
	wxSTC_SN_STRING                       => 6,
	wxSTC_SN_WORD2                        => 7,
	wxSTC_SN_WORD3                        => 8,
	wxSTC_SN_PREPROCESSOR                 => 9,
	wxSTC_SN_OPERATOR                     => 10,
	wxSTC_SN_IDENTIFIER                   => 11,
	wxSTC_SN_STRINGEOL                    => 12,
	wxSTC_SN_REGEXTAG                     => 13,
	wxSTC_SN_SIGNAL                       => 14,
	wxSTC_SN_USER                         => 19,
	wxSTC_AU3_DEFAULT                     => 0,
	wxSTC_AU3_COMMENT                     => 1,
	wxSTC_AU3_COMMENTBLOCK                => 2,
	wxSTC_AU3_NUMBER                      => 3,
	wxSTC_AU3_FUNCTION                    => 4,
	wxSTC_AU3_KEYWORD                     => 5,
	wxSTC_AU3_MACRO                       => 6,
	wxSTC_AU3_STRING                      => 7,
	wxSTC_AU3_OPERATOR                    => 8,
	wxSTC_AU3_VARIABLE                    => 9,
	wxSTC_AU3_SENT                        => 10,
	wxSTC_AU3_PREPROCESSOR                => 11,
	wxSTC_AU3_SPECIAL                     => 12,
	wxSTC_AU3_EXPAND                      => 13,
	wxSTC_AU3_COMOBJ                      => 14,
	wxSTC_AU3_UDF                         => 15,
	wxSTC_APDL_DEFAULT                    => 0,
	wxSTC_APDL_COMMENT                    => 1,
	wxSTC_APDL_COMMENTBLOCK               => 2,
	wxSTC_APDL_NUMBER                     => 3,
	wxSTC_APDL_STRING                     => 4,
	wxSTC_APDL_OPERATOR                   => 5,
	wxSTC_APDL_WORD                       => 6,
	wxSTC_APDL_PROCESSOR                  => 7,
	wxSTC_APDL_COMMAND                    => 8,
	wxSTC_APDL_SLASHCOMMAND               => 9,
	wxSTC_APDL_STARCOMMAND                => 10,
	wxSTC_APDL_ARGUMENT                   => 11,
	wxSTC_APDL_FUNCTION                   => 12,
	wxSTC_SH_DEFAULT                      => 0,
	wxSTC_SH_ERROR                        => 1,
	wxSTC_SH_COMMENTLINE                  => 2,
	wxSTC_SH_NUMBER                       => 3,
	wxSTC_SH_WORD                         => 4,
	wxSTC_SH_STRING                       => 5,
	wxSTC_SH_CHARACTER                    => 6,
	wxSTC_SH_OPERATOR                     => 7,
	wxSTC_SH_IDENTIFIER                   => 8,
	wxSTC_SH_SCALAR                       => 9,
	wxSTC_SH_PARAM                        => 10,
	wxSTC_SH_BACKTICKS                    => 11,
	wxSTC_SH_HERE_DELIM                   => 12,
	wxSTC_SH_HERE_Q                       => 13,
	wxSTC_ASN1_DEFAULT                    => 0,
	wxSTC_ASN1_COMMENT                    => 1,
	wxSTC_ASN1_IDENTIFIER                 => 2,
	wxSTC_ASN1_STRING                     => 3,
	wxSTC_ASN1_OID                        => 4,
	wxSTC_ASN1_SCALAR                     => 5,
	wxSTC_ASN1_KEYWORD                    => 6,
	wxSTC_ASN1_ATTRIBUTE                  => 7,
	wxSTC_ASN1_DESCRIPTOR                 => 8,
	wxSTC_ASN1_TYPE                       => 9,
	wxSTC_ASN1_OPERATOR                   => 10,
	wxSTC_VHDL_DEFAULT                    => 0,
	wxSTC_VHDL_COMMENT                    => 1,
	wxSTC_VHDL_COMMENTLINEBANG            => 2,
	wxSTC_VHDL_NUMBER                     => 3,
	wxSTC_VHDL_STRING                     => 4,
	wxSTC_VHDL_OPERATOR                   => 5,
	wxSTC_VHDL_IDENTIFIER                 => 6,
	wxSTC_VHDL_STRINGEOL                  => 7,
	wxSTC_VHDL_KEYWORD                    => 8,
	wxSTC_VHDL_STDOPERATOR                => 9,
	wxSTC_VHDL_ATTRIBUTE                  => 10,
	wxSTC_VHDL_STDFUNCTION                => 11,
	wxSTC_VHDL_STDPACKAGE                 => 12,
	wxSTC_VHDL_STDTYPE                    => 13,
	wxSTC_VHDL_USERWORD                   => 14,
	wxSTC_CAML_DEFAULT                    => 0,
	wxSTC_CAML_IDENTIFIER                 => 1,
	wxSTC_CAML_TAGNAME                    => 2,
	wxSTC_CAML_KEYWORD                    => 3,
	wxSTC_CAML_KEYWORD2                   => 4,
	wxSTC_CAML_KEYWORD3                   => 5,
	wxSTC_CAML_LINENUM                    => 6,
	wxSTC_CAML_OPERATOR                   => 7,
	wxSTC_CAML_NUMBER                     => 8,
	wxSTC_CAML_CHAR                       => 9,
	wxSTC_CAML_WHITE                      => 10,
	wxSTC_CAML_STRING                     => 11,
	wxSTC_CAML_COMMENT                    => 12,
	wxSTC_CAML_COMMENT1                   => 13,
	wxSTC_CAML_COMMENT2                   => 14,
	wxSTC_CAML_COMMENT3                   => 15,
	wxSTC_HA_DEFAULT                      => 0,
	wxSTC_HA_IDENTIFIER                   => 1,
	wxSTC_HA_KEYWORD                      => 2,
	wxSTC_HA_NUMBER                       => 3,
	wxSTC_HA_STRING                       => 4,
	wxSTC_HA_CHARACTER                    => 5,
	wxSTC_HA_CLASS                        => 6,
	wxSTC_HA_MODULE                       => 7,
	wxSTC_HA_CAPITAL                      => 8,
	wxSTC_HA_DATA                         => 9,
	wxSTC_HA_IMPORT                       => 10,
	wxSTC_HA_OPERATOR                     => 11,
	wxSTC_HA_INSTANCE                     => 12,
	wxSTC_HA_COMMENTLINE                  => 13,
	wxSTC_HA_COMMENTBLOCK                 => 14,
	wxSTC_HA_COMMENTBLOCK2                => 15,
	wxSTC_HA_COMMENTBLOCK3                => 16,
	wxSTC_T3_DEFAULT                      => 0,
	wxSTC_T3_X_DEFAULT                    => 1,
	wxSTC_T3_PREPROCESSOR                 => 2,
	wxSTC_T3_BLOCK_COMMENT                => 3,
	wxSTC_T3_LINE_COMMENT                 => 4,
	wxSTC_T3_OPERATOR                     => 5,
	wxSTC_T3_KEYWORD                      => 6,
	wxSTC_T3_NUMBER                       => 7,
	wxSTC_T3_IDENTIFIER                   => 8,
	wxSTC_T3_S_STRING                     => 9,
	wxSTC_T3_D_STRING                     => 10,
	wxSTC_T3_X_STRING                     => 11,
	wxSTC_T3_LIB_DIRECTIVE                => 12,
	wxSTC_T3_MSG_PARAM                    => 13,
	wxSTC_T3_HTML_TAG                     => 14,
	wxSTC_T3_HTML_DEFAULT                 => 15,
	wxSTC_T3_HTML_STRING                  => 16,
	wxSTC_T3_USER1                        => 17,
	wxSTC_T3_USER2                        => 18,
	wxSTC_T3_USER3                        => 19,
	wxSTC_T3_BRACE                        => 20,
	wxSTC_REBOL_DEFAULT                   => 0,
	wxSTC_REBOL_COMMENTLINE               => 1,
	wxSTC_REBOL_COMMENTBLOCK              => 2,
	wxSTC_REBOL_PREFACE                   => 3,
	wxSTC_REBOL_OPERATOR                  => 4,
	wxSTC_REBOL_CHARACTER                 => 5,
	wxSTC_REBOL_QUOTEDSTRING              => 6,
	wxSTC_REBOL_BRACEDSTRING              => 7,
	wxSTC_REBOL_NUMBER                    => 8,
	wxSTC_REBOL_PAIR                      => 9,
	wxSTC_REBOL_TUPLE                     => 10,
	wxSTC_REBOL_BINARY                    => 11,
	wxSTC_REBOL_MONEY                     => 12,
	wxSTC_REBOL_ISSUE                     => 13,
	wxSTC_REBOL_TAG                       => 14,
	wxSTC_REBOL_FILE                      => 15,
	wxSTC_REBOL_EMAIL                     => 16,
	wxSTC_REBOL_URL                       => 17,
	wxSTC_REBOL_DATE                      => 18,
	wxSTC_REBOL_TIME                      => 19,
	wxSTC_REBOL_IDENTIFIER                => 20,
	wxSTC_REBOL_WORD                      => 21,
	wxSTC_REBOL_WORD2                     => 22,
	wxSTC_REBOL_WORD3                     => 23,
	wxSTC_REBOL_WORD4                     => 24,
	wxSTC_REBOL_WORD5                     => 25,
	wxSTC_REBOL_WORD6                     => 26,
	wxSTC_REBOL_WORD7                     => 27,
	wxSTC_REBOL_WORD8                     => 28,
	wxSTC_SQL_DEFAULT                     => 0,
	wxSTC_SQL_COMMENT                     => 1,
	wxSTC_SQL_COMMENTLINE                 => 2,
	wxSTC_SQL_COMMENTDOC                  => 3,
	wxSTC_SQL_NUMBER                      => 4,
	wxSTC_SQL_WORD                        => 5,
	wxSTC_SQL_STRING                      => 6,
	wxSTC_SQL_CHARACTER                   => 7,
	wxSTC_SQL_SQLPLUS                     => 8,
	wxSTC_SQL_SQLPLUS_PROMPT              => 9,
	wxSTC_SQL_OPERATOR                    => 10,
	wxSTC_SQL_IDENTIFIER                  => 11,
	wxSTC_SQL_SQLPLUS_COMMENT             => 13,
	wxSTC_SQL_COMMENTLINEDOC              => 15,
	wxSTC_SQL_WORD2                       => 16,
	wxSTC_SQL_COMMENTDOCKEYWORD           => 17,
	wxSTC_SQL_COMMENTDOCKEYWORDERROR      => 18,
	wxSTC_SQL_USER1                       => 19,
	wxSTC_SQL_USER2                       => 20,
	wxSTC_SQL_USER3                       => 21,
	wxSTC_SQL_USER4                       => 22,
	wxSTC_SQL_QUOTEDIDENTIFIER            => 23,
	wxSTC_ST_DEFAULT                      => 0,
	wxSTC_ST_STRING                       => 1,
	wxSTC_ST_NUMBER                       => 2,
	wxSTC_ST_COMMENT                      => 3,
	wxSTC_ST_SYMBOL                       => 4,
	wxSTC_ST_BINARY                       => 5,
	wxSTC_ST_BOOL                         => 6,
	wxSTC_ST_SELF                         => 7,
	wxSTC_ST_SUPER                        => 8,
	wxSTC_ST_NIL                          => 9,
	wxSTC_ST_GLOBAL                       => 10,
	wxSTC_ST_RETURN                       => 11,
	wxSTC_ST_SPECIAL                      => 12,
	wxSTC_ST_KWSEND                       => 13,
	wxSTC_ST_ASSIGN                       => 14,
	wxSTC_ST_CHARACTER                    => 15,
	wxSTC_ST_SPEC_SEL                     => 16,
	wxSTC_FS_DEFAULT                      => 0,
	wxSTC_FS_COMMENT                      => 1,
	wxSTC_FS_COMMENTLINE                  => 2,
	wxSTC_FS_COMMENTDOC                   => 3,
	wxSTC_FS_COMMENTLINEDOC               => 4,
	wxSTC_FS_COMMENTDOCKEYWORD            => 5,
	wxSTC_FS_COMMENTDOCKEYWORDERROR       => 6,
	wxSTC_FS_KEYWORD                      => 7,
	wxSTC_FS_KEYWORD2                     => 8,
	wxSTC_FS_KEYWORD3                     => 9,
	wxSTC_FS_KEYWORD4                     => 10,
	wxSTC_FS_NUMBER                       => 11,
	wxSTC_FS_STRING                       => 12,
	wxSTC_FS_PREPROCESSOR                 => 13,
	wxSTC_FS_OPERATOR                     => 14,
	wxSTC_FS_IDENTIFIER                   => 15,
	wxSTC_FS_DATE                         => 16,
	wxSTC_FS_STRINGEOL                    => 17,
	wxSTC_FS_CONSTANT                     => 18,
	wxSTC_FS_ASM                          => 19,
	wxSTC_FS_LABEL                        => 20,
	wxSTC_FS_ERROR                        => 21,
	wxSTC_FS_HEXNUMBER                    => 22,
	wxSTC_FS_BINNUMBER                    => 23,
	wxSTC_CSOUND_DEFAULT                  => 0,
	wxSTC_CSOUND_COMMENT                  => 1,
	wxSTC_CSOUND_NUMBER                   => 2,
	wxSTC_CSOUND_OPERATOR                 => 3,
	wxSTC_CSOUND_INSTR                    => 4,
	wxSTC_CSOUND_IDENTIFIER               => 5,
	wxSTC_CSOUND_OPCODE                   => 6,
	wxSTC_CSOUND_HEADERSTMT               => 7,
	wxSTC_CSOUND_USERKEYWORD              => 8,
	wxSTC_CSOUND_COMMENTBLOCK             => 9,
	wxSTC_CSOUND_PARAM                    => 10,
	wxSTC_CSOUND_ARATE_VAR                => 11,
	wxSTC_CSOUND_KRATE_VAR                => 12,
	wxSTC_CSOUND_IRATE_VAR                => 13,
	wxSTC_CSOUND_GLOBAL_VAR               => 14,
	wxSTC_CSOUND_STRINGEOL                => 15,
	wxSTC_INNO_DEFAULT                    => 0,
	wxSTC_INNO_COMMENT                    => 1,
	wxSTC_INNO_KEYWORD                    => 2,
	wxSTC_INNO_PARAMETER                  => 3,
	wxSTC_INNO_SECTION                    => 4,
	wxSTC_INNO_PREPROC                    => 5,
	wxSTC_INNO_INLINE_EXPANSION           => 6,
	wxSTC_INNO_COMMENT_PASCAL             => 7,
	wxSTC_INNO_KEYWORD_PASCAL             => 8,
	wxSTC_INNO_KEYWORD_USER               => 9,
	wxSTC_INNO_STRING_DOUBLE              => 10,
	wxSTC_INNO_STRING_SINGLE              => 11,
	wxSTC_INNO_IDENTIFIER                 => 12,
	wxSTC_OPAL_SPACE                      => 0,
	wxSTC_OPAL_COMMENT_BLOCK              => 1,
	wxSTC_OPAL_COMMENT_LINE               => 2,
	wxSTC_OPAL_INTEGER                    => 3,
	wxSTC_OPAL_KEYWORD                    => 4,
	wxSTC_OPAL_SORT                       => 5,
	wxSTC_OPAL_STRING                     => 6,
	wxSTC_OPAL_PAR                        => 7,
	wxSTC_OPAL_BOOL_CONST                 => 8,
	wxSTC_OPAL_DEFAULT                    => 32,
	wxSTC_SPICE_DEFAULT                   => 0,
	wxSTC_SPICE_IDENTIFIER                => 1,
	wxSTC_SPICE_KEYWORD                   => 2,
	wxSTC_SPICE_KEYWORD2                  => 3,
	wxSTC_SPICE_KEYWORD3                  => 4,
	wxSTC_SPICE_NUMBER                    => 5,
	wxSTC_SPICE_DELIMITER                 => 6,
	wxSTC_SPICE_VALUE                     => 7,
	wxSTC_SPICE_COMMENTLINE               => 8,
	wxSTC_CMAKE_DEFAULT                   => 0,
	wxSTC_CMAKE_COMMENT                   => 1,
	wxSTC_CMAKE_STRINGDQ                  => 2,
	wxSTC_CMAKE_STRINGLQ                  => 3,
	wxSTC_CMAKE_STRINGRQ                  => 4,
	wxSTC_CMAKE_COMMANDS                  => 5,
	wxSTC_CMAKE_PARAMETERS                => 6,
	wxSTC_CMAKE_VARIABLE                  => 7,
	wxSTC_CMAKE_USERDEFINED               => 8,
	wxSTC_CMAKE_WHILEDEF                  => 9,
	wxSTC_CMAKE_FOREACHDEF                => 10,
	wxSTC_CMAKE_IFDEFINEDEF               => 11,
	wxSTC_CMAKE_MACRODEF                  => 12,
	wxSTC_CMAKE_STRINGVAR                 => 13,
	wxSTC_CMAKE_NUMBER                    => 14,
	wxSTC_GAP_DEFAULT                     => 0,
	wxSTC_GAP_IDENTIFIER                  => 1,
	wxSTC_GAP_KEYWORD                     => 2,
	wxSTC_GAP_KEYWORD2                    => 3,
	wxSTC_GAP_KEYWORD3                    => 4,
	wxSTC_GAP_KEYWORD4                    => 5,
	wxSTC_GAP_STRING                      => 6,
	wxSTC_GAP_CHAR                        => 7,
	wxSTC_GAP_OPERATOR                    => 8,
	wxSTC_GAP_COMMENT                     => 9,
	wxSTC_GAP_NUMBER                      => 10,
	wxSTC_GAP_STRINGEOL                   => 11,
	wxSTC_PLM_DEFAULT                     => 0,
	wxSTC_PLM_COMMENT                     => 1,
	wxSTC_PLM_STRING                      => 2,
	wxSTC_PLM_NUMBER                      => 3,
	wxSTC_PLM_IDENTIFIER                  => 4,
	wxSTC_PLM_OPERATOR                    => 5,
	wxSTC_PLM_CONTROL                     => 6,
	wxSTC_PLM_KEYWORD                     => 7,
	wxSTC_4GL_DEFAULT                     => 0,
	wxSTC_4GL_NUMBER                      => 1,
	wxSTC_4GL_WORD                        => 2,
	wxSTC_4GL_STRING                      => 3,
	wxSTC_4GL_CHARACTER                   => 4,
	wxSTC_4GL_PREPROCESSOR                => 5,
	wxSTC_4GL_OPERATOR                    => 6,
	wxSTC_4GL_IDENTIFIER                  => 7,
	wxSTC_4GL_BLOCK                       => 8,
	wxSTC_4GL_END                         => 9,
	wxSTC_4GL_COMMENT1                    => 10,
	wxSTC_4GL_COMMENT2                    => 11,
	wxSTC_4GL_COMMENT3                    => 12,
	wxSTC_4GL_COMMENT4                    => 13,
	wxSTC_4GL_COMMENT5                    => 14,
	wxSTC_4GL_COMMENT6                    => 15,
	wxSTC_4GL_DEFAULT_                    => 16,
	wxSTC_4GL_NUMBER_                     => 17,
	wxSTC_4GL_WORD_                       => 18,
	wxSTC_4GL_STRING_                     => 19,
	wxSTC_4GL_CHARACTER_                  => 20,
	wxSTC_4GL_PREPROCESSOR_               => 21,
	wxSTC_4GL_OPERATOR_                   => 22,
	wxSTC_4GL_IDENTIFIER_                 => 23,
	wxSTC_4GL_BLOCK_                      => 24,
	wxSTC_4GL_END_                        => 25,
	wxSTC_4GL_COMMENT1_                   => 26,
	wxSTC_4GL_COMMENT2_                   => 27,
	wxSTC_4GL_COMMENT3_                   => 28,
	wxSTC_4GL_COMMENT4_                   => 29,
	wxSTC_4GL_COMMENT5_                   => 30,
	wxSTC_4GL_COMMENT6_                   => 31,
	wxSTC_ABAQUS_DEFAULT                  => 0,
	wxSTC_ABAQUS_COMMENT                  => 1,
	wxSTC_ABAQUS_COMMENTBLOCK             => 2,
	wxSTC_ABAQUS_NUMBER                   => 3,
	wxSTC_ABAQUS_STRING                   => 4,
	wxSTC_ABAQUS_OPERATOR                 => 5,
	wxSTC_ABAQUS_WORD                     => 6,
	wxSTC_ABAQUS_PROCESSOR                => 7,
	wxSTC_ABAQUS_COMMAND                  => 8,
	wxSTC_ABAQUS_SLASHCOMMAND             => 9,
	wxSTC_ABAQUS_STARCOMMAND              => 10,
	wxSTC_ABAQUS_ARGUMENT                 => 11,
	wxSTC_ABAQUS_FUNCTION                 => 12,
	wxSTC_ASY_DEFAULT                     => 0,
	wxSTC_ASY_COMMENT                     => 1,
	wxSTC_ASY_COMMENTLINE                 => 2,
	wxSTC_ASY_NUMBER                      => 3,
	wxSTC_ASY_WORD                        => 4,
	wxSTC_ASY_STRING                      => 5,
	wxSTC_ASY_CHARACTER                   => 6,
	wxSTC_ASY_OPERATOR                    => 7,
	wxSTC_ASY_IDENTIFIER                  => 8,
	wxSTC_ASY_STRINGEOL                   => 9,
	wxSTC_ASY_COMMENTLINEDOC              => 10,
	wxSTC_ASY_WORD2                       => 11,
	wxSTC_R_DEFAULT                       => 0,
	wxSTC_R_COMMENT                       => 1,
	wxSTC_R_KWORD                         => 2,
	wxSTC_R_BASEKWORD                     => 3,
	wxSTC_R_OTHERKWORD                    => 4,
	wxSTC_R_NUMBER                        => 5,
	wxSTC_R_STRING                        => 6,
	wxSTC_R_STRING2                       => 7,
	wxSTC_R_OPERATOR                      => 8,
	wxSTC_R_IDENTIFIER                    => 9,
	wxSTC_R_INFIX                         => 10,
	wxSTC_R_INFIXEOL                      => 11,
	wxSTC_MAGIK_DEFAULT                   => 0,
	wxSTC_MAGIK_COMMENT                   => 1,
	wxSTC_MAGIK_HYPER_COMMENT             => 16,
	wxSTC_MAGIK_STRING                    => 2,
	wxSTC_MAGIK_CHARACTER                 => 3,
	wxSTC_MAGIK_NUMBER                    => 4,
	wxSTC_MAGIK_IDENTIFIER                => 5,
	wxSTC_MAGIK_OPERATOR                  => 6,
	wxSTC_MAGIK_FLOW                      => 7,
	wxSTC_MAGIK_CONTAINER                 => 8,
	wxSTC_MAGIK_BRACKET_BLOCK             => 9,
	wxSTC_MAGIK_BRACE_BLOCK               => 10,
	wxSTC_MAGIK_SQBRACKET_BLOCK           => 11,
	wxSTC_MAGIK_UNKNOWN_KEYWORD           => 12,
	wxSTC_MAGIK_KEYWORD                   => 13,
	wxSTC_MAGIK_PRAGMA                    => 14,
	wxSTC_MAGIK_SYMBOL                    => 15,
	wxSTC_POWERSHELL_DEFAULT              => 0,
	wxSTC_POWERSHELL_COMMENT              => 1,
	wxSTC_POWERSHELL_STRING               => 2,
	wxSTC_POWERSHELL_CHARACTER            => 3,
	wxSTC_POWERSHELL_NUMBER               => 4,
	wxSTC_POWERSHELL_VARIABLE             => 5,
	wxSTC_POWERSHELL_OPERATOR             => 6,
	wxSTC_POWERSHELL_IDENTIFIER           => 7,
	wxSTC_POWERSHELL_KEYWORD              => 8,
	wxSTC_POWERSHELL_CMDLET               => 9,
	wxSTC_POWERSHELL_ALIAS                => 10,
	wxSTC_MYSQL_DEFAULT                   => 0,
	wxSTC_MYSQL_COMMENT                   => 1,
	wxSTC_MYSQL_COMMENTLINE               => 2,
	wxSTC_MYSQL_VARIABLE                  => 3,
	wxSTC_MYSQL_SYSTEMVARIABLE            => 4,
	wxSTC_MYSQL_KNOWNSYSTEMVARIABLE       => 5,
	wxSTC_MYSQL_NUMBER                    => 6,
	wxSTC_MYSQL_MAJORKEYWORD              => 7,
	wxSTC_MYSQL_KEYWORD                   => 8,
	wxSTC_MYSQL_DATABASEOBJECT            => 9,
	wxSTC_MYSQL_PROCEDUREKEYWORD          => 10,
	wxSTC_MYSQL_STRING                    => 11,
	wxSTC_MYSQL_SQSTRING                  => 12,
	wxSTC_MYSQL_DQSTRING                  => 13,
	wxSTC_MYSQL_OPERATOR                  => 14,
	wxSTC_MYSQL_FUNCTION                  => 15,
	wxSTC_MYSQL_IDENTIFIER                => 16,
	wxSTC_MYSQL_QUOTEDIDENTIFIER          => 17,
	wxSTC_MYSQL_USER1                     => 18,
	wxSTC_MYSQL_USER2                     => 19,
	wxSTC_MYSQL_USER3                     => 20,
	wxSTC_MYSQL_HIDDENCOMMAND             => 21,
	wxSTC_PO_DEFAULT                      => 0,
	wxSTC_PO_COMMENT                      => 1,
	wxSTC_PO_MSGID                        => 2,
	wxSTC_PO_MSGID_TEXT                   => 3,
	wxSTC_PO_MSGSTR                       => 4,
	wxSTC_PO_MSGSTR_TEXT                  => 5,
	wxSTC_PO_MSGCTXT                      => 6,
	wxSTC_PO_MSGCTXT_TEXT                 => 7,
	wxSTC_PO_FUZZY                        => 8,
	wxSTC_PAS_DEFAULT                     => 0,
	wxSTC_PAS_IDENTIFIER                  => 1,
	wxSTC_PAS_COMMENT                     => 2,
	wxSTC_PAS_COMMENT2                    => 3,
	wxSTC_PAS_COMMENTLINE                 => 4,
	wxSTC_PAS_PREPROCESSOR                => 5,
	wxSTC_PAS_PREPROCESSOR2               => 6,
	wxSTC_PAS_NUMBER                      => 7,
	wxSTC_PAS_HEXNUMBER                   => 8,
	wxSTC_PAS_WORD                        => 9,
	wxSTC_PAS_STRING                      => 10,
	wxSTC_PAS_STRINGEOL                   => 11,
	wxSTC_PAS_CHARACTER                   => 12,
	wxSTC_PAS_OPERATOR                    => 13,
	wxSTC_PAS_ASM                         => 14,
	wxSTC_SORCUS_DEFAULT                  => 0,
	wxSTC_SORCUS_COMMAND                  => 1,
	wxSTC_SORCUS_PARAMETER                => 2,
	wxSTC_SORCUS_COMMENTLINE              => 3,
	wxSTC_SORCUS_STRING                   => 4,
	wxSTC_SORCUS_STRINGEOL                => 5,
	wxSTC_SORCUS_IDENTIFIER               => 6,
	wxSTC_SORCUS_OPERATOR                 => 7,
	wxSTC_SORCUS_NUMBER                   => 8,
	wxSTC_SORCUS_CONSTANT                 => 9,
	wxSTC_POWERPRO_DEFAULT                => 0,
	wxSTC_POWERPRO_COMMENTBLOCK           => 1,
	wxSTC_POWERPRO_COMMENTLINE            => 2,
	wxSTC_POWERPRO_NUMBER                 => 3,
	wxSTC_POWERPRO_WORD                   => 4,
	wxSTC_POWERPRO_WORD2                  => 5,
	wxSTC_POWERPRO_WORD3                  => 6,
	wxSTC_POWERPRO_WORD4                  => 7,
	wxSTC_POWERPRO_DOUBLEQUOTEDSTRING     => 8,
	wxSTC_POWERPRO_SINGLEQUOTEDSTRING     => 9,
	wxSTC_POWERPRO_LINECONTINUE           => 10,
	wxSTC_POWERPRO_OPERATOR               => 11,
	wxSTC_POWERPRO_IDENTIFIER             => 12,
	wxSTC_POWERPRO_STRINGEOL              => 13,
	wxSTC_POWERPRO_VERBATIM               => 14,
	wxSTC_POWERPRO_ALTQUOTE               => 15,
	wxSTC_POWERPRO_FUNCTION               => 16,
	wxSTC_SML_DEFAULT                     => 0,
	wxSTC_SML_IDENTIFIER                  => 1,
	wxSTC_SML_TAGNAME                     => 2,
	wxSTC_SML_KEYWORD                     => 3,
	wxSTC_SML_KEYWORD2                    => 4,
	wxSTC_SML_KEYWORD3                    => 5,
	wxSTC_SML_LINENUM                     => 6,
	wxSTC_SML_OPERATOR                    => 7,
	wxSTC_SML_NUMBER                      => 8,
	wxSTC_SML_CHAR                        => 9,
	wxSTC_SML_STRING                      => 11,
	wxSTC_SML_COMMENT                     => 12,
	wxSTC_SML_COMMENT1                    => 13,
	wxSTC_SML_COMMENT2                    => 14,
	wxSTC_SML_COMMENT3                    => 15,
	wxSTC_MARKDOWN_DEFAULT                => 0,
	wxSTC_MARKDOWN_LINE_BEGIN             => 1,
	wxSTC_MARKDOWN_STRONG1                => 2,
	wxSTC_MARKDOWN_STRONG2                => 3,
	wxSTC_MARKDOWN_EM1                    => 4,
	wxSTC_MARKDOWN_EM2                    => 5,
	wxSTC_MARKDOWN_HEADER1                => 6,
	wxSTC_MARKDOWN_HEADER2                => 7,
	wxSTC_MARKDOWN_HEADER3                => 8,
	wxSTC_MARKDOWN_HEADER4                => 9,
	wxSTC_MARKDOWN_HEADER5                => 10,
	wxSTC_MARKDOWN_HEADER6                => 11,
	wxSTC_MARKDOWN_PRECHAR                => 12,
	wxSTC_MARKDOWN_ULIST_ITEM             => 13,
	wxSTC_MARKDOWN_OLIST_ITEM             => 14,
	wxSTC_MARKDOWN_BLOCKQUOTE             => 15,
	wxSTC_MARKDOWN_STRIKEOUT              => 16,
	wxSTC_MARKDOWN_HRULE                  => 17,
	wxSTC_MARKDOWN_LINK                   => 18,
	wxSTC_MARKDOWN_CODE                   => 19,
	wxSTC_MARKDOWN_CODE2                  => 20,
	wxSTC_MARKDOWN_CODEBK                 => 21,
	wxSTC_CMD_REDO                        => 2011,
	wxSTC_CMD_SELECTALL                   => 2013,
	wxSTC_CMD_UNDO                        => 2176,
	wxSTC_CMD_CUT                         => 2177,
	wxSTC_CMD_COPY                        => 2178,
	wxSTC_CMD_PASTE                       => 2179,
	wxSTC_CMD_CLEAR                       => 2180,
	wxSTC_CMD_LINEDOWN                    => 2300,
	wxSTC_CMD_LINEDOWNEXTEND              => 2301,
	wxSTC_CMD_LINEUP                      => 2302,
	wxSTC_CMD_LINEUPEXTEND                => 2303,
	wxSTC_CMD_CHARLEFT                    => 2304,
	wxSTC_CMD_CHARLEFTEXTEND              => 2305,
	wxSTC_CMD_CHARRIGHT                   => 2306,
	wxSTC_CMD_CHARRIGHTEXTEND             => 2307,
	wxSTC_CMD_WORDLEFT                    => 2308,
	wxSTC_CMD_WORDLEFTEXTEND              => 2309,
	wxSTC_CMD_WORDRIGHT                   => 2310,
	wxSTC_CMD_WORDRIGHTEXTEND             => 2311,
	wxSTC_CMD_HOME                        => 2312,
	wxSTC_CMD_HOMEEXTEND                  => 2313,
	wxSTC_CMD_LINEEND                     => 2314,
	wxSTC_CMD_LINEENDEXTEND               => 2315,
	wxSTC_CMD_DOCUMENTSTART               => 2316,
	wxSTC_CMD_DOCUMENTSTARTEXTEND         => 2317,
	wxSTC_CMD_DOCUMENTEND                 => 2318,
	wxSTC_CMD_DOCUMENTENDEXTEND           => 2319,
	wxSTC_CMD_PAGEUP                      => 2320,
	wxSTC_CMD_PAGEUPEXTEND                => 2321,
	wxSTC_CMD_PAGEDOWN                    => 2322,
	wxSTC_CMD_PAGEDOWNEXTEND              => 2323,
	wxSTC_CMD_EDITTOGGLEOVERTYPE          => 2324,
	wxSTC_CMD_CANCEL                      => 2325,
	wxSTC_CMD_DELETEBACK                  => 2326,
	wxSTC_CMD_TAB                         => 2327,
	wxSTC_CMD_BACKTAB                     => 2328,
	wxSTC_CMD_NEWLINE                     => 2329,
	wxSTC_CMD_FORMFEED                    => 2330,
	wxSTC_CMD_VCHOME                      => 2331,
	wxSTC_CMD_VCHOMEEXTEND                => 2332,
	wxSTC_CMD_ZOOMIN                      => 2333,
	wxSTC_CMD_ZOOMOUT                     => 2334,
	wxSTC_CMD_DELWORDLEFT                 => 2335,
	wxSTC_CMD_DELWORDRIGHT                => 2336,
	wxSTC_CMD_DELWORDRIGHTEND             => 2518,
	wxSTC_CMD_LINECUT                     => 2337,
	wxSTC_CMD_LINEDELETE                  => 2338,
	wxSTC_CMD_LINETRANSPOSE               => 2339,
	wxSTC_CMD_LINEDUPLICATE               => 2404,
	wxSTC_CMD_LOWERCASE                   => 2340,
	wxSTC_CMD_UPPERCASE                   => 2341,
	wxSTC_CMD_LINESCROLLDOWN              => 2342,
	wxSTC_CMD_LINESCROLLUP                => 2343,
	wxSTC_CMD_DELETEBACKNOTLINE           => 2344,
	wxSTC_CMD_HOMEDISPLAY                 => 2345,
	wxSTC_CMD_HOMEDISPLAYEXTEND           => 2346,
	wxSTC_CMD_LINEENDDISPLAY              => 2347,
	wxSTC_CMD_LINEENDDISPLAYEXTEND        => 2348,
	wxSTC_CMD_HOMEWRAP                    => 2349,
	wxSTC_CMD_HOMEWRAPEXTEND              => 2450,
	wxSTC_CMD_LINEENDWRAP                 => 2451,
	wxSTC_CMD_LINEENDWRAPEXTEND           => 2452,
	wxSTC_CMD_VCHOMEWRAP                  => 2453,
	wxSTC_CMD_VCHOMEWRAPEXTEND            => 2454,
	wxSTC_CMD_LINECOPY                    => 2455,
	wxSTC_CMD_WORDPARTLEFT                => 2390,
	wxSTC_CMD_WORDPARTLEFTEXTEND          => 2391,
	wxSTC_CMD_WORDPARTRIGHT               => 2392,
	wxSTC_CMD_WORDPARTRIGHTEXTEND         => 2393,
	wxSTC_CMD_DELLINELEFT                 => 2395,
	wxSTC_CMD_DELLINERIGHT                => 2396,
	wxSTC_CMD_PARADOWN                    => 2413,
	wxSTC_CMD_PARADOWNEXTEND              => 2414,
	wxSTC_CMD_PARAUP                      => 2415,
	wxSTC_CMD_PARAUPEXTEND                => 2416,
	wxSTC_CMD_LINEDOWNRECTEXTEND          => 2426,
	wxSTC_CMD_LINEUPRECTEXTEND            => 2427,
	wxSTC_CMD_CHARLEFTRECTEXTEND          => 2428,
	wxSTC_CMD_CHARRIGHTRECTEXTEND         => 2429,
	wxSTC_CMD_HOMERECTEXTEND              => 2430,
	wxSTC_CMD_VCHOMERECTEXTEND            => 2431,
	wxSTC_CMD_LINEENDRECTEXTEND           => 2432,
	wxSTC_CMD_PAGEUPRECTEXTEND            => 2433,
	wxSTC_CMD_PAGEDOWNRECTEXTEND          => 2434,
	wxSTC_CMD_STUTTEREDPAGEUP             => 2435,
	wxSTC_CMD_STUTTEREDPAGEUPEXTEND       => 2436,
	wxSTC_CMD_STUTTEREDPAGEDOWN           => 2437,
	wxSTC_CMD_STUTTEREDPAGEDOWNEXTEND     => 2438,
	wxSTC_CMD_WORDLEFTEND                 => 2439,
	wxSTC_CMD_WORDLEFTENDEXTEND           => 2440,
	wxSTC_CMD_WORDRIGHTEND                => 2441,
	wxSTC_CMD_WORDRIGHTENDEXTEND          => 2442,
};

# check for loaded Wx::STC
if ( exists( $INC{'Wx/STC.pm'} ) ) {
	croak( 'Wx::Scintilla cannot be loaded alongside Wx::STC. Choose one and only one of the modules. ' );
}

require XSLoader;
XSLoader::load 'Wx::Scintilla', $VERSION;

#
# properly setup inheritance tree
#

no strict;

package Wx::ScintillaTextCtrl;
our $VERSION = '0.31_02';
@ISA = qw(Wx::Control);

package Wx::ScintillaTextEvent;
our $VERSION = '0.31_02';
@ISA = qw(Wx::CommandEvent);

#Defeat the indexer by splitting the package declaration on two lines
#<<<  do not let perltidy touch this
package
    Wx::Event;
# Don't set global Wx::Event version
#>>>

use strict;

{

	# Disable Wx::EVT_STC_* event warning redefinition
	no warnings 'redefine';

	sub EVT_STC_CHANGE($$$) {
		$_[0]->Connect( $_[1], -1, &Wx::wxEVT_STC_CHANGE, $_[2] );
	}

	sub EVT_STC_STYLENEEDED($$$) {
		$_[0]->Connect( $_[1], -1, &Wx::wxEVT_STC_STYLENEEDED, $_[2] );
	}

	sub EVT_STC_CHARADDED($$$) {
		$_[0]->Connect( $_[1], -1, &Wx::wxEVT_STC_CHARADDED, $_[2] );
	}

	sub EVT_STC_SAVEPOINTREACHED($$$) {
		$_[0]->Connect( $_[1], -1, &Wx::wxEVT_STC_SAVEPOINTREACHED, $_[2] );
	}

	sub EVT_STC_SAVEPOINTLEFT($$$) {
		$_[0]->Connect( $_[1], -1, &Wx::wxEVT_STC_SAVEPOINTLEFT, $_[2] );
	}

	sub EVT_STC_ROMODIFYATTEMPT($$$) {
		$_[0]->Connect( $_[1], -1, &Wx::wxEVT_STC_ROMODIFYATTEMPT, $_[2] );
	}

	sub EVT_STC_KEY($$$) {
		$_[0]->Connect( $_[1], -1, &Wx::wxEVT_STC_KEY, $_[2] );
	}

	sub EVT_STC_DOUBLECLICK($$$) {
		$_[0]->Connect( $_[1], -1, &Wx::wxEVT_STC_DOUBLECLICK, $_[2] );
	}

	sub EVT_STC_UPDATEUI($$$) {
		$_[0]->Connect( $_[1], -1, &Wx::wxEVT_STC_UPDATEUI, $_[2] );
	}

	sub EVT_STC_MODIFIED($$$) {
		$_[0]->Connect( $_[1], -1, &Wx::wxEVT_STC_MODIFIED, $_[2] );
	}

	sub EVT_STC_MACRORECORD($$$) {
		$_[0]->Connect( $_[1], -1, &Wx::wxEVT_STC_MACRORECORD, $_[2] );
	}

	sub EVT_STC_MARGINCLICK($$$) {
		$_[0]->Connect( $_[1], -1, &Wx::wxEVT_STC_MARGINCLICK, $_[2] );
	}

	sub EVT_STC_NEEDSHOWN($$$) {
		$_[0]->Connect( $_[1], -1, &Wx::wxEVT_STC_NEEDSHOWN, $_[2] );
	}

	sub EVT_STC_POSCHANGED($$$) {
		require Carp;
		Carp::croak 'EVT_STC_POSCHANGED is deprecated - Please use EVT_STC_UPDATEUI instead.';
	}

	sub EVT_STC_PAINTED($$$) {
		$_[0]->Connect( $_[1], -1, &Wx::wxEVT_STC_PAINTED, $_[2] );
	}

	sub EVT_STC_USERLISTSELECTION($$$) {
		$_[0]->Connect( $_[1], -1, &Wx::wxEVT_STC_USERLISTSELECTION, $_[2] );
	}

	sub EVT_STC_URIDROPPED($$$) {
		$_[0]->Connect( $_[1], -1, &Wx::wxEVT_STC_URIDROPPED, $_[2] );
	}

	sub EVT_STC_DWELLSTART($$$) {
		$_[0]->Connect( $_[1], -1, &Wx::wxEVT_STC_DWELLSTART, $_[2] );
	}

	sub EVT_STC_DWELLEND($$$) {
		$_[0]->Connect( $_[1], -1, &Wx::wxEVT_STC_DWELLEND, $_[2] );
	}

	sub EVT_STC_START_DRAG($$$) {
		$_[0]->Connect( $_[1], -1, &Wx::wxEVT_STC_START_DRAG, $_[2] );
	}

	sub EVT_STC_DRAG_OVER($$$) {
		$_[0]->Connect( $_[1], -1, &Wx::wxEVT_STC_DRAG_OVER, $_[2] );
	}

	sub EVT_STC_DO_DROP($$$) {
		$_[0]->Connect( $_[1], -1, &Wx::wxEVT_STC_DO_DROP, $_[2] );
	}

	sub EVT_STC_ZOOM($$$) {
		$_[0]->Connect( $_[1], -1, &Wx::wxEVT_STC_ZOOM, $_[2] );
	}

	sub EVT_STC_HOTSPOT_CLICK($$$) {
		$_[0]->Connect( $_[1], -1, &Wx::wxEVT_STC_HOTSPOT_CLICK, $_[2] );
	}

	sub EVT_STC_HOTSPOT_DCLICK($$$) {
		$_[0]->Connect( $_[1], -1, &Wx::wxEVT_STC_HOTSPOT_DCLICK, $_[2] );
	}

	sub EVT_STC_CALLTIP_CLICK($$$) {
		$_[0]->Connect( $_[1], -1, &Wx::wxEVT_STC_CALLTIP_CLICK, $_[2] );
	}

	sub EVT_STC_INDICATOR_CLICK($$$) {
		$_[0]->Connect( $_[1], -1, &Wx::wxEVT_STC_INDICATOR_CLICK, $_[2] );
	}

	sub EVT_STC_INDICATOR_RELEASE($$$) {
		$_[0]->Connect( $_[1], -1, &Wx::wxEVT_STC_INDICATOR_RELEASE, $_[2] );
	}

	sub EVT_STC_AUTOCOMP_CANCELLED($$$) {
		$_[0]->Connect( $_[1], -1, &Wx::wxEVT_STC_AUTOCOMP_CANCELLED, $_[2] );
	}

	sub EVT_STC_AUTOCOMP_CHAR_DELETED($$$) {
		$_[0]->Connect( $_[1], -1, &Wx::wxEVT_STC_AUTOCOMP_CHAR_DELETED, $_[2] );
	}
}

1; # The end of Wx::Scintilla? :)

__END__

=pod

=head1 NAME

Wx::Scintilla - Scintilla source code editing component for wxWidgets

=head1 SYNOPSIS

    #----> My first scintilla Wx editor :)
    package My::Scintilla::Editor;

    use strict;
    use warnings;

    # Load Wx::Scintilla
    use Wx::Scintilla ();    # replaces use Wx::STC
    use base 'Wx::ScintillaTextCtrl';    # replaces Wx::StyledTextCtrl

    use Wx qw(:everything);
    use Wx::Event;

    # Override the constructor to Enable Perl support in the editor
    sub new {
        my ( $class, $parent ) = @_;
        my $self = $class->SUPER::new( $parent, -1, [ -1, -1 ], [ 750, 700 ] );

        # Set the font
        my $font = Wx::Font->new( 10, wxTELETYPE, wxNORMAL, wxNORMAL );
        $self->SetFont($font);
        $self->StyleSetFont( wxSTC_STYLE_DEFAULT, $font );
        $self->StyleClearAll();

        # Set the various Perl lexer colors
        $self->StyleSetForeground( 0,  Wx::Colour->new( 0x00, 0x00, 0x7f ) );
        $self->StyleSetForeground( 1,  Wx::Colour->new( 0xff, 0x00, 0x00 ) );
        $self->StyleSetForeground( 2,  Wx::Colour->new( 0x00, 0x7f, 0x00 ) );
        $self->StyleSetForeground( 3,  Wx::Colour->new( 0x7f, 0x7f, 0x7f ) );
        $self->StyleSetForeground( 4,  Wx::Colour->new( 0x00, 0x7f, 0x7f ) );
        $self->StyleSetForeground( 5,  Wx::Colour->new( 0x00, 0x00, 0x7f ) );
        $self->StyleSetForeground( 6,  Wx::Colour->new( 0xff, 0x7f, 0x00 ) );
        $self->StyleSetForeground( 7,  Wx::Colour->new( 0x7f, 0x00, 0x7f ) );
        $self->StyleSetForeground( 8,  Wx::Colour->new( 0x00, 0x00, 0x00 ) );
        $self->StyleSetForeground( 9,  Wx::Colour->new( 0x7f, 0x7f, 0x7f ) );
        $self->StyleSetForeground( 10, Wx::Colour->new( 0x00, 0x00, 0x7f ) );
        $self->StyleSetForeground( 11, Wx::Colour->new( 0x00, 0x00, 0xff ) );
        $self->StyleSetForeground( 12, Wx::Colour->new( 0x7f, 0x00, 0x7f ) );
        $self->StyleSetForeground( 13, Wx::Colour->new( 0x40, 0x80, 0xff ) );
        $self->StyleSetForeground( 17, Wx::Colour->new( 0xff, 0x00, 0x7f ) );
        $self->StyleSetForeground( 18, Wx::Colour->new( 0x7f, 0x7f, 0x00 ) );
        $self->StyleSetBold( 12, 1 );
        $self->StyleSetSpec( wxSTC_H_TAG, "fore:#0000ff" );

        # set the lexer to Perl 5
        $self->SetLexer(wxSTC_LEX_PERL);

        return $self;
    }

    #----> DEMO EDITOR APPLICATION

    # First, define an application object class to encapsulate the application itself
    package DemoEditorApp;

    use strict;
    use warnings;
    use Wx;
    use base 'Wx::App';

    # We must override OnInit to build the window
    sub OnInit {
        my $self = shift;

        my $frame = Wx::Frame->new(
        undef,                           # no parent window
        -1,                              # no window id
        'My First Scintilla Editor!',    # Window title
        );

        my $editor = My::Scintilla::Editor->new(
        $frame,                          # Parent window
        );

        $frame->Show(1);
        return 1;
    }

    # Create the application object, and pass control to it.
    package main;
    my $app = DemoEditorApp->new;
    $app->MainLoop;


=head1 DESCRIPTION

While we already have a good scintilla editor component support via 
Wx::StyledTextCtrl in Perl, we already suffer from an older scintilla package 
and thus lagging Perl support in the popular Wx Scintilla component. wxWidgets 
L<http://wxwidgets.org> has a *very slow* release timeline. Scintilla is a 
contributed project which means it will not be the latest by the time a new 
wxWidgets distribution is released. And on the scintilla front, the Perl 5 lexer 
is not 100% bug free even and we do not have any kind of Perl 6 support in 
Scintilla.

The ambitious goal of this project is to provide fresh Perl 5 and maybe 6 
support in L<Wx> while preserving compatibility with Wx::StyledTextCtrl
and continually contribute it back to Scintilla project.

Note: You cannot load Wx::STC and Wx::Scintilla in the same application. They
are mutually exclusive. The wxSTC_... events are handled by one library or
the other.

Scintilla 2.28 is now bundled and enabled by default.

=head1 MANUAL

If you are looking for more API documentation, please consult L<Wx::Scintilla::Manual>

=head1 PLATFORMS

At the moment, Linux (Debian, Ubuntu, Fedora, CentOS) and Windows (Strawberry
and ActivePerl)  are supported platforms. My next goal is to support more 
platforms. Please let me know if you can help out :)

On Debian/Ubuntu, you need to install the following via:

    sudo apt-get install libgtk2.0-dev

On MacOS 64-bit by default you need to install a 32-bit Perl in order to
install wxWidgets 2.8.x. Please refer to 
L<http://wiki.wxperl.info/w/index.php/Mac_OS_X_Platform_Notes> for more information.

=head1 HISTORY

wxWidgets 2.9.1 and development have Scintilla 2.03 so far. I searched for Perl lexer
changes in scintilla history and here is what we will be getting when we upgrade to
2.26+.

=over

=item Release 2.26

Perl folding folds "here doc"s and adds options fold.perl.at.else and
fold.perl.comment.explicit. Fold structure for Perl fixed. 

=item Release 2.20

Perl folder works for array blocks, adjacent package statements, nested PODs,
and terminates package folding at DATA, D and Z.

=item Release 1.79

Perl lexer bug fixed where previous lexical states persisted causing "/" special 
case styling and subroutine prototype styling to not be correct.

=item Release 1.78

Perl lexer fixes problem with string matching caused by line endings.

=item Release 1.77

Perl lexer update.

=item Release 1.76

Perl lexer handles defined-or operator "".

=item Release 1.75

Perl lexer enhanced for handling minus-prefixed barewords, underscores in
numeric literals and vector/version strings, D and Z similar to END, subroutine 
prototypes as a new lexical class, formats and format blocks as new lexical
classes, and '/' suffixed keywords and barewords.

=item Release 1.71

Perl lexer allows UTF-8 identifiers and has some other small improvements.

=back

=head1 ACKNOWLEDGEMENTS

Neil Hudgson for creating and maintaining the excellent Scintilla project
L<http://scintilla.org>. Thanks!

Robin Dunn L<http://alldunn.com/robin/> for the excellent scintilla 
contribution that he made to wxWidgets. This work is based on his codebase.
Thanks!

Mark dootson L<http://search.cpan.org/~mdootson/> for his big effort to make
Wx::Scintilla compilable on various platforms. Big thanks!

Heiko Jansen and Gabor Szabo L<http://szabgab.com> for the idea to backport
Perl lexer for wxWidgets 2.8.10 L<http://padre.perlide.org/trac/ticket/257>
and all of #padre members for the continuous support and testing. Thanks!

=head1 SUPPORT

Bugs should always be submitted via the CPAN bug tracker

L<http://rt.cpan.org/NoAuth/ReportBug.html?Queue=Wx-Scintilla>

For other issues, contact the maintainer.

=head1 AUTHOR

Ahmad M. Zawawi <ahmad.zawawi@gmail.com>

Mark Dootson <http://www.wxperl.co.uk>

=head1 SEE ALSO

Wx::Scintilla Manual L<Wx::Scintilla::Manual>

wxStyledTextCtrl Documentation L<http://www.yellowbrain.com/stc/index.html>

Scintilla edit control for Win32::GUI L<Win32::GUI::Scintilla>

=head1 COPYRIGHT AND LICENSE

Copyright 2011 Ahmad M. Zawawi.

This program is free software; you can redistribute
it and/or modify it under the same terms as Perl itself.

License for Scintilla

Included Scintilla source is copyrighted 1998-2011 by Neil Hodgson <neilh@scintilla.org>

Permission to use, copy, modify, and distribute this software and its documentation for any purpose and without fee is hereby granted, provided that the above copyright notice appear in all copies and that both that copyright notice and this permission notice appear in supporting documentation.

NEIL HODGSON DISCLAIMS ALL WARRANTIES WITH REGARD TO THIS SOFTWARE, INCLUDING ALL IMPLIED WARRANTIES OF MERCHANTABILITY AND FITNESS, IN NO EVENT SHALL NEIL HODGSON BE LIABLE FOR ANY SPECIAL, INDIRECT OR CONSEQUENTIAL DAMAGES OR ANY DAMAGES WHATSOEVER RESULTING FROM LOSS OF USE, DATA OR PROFITS, WHETHER IN AN ACTION OF CONTRACT, NEGLIGENCE OR OTHER TORTIOUS ACTION, ARISING OUT OF OR IN CONNECTION WITH THE USE OR PERFORMANCE OF THIS SOFTWARE.

=cut
