---
name: Padre-Plugin-Nopaste
version: 0.2.1
author:
  - 'Jerome Quelin <jquelin@gmail.com>'
abstract: send code on a nopaste website from padre
license: perl
resources:
  license: http://dev.perl.org/licenses/
requires:
  App::Nopaste: 0
  File::Basename: 0
  File::Spec::Functions: 0
  Module::Util: 0
  Padre: 0.28
  Padre::Plugin: 0.28
  Padre::Task: 0.30
  parent: 0
build_requires:
  Test::More: 0
provides:
  Padre::Plugin::Nopaste:
    file: lib/Padre/Plugin/Nopaste.pm
    version: 0.2.1
generated_by: Module::Build version 0.32
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.2.html
  version: 1.2
