---
name: Padre-Plugin-HTMLExport
version: 0.01
author:
  - 'Fayland Lam <fayland@gmail.com>'
abstract: export highlighted HTML in Padre
license: perl
resources:
  license: http://dev.perl.org/licenses/
build_requires:
  Padre: 0.18
  Syntax::Highlight::Engine::Kate: 0
  Test::More: 0
provides:
  Padre::Plugin::HTMLExport:
    file: lib/Padre/Plugin/HTMLExport.pm
    version: 0.01
generated_by: Module::Build version 0.3
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.2.html
  version: 1.2
