---
name: Padre-Plugin-Mojolicious
version: 0.02
author:
  - 'Breno G. de Oliveira <garu@cpan.org>'
abstract: Simple Mojolicious helper interface for Padre
license: perl
resources:
  homepage: http://padre.perlide.org/
  license: http://dev.perl.org/licenses/
  repository: http://svn.perlide.org/padre/trunk/Padre-Plugin-Mojolicious/
configure_requires:
  Padre::PluginBuilder: 0.12
build_requires:
  File::Basename: 0
  Module::Build: 0.3
  Module::Pluggable::Object: 3.9
  Mojo: 0.9
  Padre: 0.29
  Test::More: 0
provides:
  Padre::Plugin::Mojolicious:
    file: lib/Padre/Plugin/Mojolicious.pm
    version: 0.02
  Padre::Plugin::Mojolicious::NewApp:
    file: lib/Padre/Plugin/Mojolicious/NewApp.pm
    version: 0.02
  Padre::Plugin::Mojolicious::Util:
    file: lib/Padre/Plugin/Mojolicious/Util.pm
    version: 0.02
generated_by: Module::Build version 0.33
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: 1.4
