---
name: Padre-Plugin-CPAN
version: 0.07
author:
  - 'Fayland Lam <fayland@gmail.com>'
abstract: CPAN in Padre
license: perl
resources:
  license: http://dev.perl.org/licenses/
build_requires:
  CPAN: 0
  File::Spec: 0
  Padre: 0.21
  Test::More: 0
provides:
  Padre::Plugin::CPAN:
    file: lib/Padre/Plugin/CPAN.pm
    version: 0.07
generated_by: Module::Build version 0.3
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.2.html
  version: 1.2
