---
name: Padre-Plugin-Autoformat
version: 1.1.2
author:
  - 'Jerome Quelin <jquelin@gmail.com>'
abstract: reformat your text within Padre
license: perl
resources:
  license: http://dev.perl.org/licenses/
requires:
  File::Basename: 0
  File::Spec::Functions: 0
  Module::Util: 0
build_requires:
  Padre: 0.30
  Test::More: 0
  Text::Autoformat: 0
provides:
  Padre::Plugin::Autoformat:
    file: lib/Padre/Plugin/Autoformat.pm
    version: 1.1.2
generated_by: Module::Build version 0.32
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.2.html
  version: 1.2
