=pod

PyFrame Guide to wxPython

Copyright and License information Home

__ A B C D E F G H I L M P R S T U V W

=head1 wxStyledTextCtrl - Variable Wrappers

B<Summary>:

This page has an alphabetic list of all of the STC variables as used
from Python. They're variables used as constants, actually.

Almost all of these variables just integer objects; and the main
purpose of this page is so that you can easily determine whether or not
a particular value exists. If it does not, you should examine the
source for stc_.cpp (look near the end of the file) as it may have
changed with a wxPython version change.

It would be a B<I<really> BAD> idea to use one of the constant values
(say, 1650) rather than one of the variables (say, wxEVT_STC_CHANGE) as
the values could potentially change with wxPython/wxWindows/Scintilla
versions.

STC_USE_DND = 1

wxEVT_STC_CHANGE = 1650

wxEVT_STC_CHARADDED = 1652

wxEVT_STC_DO_DROP = 1671

wxEVT_STC_DOUBLECLICK = 1657

wxEVT_STC_DRAG_OVER = 1670

wxEVT_STC_DWELLEND = 1668

wxEVT_STC_DWELLSTART = 1667

wxEVT_STC_KEY = 1656

wxEVT_STC_MACRORECORD = 1660

wxEVT_STC_MARGINCLICK = 1661

wxEVT_STC_MODIFIED = 1659

wxEVT_STC_NEEDSHOWN = 1662

wxEVT_STC_PAINTED = 1664

wxEVT_STC_POSCHANGED = 1663

wxEVT_STC_ROMODIFYATTEMPT = 1655

wxEVT_STC_SAVEPOINTLEFT = 1654

wxEVT_STC_SAVEPOINTREACHED = 1653

wxEVT_STC_START_DRAG = 1669

wxEVT_STC_STYLENEEDED = 1651

wxEVT_STC_UPDATEUI = 1658

wxEVT_STC_URIDROPPED = 1666

wxEVT_STC_USERLISTSELECTION = 1665

wxEVT_STC_ZOOM = 1672

wxSTC_ADA_CHARACTER = 5

wxSTC_ADA_COMMENT = 1

wxSTC_ADA_DEFAULT = 0

wxSTC_ADA_IDENTIFIER = 7

wxSTC_ADA_NUMBER = 2

wxSTC_ADA_OPERATOR = 6

wxSTC_ADA_STRING = 4

wxSTC_ADA_STRINGEOL = 8

wxSTC_ADA_WORD = 3

wxSTC_AVE_COMMENT = 1

wxSTC_AVE_DEFAULT = 0

wxSTC_AVE_ENUM = 7

wxSTC_AVE_IDENTIFIER = 9

wxSTC_AVE_KEYWORD = 4

wxSTC_AVE_NUMBER = 2

wxSTC_AVE_OPERATOR = 10

wxSTC_AVE_STATEMENT = 5

wxSTC_AVE_STRING = 6

wxSTC_AVE_STRINGEOL = 8

wxSTC_AVE_WORD = 3

wxSTC_B_COMMENT = 1

wxSTC_B_DATE = 8

wxSTC_B_DEFAULT = 0

wxSTC_B_IDENTIFIER = 7

wxSTC_B_KEYWORD = 3

wxSTC_B_NUMBER = 2

wxSTC_B_OPERATOR = 6

wxSTC_B_PREPROCESSOR = 5

wxSTC_B_STRING = 4

wxSTC_BAAN_COMMENT = 1

wxSTC_BAAN_COMMENTDOC = 2

wxSTC_BAAN_DEFAULT = 0

wxSTC_BAAN_IDENTIFIER = 8

wxSTC_BAAN_NUMBER = 3

wxSTC_BAAN_OPERATOR = 7

wxSTC_BAAN_PREPROCESSOR = 6

wxSTC_BAAN_STRING = 5

wxSTC_BAAN_STRINGEOL = 9

wxSTC_BAAN_WORD = 4

wxSTC_BAAN_WORD2 = 10

wxSTC_BAT_COMMAND = 5

wxSTC_BAT_COMMENT = 1

wxSTC_BAT_DEFAULT = 0

wxSTC_BAT_HIDE = 4

wxSTC_BAT_IDENTIFIER = 6

wxSTC_BAT_LABEL = 3

wxSTC_BAT_OPERATOR = 7

wxSTC_BAT_WORD = 2

wxSTC_C_CHARACTER = 7

wxSTC_C_COMMENT = 1

wxSTC_C_COMMENTDOC = 3

wxSTC_C_COMMENTDOCKEYWORD = 17

wxSTC_C_COMMENTDOCKEYWORDERROR = 18

wxSTC_C_COMMENTLINE = 2

wxSTC_C_COMMENTLINEDOC = 15

wxSTC_C_DEFAULT = 0

wxSTC_C_IDENTIFIER = 11

wxSTC_C_NUMBER = 4

wxSTC_C_OPERATOR = 10

wxSTC_C_PREPROCESSOR = 9

wxSTC_C_REGEX = 14

wxSTC_C_STRING = 6

wxSTC_C_STRINGEOL = 12

wxSTC_C_UUID = 8

wxSTC_C_VERBATIM = 13

wxSTC_C_WORD = 5

wxSTC_C_WORD2 = 16

wxSTC_CACHE_CARET = 1

wxSTC_CACHE_DOCUMENT = 3

wxSTC_CACHE_NONE = 0

wxSTC_CACHE_PAGE = 2

wxSTC_CARET_CENTER = wxSTC_CARET_STRICT

wxSTC_CARET_EVEN = 0x08

wxSTC_CARET_JUMPS = 0x10

wxSTC_CARET_SLOP = 0x01

wxSTC_CARET_STRICT = 0x04

wxSTC_CASE_LOWER = 2

wxSTC_CASE_MIXED = 0

wxSTC_CASE_UPPER = 1

wxSTC_CHARSET_ANSI = 0

wxSTC_CHARSET_ARABIC = 178

wxSTC_CHARSET_BALTIC = 186

wxSTC_CHARSET_CHINESEBIG5 = 136

wxSTC_CHARSET_DEFAULT = 1

wxSTC_CHARSET_EASTEUROPE = 238

wxSTC_CHARSET_GB2312 = 134

wxSTC_CHARSET_GREEK = 161

wxSTC_CHARSET_HANGUL = 129

wxSTC_CHARSET_HEBREW = 177

wxSTC_CHARSET_JOHAB = 130

wxSTC_CHARSET_MAC = 77

wxSTC_CHARSET_OEM = 255

wxSTC_CHARSET_RUSSIAN = 204

wxSTC_CHARSET_SHIFTJIS = 128

wxSTC_CHARSET_SYMBOL = 2

wxSTC_CHARSET_THAI = 222

wxSTC_CHARSET_TURKISH = 162

wxSTC_CHARSET_VIETNAMESE = 163

wxSTC_CMD_BACKTAB = 2328

wxSTC_CMD_CANCEL = 2325

wxSTC_CMD_CHARLEFT = 2304

wxSTC_CMD_CHARLEFTEXTEND = 2305

wxSTC_CMD_CHARRIGHT = 2306

wxSTC_CMD_CHARRIGHTEXTEND = 2307

wxSTC_CMD_COPY = 2178

wxSTC_CMD_CUT = 2177

wxSTC_CMD_DELETEBACK = 2326

wxSTC_CMD_DELETEBACKNOTLINE = 2344

wxSTC_CMD_DELWORDLEFT = 2335

wxSTC_CMD_DELWORDRIGHT = 2336

wxSTC_CMD_DOCUMENTEND = 2318

wxSTC_CMD_DOCUMENTENDEXTEND = 2319

wxSTC_CMD_DOCUMENTSTART = 2316

wxSTC_CMD_DOCUMENTSTARTEXTEND = 2317

wxSTC_CMD_EDITTOGGLEOVERTYPE = 2324

wxSTC_CMD_FORMFEED = 2330

wxSTC_CMD_HOME = 2312

wxSTC_CMD_HOMEDISPLAY = 2345

wxSTC_CMD_HOMEDISPLAYEXTEND = 2346

wxSTC_CMD_HOMEEXTEND = 2313

wxSTC_CMD_LINECUT = 2337

wxSTC_CMD_LINEDELETE = 2338

wxSTC_CMD_LINEDOWN = 2300

wxSTC_CMD_LINEDOWNEXTEND = 2301

wxSTC_CMD_LINEEND = 2314

wxSTC_CMD_LINEENDDISPLAY = 2347

wxSTC_CMD_LINEENDDISPLAYEXTEND = 2348

wxSTC_CMD_LINEENDEXTEND = 2315

wxSTC_CMD_LINESCROLLDOWN = 2342

wxSTC_CMD_LINESCROLLUP = 2343

wxSTC_CMD_LINETRANSPOSE = 2339

wxSTC_CMD_LINEUP = 2302

wxSTC_CMD_LINEUPEXTEND = 2303

wxSTC_CMD_LOWERCASE = 2340

wxSTC_CMD_NEWLINE = 2329

wxSTC_CMD_PAGEDOWN = 2322

wxSTC_CMD_PAGEDOWNEXTEND = 2323

wxSTC_CMD_PAGEUP = 2320

wxSTC_CMD_PAGEUPEXTEND = 2321

wxSTC_CMD_PASTE = 2179

wxSTC_CMD_REDO = 2011

wxSTC_CMD_SELECTALL = 2013

wxSTC_CMD_TAB = 2327

wxSTC_CMD_UNDO = 2176

wxSTC_CMD_UPPERCASE = 2341

wxSTC_CMD_VCHOME = 2331

wxSTC_CMD_VCHOMEEXTEND = 2332

wxSTC_CMD_WORDLEFT = 2308

wxSTC_CMD_WORDLEFTEXTEND = 2309

wxSTC_CMD_WORDRIGHT = 2310

wxSTC_CMD_WORDRIGHTEXTEND = 2311

wxSTC_CMD_ZOOMIN = 2333

wxSTC_CMD_ZOOMOUT = 2334

wxSTC_CONF_COMMENT = 1

wxSTC_CONF_DEFAULT = 0

wxSTC_CONF_DIRECTIVE = 9

wxSTC_CONF_EXTENSION = 4

wxSTC_CONF_IDENTIFIER = 3

wxSTC_CONF_IP = 8

wxSTC_CONF_NUMBER = 2

wxSTC_CONF_OPERATOR = 7

wxSTC_CONF_PARAMETER = 5

wxSTC_CONF_STRING = 6

wxSTC_CP_UTF8 = 65001

wxSTC_CURSORNORMAL = -1

wxSTC_CURSORWAIT = 3

wxSTC_DIFF_ADDED = 6

wxSTC_DIFF_COMMAND = 2

wxSTC_DIFF_COMMENT = 1

wxSTC_DIFF_DEFAULT = 0

wxSTC_DIFF_DELETED = 5

wxSTC_DIFF_HEADER = 3

wxSTC_DIFF_POSITION = 4

wxSTC_EDGE_BACKGROUND = 2

wxSTC_EDGE_LINE = 1

wxSTC_EDGE_NONE = 0

wxSTC_EIFFEL_CHARACTER = 5

wxSTC_EIFFEL_COMMENTLINE = 1

wxSTC_EIFFEL_DEFAULT = 0

wxSTC_EIFFEL_IDENTIFIER = 7

wxSTC_EIFFEL_NUMBER = 2

wxSTC_EIFFEL_OPERATOR = 6

wxSTC_EIFFEL_STRING = 4

wxSTC_EIFFEL_STRINGEOL = 8

wxSTC_EIFFEL_WORD = 3

wxSTC_EOL_CR = 1

wxSTC_EOL_CRLF = 0

wxSTC_EOL_LF = 2

wxSTC_ERR_BORLAND = 5

wxSTC_ERR_CMD = 4

wxSTC_ERR_CTAG = 9

wxSTC_ERR_DEFAULT = 0

wxSTC_ERR_DIFF_ADDITION = 11

wxSTC_ERR_DIFF_CHANGED = 10

wxSTC_ERR_DIFF_DELETION = 12

wxSTC_ERR_DIFF_MESSAGE = 13

wxSTC_ERR_GCC = 2

wxSTC_ERR_LUA = 8

wxSTC_ERR_MS = 3

wxSTC_ERR_NET = 7

wxSTC_ERR_PERL = 6

wxSTC_ERR_PYTHON = 1

wxSTC_FIND_MATCHCASE = 4

wxSTC_FIND_REGEXP = 0x00200000

wxSTC_FIND_WHOLEWORD = 2

wxSTC_FIND_WORDSTART = 0x00100000

wxSTC_FOLDLEVELBASE = 0x400

wxSTC_FOLDLEVELHEADERFLAG = 0x2000

wxSTC_FOLDLEVELNUMBERMASK = 0x0FFF

wxSTC_FOLDLEVELWHITEFLAG = 0x1000

wxSTC_H_ASP = 15

wxSTC_H_ASPAT = 16

wxSTC_H_ATTRIBUTE = 3

wxSTC_H_ATTRIBUTEUNKNOWN = 4

wxSTC_H_CDATA = 17

wxSTC_H_COMMENT = 9

wxSTC_H_DEFAULT = 0

wxSTC_H_DOUBLESTRING = 6

wxSTC_H_ENTITY = 10

wxSTC_H_NUMBER = 5

wxSTC_H_OTHER = 8

wxSTC_H_QUESTION = 18

wxSTC_H_SCRIPT = 14

wxSTC_H_SGML_1ST_PARAM = 23

wxSTC_H_SGML_1ST_PARAM_COMMENT = 30

wxSTC_H_SGML_BLOCK_DEFAULT = 31

wxSTC_H_SGML_COMMAND = 22

wxSTC_H_SGML_COMMENT = 29

wxSTC_H_SGML_DEFAULT = 21

wxSTC_H_SGML_DOUBLESTRING = 24

wxSTC_H_SGML_ENTITY = 28

wxSTC_H_SGML_ERROR = 26

wxSTC_H_SGML_SIMPLESTRING = 25

wxSTC_H_SGML_SPECIAL = 27

wxSTC_H_SINGLESTRING = 7

wxSTC_H_TAG = 1

wxSTC_H_TAGEND = 11

wxSTC_H_TAGUNKNOWN = 2

wxSTC_H_VALUE = 19

wxSTC_H_XCCOMMENT = 20

wxSTC_H_XMLEND = 13

wxSTC_H_XMLSTART = 12

wxSTC_HB_COMMENTLINE = 72

wxSTC_HB_DEFAULT = 71

wxSTC_HB_IDENTIFIER = 76

wxSTC_HB_NUMBER = 73

wxSTC_HB_START = 70

wxSTC_HB_STRING = 75

wxSTC_HB_STRINGEOL = 77

wxSTC_HB_WORD = 74

wxSTC_HBA_COMMENTLINE = 82

wxSTC_HBA_DEFAULT = 81

wxSTC_HBA_IDENTIFIER = 86

wxSTC_HBA_NUMBER = 83

wxSTC_HBA_START = 80

wxSTC_HBA_STRING = 85

wxSTC_HBA_STRINGEOL = 87

wxSTC_HBA_WORD = 84

wxSTC_HJ_COMMENT = 42

wxSTC_HJ_COMMENTDOC = 44

wxSTC_HJ_COMMENTLINE = 43

wxSTC_HJ_DEFAULT = 41

wxSTC_HJ_DOUBLESTRING = 48

wxSTC_HJ_KEYWORD = 47

wxSTC_HJ_NUMBER = 45

wxSTC_HJ_REGEX = 52

wxSTC_HJ_SINGLESTRING = 49

wxSTC_HJ_START = 40

wxSTC_HJ_STRINGEOL = 51

wxSTC_HJ_SYMBOLS = 50

wxSTC_HJ_WORD = 46

wxSTC_HJA_COMMENT = 57

wxSTC_HJA_COMMENTDOC = 59

wxSTC_HJA_COMMENTLINE = 58

wxSTC_HJA_DEFAULT = 56

wxSTC_HJA_DOUBLESTRING = 63

wxSTC_HJA_KEYWORD = 62

wxSTC_HJA_NUMBER = 60

wxSTC_HJA_REGEX = 67

wxSTC_HJA_SINGLESTRING = 64

wxSTC_HJA_START = 55

wxSTC_HJA_STRINGEOL = 66

wxSTC_HJA_SYMBOLS = 65

wxSTC_HJA_WORD = 61

wxSTC_HP_CHARACTER = 95

wxSTC_HP_CLASSNAME = 99

wxSTC_HP_COMMENTLINE = 92

wxSTC_HP_DEFAULT = 91

wxSTC_HP_DEFNAME = 100

wxSTC_HP_IDENTIFIER = 102

wxSTC_HP_NUMBER = 93

wxSTC_HP_OPERATOR = 101

wxSTC_HP_START = 90

wxSTC_HP_STRING = 94

wxSTC_HP_TRIPLE = 97

wxSTC_HP_TRIPLEDOUBLE = 98

wxSTC_HP_WORD = 96

wxSTC_HPA_CHARACTER = 110

wxSTC_HPA_CLASSNAME = 114

wxSTC_HPA_COMMENTLINE = 107

wxSTC_HPA_DEFAULT = 106

wxSTC_HPA_DEFNAME = 115

wxSTC_HPA_IDENTIFIER = 117

wxSTC_HPA_NUMBER = 108

wxSTC_HPA_OPERATOR = 116

wxSTC_HPA_START = 105

wxSTC_HPA_STRING = 109

wxSTC_HPA_TRIPLE = 112

wxSTC_HPA_TRIPLEDOUBLE = 113

wxSTC_HPA_WORD = 111

wxSTC_HPHP_COMMENT = 124

wxSTC_HPHP_COMMENTLINE = 125

wxSTC_HPHP_DEFAULT = 118

wxSTC_HPHP_HSTRING = 119

wxSTC_HPHP_HSTRING_VARIABLE = 126

wxSTC_HPHP_NUMBER = 122

wxSTC_HPHP_OPERATOR = 127

wxSTC_HPHP_SIMPLESTRING = 120

wxSTC_HPHP_VARIABLE = 123

wxSTC_HPHP_WORD = 121

wxSTC_INDIC_DIAGONAL = 3

wxSTC_INDIC_MAX = 7

wxSTC_INDIC_PLAIN = 0

wxSTC_INDIC_SQUIGGLE = 1

wxSTC_INDIC_STRIKE = 4

wxSTC_INDIC_TT = 2

wxSTC_INDIC0_MASK = 0x20

wxSTC_INDIC1_MASK = 0x40

wxSTC_INDIC2_MASK = 0x80

wxSTC_INDICS_MASK = 0xE0

wxSTC_INVALID_POSITION = -1

wxSTC_KEY_ADD = 310

wxSTC_KEY_BACK = 8

wxSTC_KEY_DELETE = 308

wxSTC_KEY_DIVIDE = 312

wxSTC_KEY_DOWN = 300

wxSTC_KEY_END = 305

wxSTC_KEY_ESCAPE = 7

wxSTC_KEY_HOME = 304

wxSTC_KEY_INSERT = 309

wxSTC_KEY_LEFT = 302

wxSTC_KEY_NEXT = 307

wxSTC_KEY_PRIOR = 306

wxSTC_KEY_RETURN = 13

wxSTC_KEY_RIGHT = 303

wxSTC_KEY_SUBTRACT = 311

wxSTC_KEY_TAB = 9

wxSTC_KEY_UP = 301

wxSTC_L_COMMAND = 1

wxSTC_L_COMMENT = 4

wxSTC_L_DEFAULT = 0

wxSTC_L_MATH = 3

wxSTC_L_TAG = 2

wxSTC_LASTSTEPINUNDOREDO = 0x100

wxSTC_LEX_ADA = 20

wxSTC_LEX_ASP = 29

wxSTC_LEX_AUTOMATIC = 1000

wxSTC_LEX_AVE = 19

wxSTC_LEX_BAAN = 31

wxSTC_LEX_BATCH = 12

wxSTC_LEX_BULLANT = 27

wxSTC_LEX_CONF = 17

wxSTC_LEX_CONTAINER = 0

wxSTC_LEX_CPP = 3

wxSTC_LEX_DIFF = 16

wxSTC_LEX_EIFFEL = 23

wxSTC_LEX_EIFFELKW = 24

wxSTC_LEX_ERRORLIST = 10

wxSTC_LEX_HTML = 4

wxSTC_LEX_LATEX = 14

wxSTC_LEX_LISP = 21

wxSTC_LEX_LUA = 15

wxSTC_LEX_MAKEFILE = 11

wxSTC_LEX_MATLAB = 32

wxSTC_LEX_NNCRONTAB = 26

wxSTC_LEX_NULL = 1

wxSTC_LEX_PASCAL = 18

wxSTC_LEX_PERL = 6

wxSTC_LEX_PHP = 30

wxSTC_LEX_PROPERTIES = 9

wxSTC_LEX_PYTHON = 2

wxSTC_LEX_RUBY = 22

wxSTC_LEX_SCRIPTOL = 33

wxSTC_LEX_SQL = 7

wxSTC_LEX_TCL = 25

wxSTC_LEX_VB = 8

wxSTC_LEX_VBSCRIPT = 28

wxSTC_LEX_XCODE = 13

wxSTC_LEX_XML = 5

wxSTC_LEXER_START = 4000

wxSTC_LISP_COMMENT = 1

wxSTC_LISP_DEFAULT = 0

wxSTC_LISP_IDENTIFIER = 9

wxSTC_LISP_KEYWORD = 3

wxSTC_LISP_NUMBER = 2

wxSTC_LISP_OPERATOR = 10

wxSTC_LISP_STRING = 6

wxSTC_LISP_STRINGEOL = 8

wxSTC_LUA_CHARACTER = 7

wxSTC_LUA_COMMENT = 1

wxSTC_LUA_COMMENTDOC = 3

wxSTC_LUA_COMMENTLINE = 2

wxSTC_LUA_DEFAULT = 0

wxSTC_LUA_IDENTIFIER = 11

wxSTC_LUA_LITERALSTRING = 8

wxSTC_LUA_NUMBER = 4

wxSTC_LUA_OPERATOR = 10

wxSTC_LUA_PREPROCESSOR = 9

wxSTC_LUA_STRING = 6

wxSTC_LUA_STRINGEOL = 12

wxSTC_LUA_WORD = 5

wxSTC_LUA_WORD2 = 13

wxSTC_LUA_WORD3 = 14

wxSTC_LUA_WORD4 = 15

wxSTC_LUA_WORD5 = 16

wxSTC_LUA_WORD6 = 17

wxSTC_MAKE_COMMENT = 1

wxSTC_MAKE_DEFAULT = 0

wxSTC_MAKE_IDENTIFIER = 3

wxSTC_MAKE_IDEOL = 9

wxSTC_MAKE_OPERATOR = 4

wxSTC_MAKE_PREPROCESSOR = 2

wxSTC_MAKE_TARGET = 5

wxSTC_MARGIN_NUMBER = 1

wxSTC_MARGIN_SYMBOL = 0

wxSTC_MARK_ARROW = 2

wxSTC_MARK_ARROWDOWN = 6

wxSTC_MARK_ARROWS = 24

wxSTC_MARK_BACKGROUND = 22

wxSTC_MARK_BOXMINUS = 14

wxSTC_MARK_BOXMINUSCONNECTED = 15

wxSTC_MARK_BOXPLUS = 12

wxSTC_MARK_BOXPLUSCONNECTED = 13

wxSTC_MARK_CHARACTER = 10000

wxSTC_MARK_CIRCLE = 0

wxSTC_MARK_CIRCLEMINUS = 20

wxSTC_MARK_CIRCLEMINUSCONNECTED = 21

wxSTC_MARK_CIRCLEPLUS = 18

wxSTC_MARK_CIRCLEPLUSCONNECTED = 19

wxSTC_MARK_DOTDOTDOT = 23

wxSTC_MARK_EMPTY = 5

wxSTC_MARK_LCORNER = 10

wxSTC_MARK_LCORNERCURVE = 16

wxSTC_MARK_MINUS = 7

wxSTC_MARK_PLUS = 8

wxSTC_MARK_ROUNDRECT = 1

wxSTC_MARK_SHORTARROW = 4

wxSTC_MARK_SMALLRECT = 3

wxSTC_MARK_TCORNER = 11

wxSTC_MARK_TCORNERCURVE = 17

wxSTC_MARK_VLINE = 9

wxSTC_MARKER_MAX = 31

wxSTC_MARKNUM_FOLDER = 30

wxSTC_MARKNUM_FOLDEREND = 25

wxSTC_MARKNUM_FOLDERMIDTAIL = 27

wxSTC_MARKNUM_FOLDEROPEN = 31

wxSTC_MARKNUM_FOLDEROPENMID = 26

wxSTC_MARKNUM_FOLDERSUB = 29

wxSTC_MARKNUM_FOLDERTAIL = 28

wxSTC_MASK_FOLDERS = 0xFE000000

wxSTC_MATLAB_COMMAND = 2

wxSTC_MATLAB_COMMENT = 1

wxSTC_MATLAB_DEFAULT = 0

wxSTC_MATLAB_IDENTIFIER = 7

wxSTC_MATLAB_KEYWORD = 4

wxSTC_MATLAB_NUMBER = 3

wxSTC_MATLAB_OPERATOR = 6

wxSTC_MATLAB_STRING = 5

wxSTC_MOD_BEFOREDELETE = 0x800

wxSTC_MOD_BEFOREINSERT = 0x400

wxSTC_MOD_CHANGEFOLD = 0x8

wxSTC_MOD_CHANGEMARKER = 0x200

wxSTC_MOD_CHANGESTYLE = 0x4

wxSTC_MOD_DELETETEXT = 0x2

wxSTC_MOD_INSERTTEXT = 0x1

wxSTC_MODEVENTMASKALL = 0xF77

wxSTC_NNCRONTAB_ASTERISK = 6

wxSTC_NNCRONTAB_COMMENT = 1

wxSTC_NNCRONTAB_DEFAULT = 0

wxSTC_NNCRONTAB_ENVIRONMENT = 9

wxSTC_NNCRONTAB_IDENTIFIER = 10

wxSTC_NNCRONTAB_KEYWORD = 4

wxSTC_NNCRONTAB_MODIFIER = 5

wxSTC_NNCRONTAB_NUMBER = 7

wxSTC_NNCRONTAB_SECTION = 3

wxSTC_NNCRONTAB_STRING = 8

wxSTC_NNCRONTAB_TASK = 2

wxSTC_OPTIONAL_START = 3000

wxSTC_P_CHARACTER = 4

wxSTC_P_CLASSNAME = 8

wxSTC_P_COMMENTBLOCK = 12

wxSTC_P_COMMENTLINE = 1

wxSTC_P_DEFAULT = 0

wxSTC_P_DEFNAME = 9

wxSTC_P_IDENTIFIER = 11

wxSTC_P_NUMBER = 2

wxSTC_P_OPERATOR = 10

wxSTC_P_STRING = 3

wxSTC_P_STRINGEOL = 13

wxSTC_P_TRIPLE = 6

wxSTC_P_TRIPLEDOUBLE = 7

wxSTC_P_WORD = 5

wxSTC_PERFORMED_REDO = 0x40

wxSTC_PERFORMED_UNDO = 0x20

wxSTC_PERFORMED_USER = 0x10

wxSTC_PL_ARRAY = 13

wxSTC_PL_BACKTICKS = 20

wxSTC_PL_CHARACTER = 7

wxSTC_PL_COMMENTLINE = 2

wxSTC_PL_DATASECTION = 21

wxSTC_PL_DEFAULT = 0

wxSTC_PL_ERROR = 1

wxSTC_PL_HASH = 14

wxSTC_PL_HERE_DELIM = 22

wxSTC_PL_HERE_Q = 23

wxSTC_PL_HERE_QQ = 24

wxSTC_PL_HERE_QX = 25

wxSTC_PL_IDENTIFIER = 11

wxSTC_PL_LONGQUOTE = 19

wxSTC_PL_NUMBER = 4

wxSTC_PL_OPERATOR = 10

wxSTC_PL_POD = 3

wxSTC_PL_PREPROCESSOR = 9

wxSTC_PL_PUNCTUATION = 8

wxSTC_PL_REGEX = 17

wxSTC_PL_REGSUBST = 18

wxSTC_PL_SCALAR = 12

wxSTC_PL_STRING = 6

wxSTC_PL_STRING_Q = 26

wxSTC_PL_STRING_QQ = 27

wxSTC_PL_STRING_QR = 29

wxSTC_PL_STRING_QW = 30

wxSTC_PL_STRING_QX = 28

wxSTC_PL_SYMBOLTABLE = 15

wxSTC_PL_WORD = 5

wxSTC_PRINT_BLACKONWHITE = 2

wxSTC_PRINT_COLOURONWHITE = 3

wxSTC_PRINT_COLOURONWHITEDEFAULTBG = 4

wxSTC_PRINT_INVERTLIGHT = 1

wxSTC_PRINT_NORMAL = 0

wxSTC_PROPS_ASSIGNMENT = 3

wxSTC_PROPS_COMMENT = 1

wxSTC_PROPS_DEFAULT = 0

wxSTC_PROPS_DEFVAL = 4

wxSTC_PROPS_SECTION = 2

wxSTC_SCMOD_ALT = 4

wxSTC_SCMOD_CTRL = 2

wxSTC_SCMOD_SHIFT = 1

wxSTC_SCRIPTOL_CHARACTER = 7

wxSTC_SCRIPTOL_COMMENT = 1

wxSTC_SCRIPTOL_COMMENTBASIC = 19

wxSTC_SCRIPTOL_COMMENTDOC = 3

wxSTC_SCRIPTOL_COMMENTDOCKEYWORD = 17

wxSTC_SCRIPTOL_COMMENTDOCKEYWORDERROR = 18

wxSTC_SCRIPTOL_COMMENTLINE = 2

wxSTC_SCRIPTOL_COMMENTLINEDOC = 15

wxSTC_SCRIPTOL_DEFAULT = 0

wxSTC_SCRIPTOL_IDENTIFIER = 11

wxSTC_SCRIPTOL_NUMBER = 4

wxSTC_SCRIPTOL_OPERATOR = 10

wxSTC_SCRIPTOL_PREPROCESSOR = 9

wxSTC_SCRIPTOL_REGEX = 14

wxSTC_SCRIPTOL_STRING = 6

wxSTC_SCRIPTOL_STRINGEOL = 12

wxSTC_SCRIPTOL_UUID = 8

wxSTC_SCRIPTOL_VERBATIM = 13

wxSTC_SCRIPTOL_WORD = 5

wxSTC_SCRIPTOL_WORD2 = 16

wxSTC_START = 2000

wxSTC_STYLE_BRACEBAD = 35

wxSTC_STYLE_BRACELIGHT = 34

wxSTC_STYLE_CONTROLCHAR = 36

wxSTC_STYLE_DEFAULT = 32

wxSTC_STYLE_INDENTGUIDE = 37

wxSTC_STYLE_LASTPREDEFINED = 39

wxSTC_STYLE_LINENUMBER = 33

wxSTC_STYLE_MAX = 127

wxSTC_TIME_FOREVER = 10000000

wxSTC_USE_POPUP = 1

wxSTC_VISIBLE_SLOP = 0x01

wxSTC_VISIBLE_STRICT = 0x04

wxSTC_WRAP_NONE = 0

wxSTC_WRAP_WORD = 1

wxSTC_WS_INVISIBLE = 0

wxSTC_WS_VISIBLEAFTERINDENT = 2

wxSTC_WS_VISIBLEALWAYS = 1

wxSTCNameStr = "wxSTCNameStr"

=cut

#Pod::HTML2Pod conversion notes:
# 21302 bytes of input
#Mon Jun 20 17:30:07 2011 
# No a_name switch not specified, so will not try to render <a name='...'>
# No a_href switch not specified, so will not try to render <a href='...'>
