=pod

PyFrame Guide to wxPython

Copyright and License information Home

__ A B C D E F G H I L M P R S T U V W

=head1 wxStyledTextCtrl - Zooming

=over

=item * GetZoom

=item * SetZoom

=back

B<Summary>:

These two commands can be used to set and retrieve the zoom factor,
which allows the text size to be made larger and/or smaller. The zoom
factors may range from -10 to +20 and are added to each style's point
size (which will never be less than 2).

Note that the Scintilla documentation has ZOOMOUT and ZOOMIN commands.
These are normally bound to CTRL+SUBTRACT and CTRL+ADD, respectively.
Furthermore, that mapping sets CTRL+DIVIDE to execute SETZOOM(0), which
resets the zooming to zero (none). You can execute these
programmatically using wxSTC_CMD_ZOOMIN or wxSTC_CMD_ZOOMOUT as the
input parameter to CmdKeyExecute.

----

B<GetZoom()>

Returns an integer with the zoom factor.

top

----

B<SetZoom(zoom)>

Sets the zoom factor to the value of the integer parameter zoom. The
acceptable range is -10 through +20. Returns None.

top

----

=cut

#Pod::HTML2Pod conversion notes:
# 2996 bytes of input
#Mon Jun 20 17:30:09 2011 
# No a_name switch not specified, so will not try to render <a name='...'>
# No a_href switch not specified, so will not try to render <a href='...'>
