#!/usr/bin/perl 

use strict;
use warnings;

$| = 1;

unless ( $^O eq 'MSWin32' ) {
	exit 0 if fork();
}

require threads;
require threads::shared;

$ENV{PADRE_PAR_PATH} = $ENV{PAR_TEMP}||'';

require Padre;
my $app = Padre->new;
$app->run;
