package Padre::Plugin::Debug::FBP::DebugVariable;

## no critic

# This module was generated by Padre::Plugin::FormBuilder::Perl.
# To change this module edit the original .fbp file and regenerate.
# DO NOT MODIFY THIS FILE BY HAND!

use 5.008;
use strict;
use warnings;
use Padre::Wx ();
use Padre::Wx::Role::Main ();

our $VERSION = '0.13';
our @ISA     = qw{
	Padre::Wx::Role::Main
	Wx::Panel
};

sub new {
	my $class  = shift;
	my $parent = shift;

	my $self = $class->SUPER::new(
		$parent,
		-1,
		Wx::DefaultPosition(),
		[ 195, 530 ],
		Wx::TAB_TRAVERSAL(),
	);

	$self->{refresh} = Wx::BitmapButton->new(
		$self,
		-1,
		Wx::NullBitmap(),
		Wx::DefaultPosition(),
		Wx::DefaultSize(),
		Wx::BU_AUTODRAW(),
	);
	$self->{refresh}->SetToolTip(
		Wx::gettext("Refresh List")
	);

	Wx::Event::EVT_BUTTON(
		$self,
		$self->{refresh},
		sub {
			shift->on_refresh_click(@_);
		},
	);

	$self->{variables} = Wx::ListCtrl->new(
		$self,
		-1,
		Wx::DefaultPosition(),
		Wx::DefaultSize(),
		Wx::LC_REPORT() | Wx::LC_SINGLE_SEL(),
	);
	$self->{variables}->SetMinSize( Wx::DefaultSize() );

	$self->{show_local_variables} = Wx::CheckBox->new(
		$self,
		-1,
		Wx::gettext("Show Local Variables (y 0)"),
		Wx::DefaultPosition(),
		Wx::DefaultSize(),
	);
	$self->{show_local_variables}->SetToolTip(
		Wx::gettext("y [level [vars]]\nDisplay all (or some) lexical variables (mnemonic: mY variables) in the current scope or level scopes higher. You can limit the variables that you see with vars which works exactly as it does for the V and X commands. Requires the PadWalker module version 0.08 or higher; will warn if this isn't installed. Output is pretty-printed in the same style as for V and the format is controlled by the same options.")
	);

	Wx::Event::EVT_CHECKBOX(
		$self,
		$self->{show_local_variables},
		sub {
			shift->show_local_variables_checked(@_);
		},
	);

	$self->{show_global_variables} = Wx::CheckBox->new(
		$self,
		-1,
		Wx::gettext("Show Global Variables"),
		Wx::DefaultPosition(),
		Wx::DefaultSize(),
	);
	$self->{show_global_variables}->SetToolTip(
		Wx::gettext("Intermitent Error, You can't FIRSTKEY with the %~ hash")
	);

	Wx::Event::EVT_CHECKBOX(
		$self,
		$self->{show_global_variables},
		sub {
			shift->show_global_variables_checked(@_);
		},
	);

	my $button_sizer = Wx::BoxSizer->new(Wx::HORIZONTAL());
	$button_sizer->Add( $self->{refresh}, 0, Wx::ALL(), 1 );

	my $checkbox_sizer = Wx::StaticBoxSizer->new(
		Wx::StaticBox->new(
			$self,
			-1,
			Wx::gettext("Show"),
		),
		Wx::VERTICAL(),
	);
	$checkbox_sizer->Add( $self->{show_local_variables}, 0, Wx::ALL(), 2 );
	$checkbox_sizer->Add( $self->{show_global_variables}, 0, Wx::ALL(), 5 );

	my $bSizer10 = Wx::BoxSizer->new(Wx::VERTICAL());
	$bSizer10->Add( $button_sizer, 0, Wx::EXPAND(), 5 );
	$bSizer10->Add( $self->{variables}, 1, Wx::ALL() | Wx::EXPAND(), 5 );
	$bSizer10->Add( $checkbox_sizer, 0, Wx::EXPAND(), 5 );

	$self->SetSizer($bSizer10);
	$self->Layout;

	return $self;
}

sub on_refresh_click {
	$_[0]->main->error('Handler method on_refresh_click for event refresh.OnButtonClick not implemented');
}

sub show_local_variables_checked {
	$_[0]->main->error('Handler method show_local_variables_checked for event show_local_variables.OnCheckBox not implemented');
}

sub show_global_variables_checked {
	$_[0]->main->error('Handler method show_global_variables_checked for event show_global_variables.OnCheckBox not implemented');
}

1;

# Copyright 2008-2011 The Padre development team as listed in Padre.pm.
# LICENSE
# This program is free software; you can redistribute it and/or
# modify it under the same terms as Perl 5 itself.

