package Padre::Plugin::Debug::FBP::MainFB;

## no critic

# This module was generated by Padre::Plugin::FormBuilder::Perl.
# To change this module edit the original .fbp file and regenerate.
# DO NOT MODIFY THIS FILE BY HAND!

use 5.008;
use strict;
use warnings;
use Padre::Wx ();
use Padre::Wx::Role::Main ();

our $VERSION = '0.01';
our @ISA     = qw{
	Padre::Wx::Role::Main
	Wx::Dialog
};

sub new {
	my $class  = shift;
	my $parent = shift;

	my $self = $class->SUPER::new(
		$parent,
		-1,
		Wx::gettext("Debug Simulator"),
		Wx::DefaultPosition,
		Wx::DefaultSize,
		Wx::DEFAULT_DIALOG_STYLE | Wx::RESIZE_BORDER,
	);

	$self->{debug_bottom} = Wx::CheckBox->new(
		$self,
		-1,
		Wx::gettext("Debug Bottom"),
		Wx::DefaultPosition,
		Wx::DefaultSize,
	);

	Wx::Event::EVT_CHECKBOX(
		$self,
		$self->{debug_bottom},
		sub {
			shift->on_debug_bottom_clicked(@_);
		},
	);

	$self->{m_checkBox2} = Wx::CheckBox->new(
		$self,
		-1,
		Wx::gettext("Breakpoints"),
		Wx::DefaultPosition,
		Wx::DefaultSize,
	);

	Wx::Event::EVT_CHECKBOX(
		$self,
		$self->{m_checkBox2},
		sub {
			shift->on_breakpoints_clicked(@_);
		},
	);

	$self->{m_checkBox3} = Wx::CheckBox->new(
		$self,
		-1,
		Wx::gettext("Variables"),
		Wx::DefaultPosition,
		Wx::DefaultSize,
	);

	$self->{m_staticText3} = Wx::StaticText->new(
		$self,
		-1,
		Wx::gettext("Line #"),
	);

	$self->{bp_line_number} = Wx::TextCtrl->new(
		$self,
		-1,
		"",
		Wx::DefaultPosition,
		Wx::DefaultSize,
	);

	$self->{breakpoint_button} = Wx::Button->new(
		$self,
		-1,
		Wx::gettext("Breakpoint"),
		Wx::DefaultPosition,
		Wx::DefaultSize,
	);

	Wx::Event::EVT_BUTTON(
		$self,
		$self->{breakpoint_button},
		sub {
			shift->breakpoint_clicked(@_);
		},
	);

	$self->{m_staticText2} = Wx::StaticText->new(
		$self,
		-1,
		Wx::gettext("MyLabel"),
	);

	my $close_button = Wx::Button->new(
		$self,
		Wx::ID_CANCEL,
		Wx::gettext("Close"),
		Wx::DefaultPosition,
		Wx::DefaultSize,
	);
	$close_button->SetDefault;

	$self->{m_staticline5} = Wx::StaticLine->new(
		$self,
		-1,
		Wx::DefaultPosition,
		Wx::DefaultSize,
		Wx::LI_HORIZONTAL,
	);

	my $file_1 = Wx::StaticBoxSizer->new(
		Wx::StaticBox->new(
			$self,
			-1,
			Wx::gettext("View -> Show Debug"),
		),
		Wx::HORIZONTAL,
	);
	$file_1->Add( $self->{debug_bottom}, 0, Wx::ALL, 5 );
	$file_1->Add( $self->{m_checkBox2}, 0, Wx::ALL, 5 );
	$file_1->Add( $self->{m_checkBox3}, 0, Wx::ALL, 5 );

	my $sbSizer2 = Wx::StaticBoxSizer->new(
		Wx::StaticBox->new(
			$self,
			-1,
			Wx::gettext("Breakpoint Simulation"),
		),
		Wx::HORIZONTAL,
	);
	$sbSizer2->Add( $self->{m_staticText3}, 0, Wx::ALL, 5 );
	$sbSizer2->Add( $self->{bp_line_number}, 0, Wx::ALL, 5 );
	$sbSizer2->Add( 0, 0, 1, Wx::EXPAND, 5 );
	$sbSizer2->Add( $self->{breakpoint_button}, 0, Wx::ALL, 5 );

	my $file_2 = Wx::StaticBoxSizer->new(
		Wx::StaticBox->new(
			$self,
			-1,
			Wx::gettext("File-2"),
		),
		Wx::VERTICAL,
	);
	$file_2->Add( $self->{m_staticText2}, 0, Wx::ALL, 5 );

	my $buttons = Wx::BoxSizer->new(Wx::HORIZONTAL);
	$buttons->Add( 0, 0, 1, Wx::EXPAND, 5 );
	$buttons->Add( $close_button, 0, Wx::ALL, 5 );

	my $vsizer = Wx::BoxSizer->new(Wx::VERTICAL);
	$vsizer->Add( $file_1, 0, Wx::EXPAND, 5 );
	$vsizer->Add( $sbSizer2, 1, Wx::EXPAND, 5 );
	$vsizer->Add( $file_2, 0, Wx::EXPAND, 5 );
	$vsizer->Add( $buttons, 0, Wx::EXPAND, 3 );
	$vsizer->Add( $self->{m_staticline5}, 0, Wx::EXPAND | Wx::ALL, 5 );

	my $sizer = Wx::BoxSizer->new(Wx::HORIZONTAL);
	$sizer->Add( $vsizer, 0, Wx::ALL, 1 );

	$self->SetSizerAndFit($sizer);
	$self->Layout;

	return $self;
}

sub bp_line_number {
	$_[0]->{bp_line_number};
}

sub on_debug_bottom_clicked {
	$_[0]->main->error('Handler method on_debug_bottom_clicked for event debug_bottom.OnCheckBox not implemented');
}

sub on_breakpoints_clicked {
	$_[0]->main->error('Handler method on_breakpoints_clicked for event m_checkBox2.OnCheckBox not implemented');
}

sub breakpoint_clicked {
	$_[0]->main->error('Handler method breakpoint_clicked for event breakpoint_button.OnButtonClick not implemented');
}

1;

# Copyright 2008-2011 The Padre development team as listed in Padre.pm.
# LICENSE
# This program is free software; you can redistribute it and/or
# modify it under the same terms as Perl 5 itself.

