#!/usr/bin/perl -w -- 
# generated by wxGlade 0.6.3
# To get wxPerl visit http://wxPerl.sourceforge.net/

use Wx 0.15 qw[:allclasses];
use strict;

package MyDialog1;

use Wx qw[:everything];
use base qw(Wx::Dialog);
use strict;

sub new {
	my( $self, $parent, $id, $title, $pos, $size, $style, $name ) = @_;
	$parent = undef              unless defined $parent;
	$id     = -1                 unless defined $id;
	$title  = ""                 unless defined $title;
	$pos    = wxDefaultPosition  unless defined $pos;
	$size   = wxDefaultSize      unless defined $size;
	$name   = ""                 unless defined $name;

# begin wxGlade: MyDialog1::new

	$style = wxDEFAULT_DIALOG_STYLE 
		unless defined $style;

	$self = $self->SUPER::new( $parent, $id, $title, $pos, $size, $style, $name );
	$self->{find_label} = Wx::StaticText->new($self, -1, "Find Text:", wxDefaultPosition, wxDefaultSize, );
	$self->{find_text} = Wx::ComboBox->new($self, -1, "", wxDefaultPosition, wxDefaultSize, [], wxCB_DROPDOWN);
	$self->{find_regex} = Wx::CheckBox->new($self, -1, "Regular Expression", wxDefaultPosition, wxDefaultSize, );
	$self->{find_reverse} = Wx::CheckBox->new($self, -1, "Search Backwards", wxDefaultPosition, wxDefaultSize, );
	$self->{find_case} = Wx::CheckBox->new($self, -1, "Case Insensitive", wxDefaultPosition, wxDefaultSize, );
	$self->{find_first} = Wx::CheckBox->new($self, -1, "Close Window on Hit", wxDefaultPosition, wxDefaultSize, );
	$self->{line_2} = Wx::StaticLine->new($self, -1, wxDefaultPosition, wxDefaultSize, );
	$self->{button_find} = Wx::Button->new($self, -1, "Find Next");
	$self->{button_count} = Wx::Button->new($self, -1, "Count All");
	$self->{button_cancel} = Wx::Button->new($self, wxID_CANCEL, "");

	$self->__set_properties();
	$self->__do_layout();

# end wxGlade
	return $self;

}


sub __set_properties {
	my $self = shift;

# begin wxGlade: MyDialog1::__set_properties

	$self->SetTitle("dialog_find");
	$self->{find_text}->SetSelection(-1);

# end wxGlade
}

sub __do_layout {
	my $self = shift;

# begin wxGlade: MyDialog1::__do_layout

	$self->{sizer_1} = Wx::BoxSizer->new(wxHORIZONTAL);
	$self->{sizer_2} = Wx::BoxSizer->new(wxVERTICAL);
	$self->{button_sizer} = Wx::BoxSizer->new(wxHORIZONTAL);
	$self->{option_sizer} = Wx::GridSizer->new(2, 2, 5, 5);
	$self->{sizer_2}->Add($self->{find_label}, 0, 0, 0);
	$self->{sizer_2}->Add($self->{find_text}, 0, wxTOP|wxEXPAND, 5);
	my $line_1 = Wx::StaticLine->new($self, -1, wxDefaultPosition, wxDefaultSize, );
	$self->{sizer_2}->Add($line_1, 0, wxTOP|wxBOTTOM|wxEXPAND, 5);
	$self->{option_sizer}->Add($self->{find_regex}, 0, 0, 0);
	$self->{option_sizer}->Add($self->{find_reverse}, 0, 0, 0);
	$self->{option_sizer}->Add($self->{find_case}, 0, 0, 0);
	$self->{option_sizer}->Add($self->{find_first}, 0, 0, 0);
	$self->{sizer_2}->Add($self->{option_sizer}, 1, wxTOP|wxBOTTOM|wxEXPAND, 5);
	$self->{sizer_2}->Add($self->{line_2}, 0, wxTOP|wxBOTTOM|wxEXPAND, 5);
	$self->{button_sizer}->Add($self->{button_find}, 1, 0, 0);
	$self->{button_sizer}->Add($self->{button_count}, 1, wxLEFT|wxRIGHT, 5);
	$self->{button_sizer}->Add($self->{button_cancel}, 1, 0, 0);
	$self->{sizer_2}->Add($self->{button_sizer}, 0, 0, 0);
	$self->{sizer_1}->Add($self->{sizer_2}, 1, wxALL|wxEXPAND, 5);
	$self->SetSizer($self->{sizer_1});
	$self->{sizer_1}->Fit($self);
	$self->Layout();

# end wxGlade
}

# end of class MyDialog1

1;

package MyDialog2;

use Wx qw[:everything];
use base qw(Wx::Dialog);
use strict;

sub new {
	my( $self, $parent, $id, $title, $pos, $size, $style, $name ) = @_;
	$parent = undef              unless defined $parent;
	$id     = -1                 unless defined $id;
	$title  = ""                 unless defined $title;
	$pos    = wxDefaultPosition  unless defined $pos;
	$size   = wxDefaultSize      unless defined $size;
	$name   = ""                 unless defined $name;

# begin wxGlade: MyDialog2::new

	$style = wxDEFAULT_DIALOG_STYLE 
		unless defined $style;

	$self = $self->SUPER::new( $parent, $id, $title, $pos, $size, $style, $name );
	$self->{find_label} = Wx::StaticText->new($self, -1, "Find Text:", wxDefaultPosition, wxDefaultSize, );
	$self->{find_text} = Wx::ComboBox->new($self, -1, "", wxDefaultPosition, wxDefaultSize, [], wxCB_DROPDOWN);
	$self->{replace_label} = Wx::StaticText->new($self, -1, "Replace Text:", wxDefaultPosition, wxDefaultSize, );
	$self->{replace_text} = Wx::ComboBox->new($self, -1, "", wxDefaultPosition, wxDefaultSize, [], wxCB_DROPDOWN);
	$self->{line_1} = Wx::StaticLine->new($self, -1, wxDefaultPosition, wxDefaultSize, );
	$self->{find_regex} = Wx::CheckBox->new($self, -1, "Regular Expression", wxDefaultPosition, wxDefaultSize, );
	$self->{find_reverse} = Wx::CheckBox->new($self, -1, "Search Backwards", wxDefaultPosition, wxDefaultSize, );
	$self->{find_case} = Wx::CheckBox->new($self, -1, "Case Insensitive", wxDefaultPosition, wxDefaultSize, );
	$self->{replace_all} = Wx::CheckBox->new($self, -1, "Replace All", wxDefaultPosition, wxDefaultSize, );
	$self->{line_2} = Wx::StaticLine->new($self, -1, wxDefaultPosition, wxDefaultSize, );
	$self->{button_find} = Wx::Button->new($self, -1, "Find Next");
	$self->{button_replace} = Wx::Button->new($self, -1, "Replace");
	$self->{button_cancel} = Wx::Button->new($self, wxID_CANCEL, "");

	$self->__set_properties();
	$self->__do_layout();

# end wxGlade
	return $self;

}


sub __set_properties {
	my $self = shift;

# begin wxGlade: MyDialog2::__set_properties

	$self->SetTitle("dialog_replace");
	$self->{find_text}->SetSelection(-1);
	$self->{replace_text}->SetSelection(-1);

# end wxGlade
}

sub __do_layout {
	my $self = shift;

# begin wxGlade: MyDialog2::__do_layout

	$self->{sizer_1} = Wx::BoxSizer->new(wxHORIZONTAL);
	$self->{sizer_2} = Wx::BoxSizer->new(wxVERTICAL);
	$self->{button_sizer} = Wx::BoxSizer->new(wxHORIZONTAL);
	$self->{option_sizer} = Wx::GridSizer->new(2, 2, 5, 20);
	$self->{sizer_2}->Add($self->{find_label}, 0, 0, 0);
	$self->{sizer_2}->Add($self->{find_text}, 0, wxTOP|wxEXPAND, 5);
	$self->{sizer_2}->Add($self->{replace_label}, 0, wxTOP, 10);
	$self->{sizer_2}->Add($self->{replace_text}, 0, wxTOP|wxEXPAND, 5);
	$self->{sizer_2}->Add($self->{line_1}, 0, wxTOP|wxBOTTOM|wxEXPAND, 5);
	$self->{option_sizer}->Add($self->{find_regex}, 0, 0, 0);
	$self->{option_sizer}->Add($self->{find_reverse}, 0, 0, 0);
	$self->{option_sizer}->Add($self->{find_case}, 0, 0, 0);
	$self->{option_sizer}->Add($self->{replace_all}, 0, 0, 0);
	$self->{sizer_2}->Add($self->{option_sizer}, 1, wxTOP|wxBOTTOM|wxEXPAND, 5);
	$self->{sizer_2}->Add($self->{line_2}, 0, wxTOP|wxBOTTOM|wxEXPAND, 5);
	$self->{button_sizer}->Add($self->{button_find}, 1, 0, 0);
	$self->{button_sizer}->Add($self->{button_replace}, 1, wxLEFT|wxRIGHT, 5);
	$self->{button_sizer}->Add($self->{button_cancel}, 1, 0, 0);
	$self->{sizer_2}->Add($self->{button_sizer}, 0, 0, 0);
	$self->{sizer_1}->Add($self->{sizer_2}, 1, wxALL|wxEXPAND, 5);
	$self->SetSizer($self->{sizer_1});
	$self->{sizer_1}->Fit($self);
	$self->Layout();

# end wxGlade
}

# end of class MyDialog2

1;

1;

package main;

unless(caller){
	local *Wx::App::OnInit = sub{1};
	my $app = Wx::App->new();
	Wx::InitAllImageHandlers();

	my $dialog_find = MyDialog1->new();

	$app->SetTopWindow($dialog_find);
	$dialog_find->Show(1);
	$app->MainLoop();
}
