#!/usr/bin/perl -w -- 
# generated by wxGlade 0.6.3
# To get wxPerl visit http://wxPerl.sourceforge.net/

use Wx 0.15 qw[:allclasses];
use strict;

package MyDialog1;

use Wx qw[:everything];
use base qw(Wx::Dialog);
use strict;

sub new {
	my( $self, $parent, $id, $title, $pos, $size, $style, $name ) = @_;
	$parent = undef              unless defined $parent;
	$id     = -1                 unless defined $id;
	$title  = ""                 unless defined $title;
	$pos    = wxDefaultPosition  unless defined $pos;
	$size   = wxDefaultSize      unless defined $size;
	$name   = ""                 unless defined $name;

# begin wxGlade: MyDialog1::new

	$style = wxDEFAULT_DIALOG_STYLE 
		unless defined $style;

	$self = $self->SUPER::new( $parent, $id, $title, $pos, $size, $style, $name );
	$self->{label_1} = Wx::StaticText->new($self, -1, "Find Text:", wxDefaultPosition, wxDefaultSize, );
	$self->{combo_box_1} = Wx::ComboBox->new($self, -1, "", wxDefaultPosition, wxDefaultSize, [], wxCB_DROPDOWN);
	$self->{static_line_2} = Wx::StaticLine->new($self, -1, wxDefaultPosition, wxDefaultSize, );
	$self->{checkbox_4} = Wx::CheckBox->new($self, -1, "Regular Expression", wxDefaultPosition, wxDefaultSize, );
	$self->{checkbox_6} = Wx::CheckBox->new($self, -1, "Search Backwards", wxDefaultPosition, wxDefaultSize, );
	$self->{checkbox_5} = Wx::CheckBox->new($self, -1, "Case Insensitive", wxDefaultPosition, wxDefaultSize, );
	$self->{checkbox_7} = Wx::CheckBox->new($self, -1, "Close Window on Hit", wxDefaultPosition, wxDefaultSize, );
	$self->{static_line_1} = Wx::StaticLine->new($self, -1, wxDefaultPosition, wxDefaultSize, );
	$self->{button_1} = Wx::Button->new($self, -1, "Find Next");
	$self->{button_2} = Wx::Button->new($self, -1, "Count All");
	$self->{button_3} = Wx::Button->new($self, wxID_CANCEL, "");

	$self->__set_properties();
	$self->__do_layout();

# end wxGlade
	return $self;

}


sub __set_properties {
	my $self = shift;

# begin wxGlade: MyDialog1::__set_properties

	$self->SetTitle("dialog_find");
	$self->{combo_box_1}->SetSelection(-1);

# end wxGlade
}

sub __do_layout {
	my $self = shift;

# begin wxGlade: MyDialog1::__do_layout

	$self->{sizer_1} = Wx::BoxSizer->new(wxHORIZONTAL);
	$self->{sizer_2} = Wx::BoxSizer->new(wxVERTICAL);
	$self->{sizer_3} = Wx::BoxSizer->new(wxHORIZONTAL);
	$self->{grid_sizer_1} = Wx::GridSizer->new(2, 2, 5, 5);
	$self->{sizer_2}->Add($self->{label_1}, 0, 0, 0);
	$self->{sizer_2}->Add($self->{combo_box_1}, 0, wxTOP|wxEXPAND, 5);
	$self->{sizer_2}->Add($self->{static_line_2}, 0, wxTOP|wxBOTTOM|wxEXPAND, 5);
	$self->{grid_sizer_1}->Add($self->{checkbox_4}, 0, 0, 0);
	$self->{grid_sizer_1}->Add($self->{checkbox_6}, 0, 0, 0);
	$self->{grid_sizer_1}->Add($self->{checkbox_5}, 0, 0, 0);
	$self->{grid_sizer_1}->Add($self->{checkbox_7}, 0, 0, 0);
	$self->{sizer_2}->Add($self->{grid_sizer_1}, 1, wxTOP|wxBOTTOM|wxEXPAND, 5);
	$self->{sizer_2}->Add($self->{static_line_1}, 0, wxTOP|wxBOTTOM|wxEXPAND, 5);
	$self->{sizer_3}->Add($self->{button_1}, 1, 0, 0);
	$self->{sizer_3}->Add($self->{button_2}, 1, wxLEFT|wxRIGHT, 5);
	$self->{sizer_3}->Add($self->{button_3}, 1, 0, 0);
	$self->{sizer_2}->Add($self->{sizer_3}, 0, 0, 0);
	$self->{sizer_1}->Add($self->{sizer_2}, 1, wxALL|wxEXPAND, 5);
	$self->SetSizer($self->{sizer_1});
	$self->{sizer_1}->Fit($self);
	$self->Layout();

# end wxGlade
}

# end of class MyDialog1

1;

package MyDialog2;

use Wx qw[:everything];
use base qw(Wx::Dialog);
use strict;

sub new {
	my( $self, $parent, $id, $title, $pos, $size, $style, $name ) = @_;
	$parent = undef              unless defined $parent;
	$id     = -1                 unless defined $id;
	$title  = ""                 unless defined $title;
	$pos    = wxDefaultPosition  unless defined $pos;
	$size   = wxDefaultSize      unless defined $size;
	$name   = ""                 unless defined $name;

# begin wxGlade: MyDialog2::new

	$style = wxDEFAULT_DIALOG_STYLE 
		unless defined $style;

	$self = $self->SUPER::new( $parent, $id, $title, $pos, $size, $style, $name );
	$self->{label_2} = Wx::StaticText->new($self, -1, "Find Text:", wxDefaultPosition, wxDefaultSize, );
	$self->{combo_box_2} = Wx::ComboBox->new($self, -1, "", wxDefaultPosition, wxDefaultSize, [], wxCB_DROPDOWN);
	$self->{label_3} = Wx::StaticText->new($self, -1, "Replace Text:", wxDefaultPosition, wxDefaultSize, );
	$self->{combo_box_3} = Wx::ComboBox->new($self, -1, "", wxDefaultPosition, wxDefaultSize, [], wxCB_DROPDOWN);
	$self->{static_line_3} = Wx::StaticLine->new($self, -1, wxDefaultPosition, wxDefaultSize, );
	$self->{checkbox_8} = Wx::CheckBox->new($self, -1, "Regular Expression", wxDefaultPosition, wxDefaultSize, );
	$self->{checkbox_10} = Wx::CheckBox->new($self, -1, "Search Backwards", wxDefaultPosition, wxDefaultSize, );
	$self->{checkbox_9} = Wx::CheckBox->new($self, -1, "Case Insensitive", wxDefaultPosition, wxDefaultSize, );
	$self->{checkbox_11} = Wx::CheckBox->new($self, -1, "Replace All", wxDefaultPosition, wxDefaultSize, );
	$self->{static_line_4} = Wx::StaticLine->new($self, -1, wxDefaultPosition, wxDefaultSize, );
	$self->{button_4} = Wx::Button->new($self, -1, "Find Next");
	$self->{button_6} = Wx::Button->new($self, -1, "Replace");
	$self->{button_5} = Wx::Button->new($self, wxID_CANCEL, "");

	$self->__set_properties();
	$self->__do_layout();

# end wxGlade
	return $self;

}


sub __set_properties {
	my $self = shift;

# begin wxGlade: MyDialog2::__set_properties

	$self->SetTitle("dialog_replace");
	$self->{combo_box_2}->SetSelection(-1);
	$self->{combo_box_3}->SetSelection(-1);

# end wxGlade
}

sub __do_layout {
	my $self = shift;

# begin wxGlade: MyDialog2::__do_layout

	$self->{sizer_4} = Wx::BoxSizer->new(wxHORIZONTAL);
	$self->{sizer_5} = Wx::BoxSizer->new(wxVERTICAL);
	$self->{sizer_6} = Wx::BoxSizer->new(wxHORIZONTAL);
	$self->{grid_sizer_2} = Wx::GridSizer->new(2, 2, 5, 20);
	$self->{sizer_5}->Add($self->{label_2}, 0, 0, 0);
	$self->{sizer_5}->Add($self->{combo_box_2}, 0, wxTOP|wxEXPAND, 5);
	$self->{sizer_5}->Add($self->{label_3}, 0, wxTOP, 10);
	$self->{sizer_5}->Add($self->{combo_box_3}, 0, wxTOP|wxEXPAND, 5);
	$self->{sizer_5}->Add($self->{static_line_3}, 0, wxTOP|wxBOTTOM|wxEXPAND, 5);
	$self->{grid_sizer_2}->Add($self->{checkbox_8}, 0, 0, 0);
	$self->{grid_sizer_2}->Add($self->{checkbox_10}, 0, 0, 0);
	$self->{grid_sizer_2}->Add($self->{checkbox_9}, 0, 0, 0);
	$self->{grid_sizer_2}->Add($self->{checkbox_11}, 0, 0, 0);
	$self->{sizer_5}->Add($self->{grid_sizer_2}, 1, wxTOP|wxBOTTOM|wxEXPAND, 5);
	$self->{sizer_5}->Add($self->{static_line_4}, 0, wxTOP|wxBOTTOM|wxEXPAND, 5);
	$self->{sizer_6}->Add($self->{button_4}, 1, 0, 0);
	$self->{sizer_6}->Add($self->{button_6}, 1, wxLEFT|wxRIGHT, 5);
	$self->{sizer_6}->Add($self->{button_5}, 1, 0, 0);
	$self->{sizer_5}->Add($self->{sizer_6}, 0, 0, 0);
	$self->{sizer_4}->Add($self->{sizer_5}, 1, wxALL|wxEXPAND, 5);
	$self->SetSizer($self->{sizer_4});
	$self->{sizer_4}->Fit($self);
	$self->Layout();

# end wxGlade
}

# end of class MyDialog2

1;

1;

package main;

unless(caller){
	local *Wx::App::OnInit = sub{1};
	my $app = Wx::App->new();
	Wx::InitAllImageHandlers();

	my $dialog_find = MyDialog1->new();

	$app->SetTopWindow($dialog_find);
	$dialog_find->Show(1);
	$app->MainLoop();
}
