#!/usr/bin/perl -w -- 
# generated by wxGlade 0.6.3 on Mon Aug 17 02:16:43 2009
# To get wxPerl visit http://wxPerl.sourceforge.net/

use Wx 0.15 qw[:allclasses];
use strict;

package Padre__Wx__Dialog__FindInFiles2;

use Wx qw[:everything];
use base qw(Wx::Dialog);
use strict;

sub new {
	my( $self, $parent, $id, $title, $pos, $size, $style, $name ) = @_;
	$parent = undef              unless defined $parent;
	$id     = -1                 unless defined $id;
	$title  = ""                 unless defined $title;
	$pos    = wxDefaultPosition  unless defined $pos;
	$size   = wxDefaultSize      unless defined $size;
	$name   = ""                 unless defined $name;

# begin wxGlade: Padre__Wx__Dialog__FindInFiles2::new

	$style = wxDEFAULT_DIALOG_STYLE|wxRESIZE_BORDER|wxTHICK_FRAME|wxFULL_REPAINT_ON_RESIZE|wxCLIP_CHILDREN 
		unless defined $style;

	$self = $self->SUPER::new( $parent, $id, $title, $pos, $size, $style, $name );
	$self->{find_combo} = Wx::ComboBox->new($self, -1, "", wxDefaultPosition, wxDefaultSize, [], wxCB_DROPDOWN);
	$self->{find_button} = Wx::Button->new($self, wxID_FIND, "");
	$self->{directory_label} = Wx::StaticText->new($self, -1, "Directory:", wxDefaultPosition, wxDefaultSize, );
	$self->{type_combo} = Wx::ComboBox->new($self, -1, "", wxDefaultPosition, wxDefaultSize, [], wxCB_DROPDOWN);
	$self->{browse_button} = Wx::Button->new($self, -1, "Browse");
	$self->{type_label} = Wx::StaticText->new($self, -1, "File Type:", wxDefaultPosition, wxDefaultSize, );
	$self->{directory_combo} = Wx::ComboBox->new($self, -1, "", wxDefaultPosition, wxDefaultSize, [], wxCB_DROPDOWN);
	$self->{cancel_button} = Wx::Button->new($self, wxID_CANCEL, "");
	$self->{static_line_1} = Wx::StaticLine->new($self, -1, wxDefaultPosition, wxDefaultSize, );
	$self->{radio_btn_1} = Wx::RadioButton->new($self, -1, "Substring", wxDefaultPosition, wxDefaultSize, wxRB_GROUP);
	$self->{radio_btn_2} = Wx::RadioButton->new($self, -1, "Whole Word", wxDefaultPosition, wxDefaultSize, );
	$self->{radio_btn_3} = Wx::RadioButton->new($self, -1, "Regular Expression", wxDefaultPosition, wxDefaultSize, );
	$self->{checkbox_1} = Wx::CheckBox->new($self, -1, "Case Sensitive", wxDefaultPosition, wxDefaultSize, );
	$self->{checkbox_2} = Wx::CheckBox->new($self, -1, "Include Subfolders", wxDefaultPosition, wxDefaultSize, );
	$self->{checkbox_3} = Wx::CheckBox->new($self, -1, "Include Hidden", wxDefaultPosition, wxDefaultSize, );
	$self->{checkbox_4} = Wx::CheckBox->new($self, -1, "Include Ignored", wxDefaultPosition, wxDefaultSize, );

	$self->__set_properties();
	$self->__do_layout();

# end wxGlade
	return $self;

}


sub __set_properties {
	my $self = shift;

# begin wxGlade: Padre__Wx__Dialog__FindInFiles2::__set_properties

	$self->SetTitle("Find in Files");
	$self->{find_combo}->SetSelection(-1);
	$self->{find_button}->SetDefault();
	$self->{type_combo}->SetSelection(-1);
	$self->{directory_combo}->SetSelection(-1);
	$self->{checkbox_2}->SetValue(1);

# end wxGlade
}

sub __do_layout {
	my $self = shift;

# begin wxGlade: Padre__Wx__Dialog__FindInFiles2::__do_layout

	$self->{vsizer} = Wx::BoxSizer->new(wxVERTICAL);
	$self->{sizer_1} = Wx::BoxSizer->new(wxHORIZONTAL);
	$self->{sizer_4} = Wx::BoxSizer->new(wxVERTICAL);
	$self->{sizer_3} = Wx::BoxSizer->new(wxVERTICAL);
	$self->{sizer_2} = Wx::BoxSizer->new(wxVERTICAL);
	$self->{grid_top} = Wx::FlexGridSizer->new(3, 3, 5, 5);
	my $find_label = Wx::StaticText->new($self, -1, "Search Term:", wxDefaultPosition, wxDefaultSize, );
	$self->{grid_top}->Add($find_label, 0, wxLEFT|wxTOP|wxALIGN_CENTER_VERTICAL, 5);
	$self->{grid_top}->Add($self->{find_combo}, 0, wxTOP|wxEXPAND|wxALIGN_CENTER_VERTICAL, 5);
	$self->{grid_top}->Add($self->{find_button}, 0, wxRIGHT|wxTOP|wxALIGN_CENTER_VERTICAL, 5);
	$self->{grid_top}->Add($self->{directory_label}, 0, wxLEFT|wxALIGN_CENTER_VERTICAL, 5);
	$self->{grid_top}->Add($self->{type_combo}, 0, wxEXPAND|wxALIGN_CENTER_VERTICAL, 5);
	$self->{grid_top}->Add($self->{browse_button}, 0, wxRIGHT|wxALIGN_CENTER_VERTICAL, 5);
	$self->{grid_top}->Add($self->{type_label}, 0, wxLEFT|wxBOTTOM|wxALIGN_CENTER_VERTICAL, 5);
	$self->{grid_top}->Add($self->{directory_combo}, 0, wxBOTTOM|wxEXPAND|wxALIGN_CENTER_VERTICAL, 5);
	$self->{grid_top}->Add($self->{cancel_button}, 0, wxRIGHT|wxBOTTOM|wxALIGN_CENTER_VERTICAL, 5);
	$self->{grid_top}->AddGrowableRow(1);
	$self->{grid_top}->AddGrowableCol(1);
	$self->{vsizer}->Add($self->{grid_top}, 1, wxEXPAND, 5);
	$self->{vsizer}->Add($self->{static_line_1}, 0, wxEXPAND, 0);
	$self->{sizer_2}->Add($self->{radio_btn_1}, 0, wxLEFT|wxRIGHT|wxTOP, 5);
	$self->{sizer_2}->Add($self->{radio_btn_2}, 0, wxLEFT|wxRIGHT|wxTOP, 5);
	$self->{sizer_2}->Add($self->{radio_btn_3}, 0, wxALL, 5);
	$self->{sizer_1}->Add($self->{sizer_2}, 0, 0, 0);
	$self->{sizer_3}->Add($self->{checkbox_1}, 0, wxLEFT|wxRIGHT|wxTOP, 5);
	$self->{sizer_1}->Add($self->{sizer_3}, 0, 0, 0);
	$self->{sizer_4}->Add($self->{checkbox_2}, 0, wxLEFT|wxRIGHT|wxTOP, 5);
	$self->{sizer_4}->Add($self->{checkbox_3}, 0, wxLEFT|wxRIGHT|wxTOP, 5);
	$self->{sizer_4}->Add($self->{checkbox_4}, 0, wxALL, 5);
	$self->{sizer_1}->Add($self->{sizer_4}, 0, 0, 0);
	$self->{vsizer}->Add($self->{sizer_1}, 0, wxEXPAND, 0);
	$self->SetSizer($self->{vsizer});
	$self->{vsizer}->Fit($self);
	$self->Layout();
	$self->Centre();

# end wxGlade
}

# end of class Padre__Wx__Dialog__FindInFiles2

1;

package Padre__Glade;

use base qw(Wx::App);
use strict;

sub OnInit {
	my( $self ) = shift;

	Wx::InitAllImageHandlers();

	my $find_in_files = Padre__Wx__Dialog__FindInFiles2->new();

	$self->SetTopWindow($find_in_files);
	$find_in_files->Show(1);

	return 1;
}
# end of class Padre__Glade

package main;

unless(caller){
	my $app = Padre__Glade->new();
	$app->MainLoop();
}
