#!/usr/bin/perl -w -- 
# generated by wxGlade 0.6.3 on Tue Jul 28 01:13:20 2009
# To get wxPerl visit http://wxPerl.sourceforge.net/

use Wx 0.15 qw[:allclasses];
use strict;

package Padre__Wx__Dialog__FindInFiles2;

use Wx qw[:everything];
use base qw(Wx::Dialog);
use strict;

sub new {
	my( $self, $parent, $id, $title, $pos, $size, $style, $name ) = @_;
	$parent = undef              unless defined $parent;
	$id     = -1                 unless defined $id;
	$title  = ""                 unless defined $title;
	$pos    = wxDefaultPosition  unless defined $pos;
	$size   = wxDefaultSize      unless defined $size;
	$name   = ""                 unless defined $name;

# begin wxGlade: Padre__Wx__Dialog__FindInFiles2::new

	$style = wxCAPTION|wxRESIZE_BORDER|wxFULL_REPAINT_ON_RESIZE|wxCLIP_CHILDREN 
		unless defined $style;

	$self = $self->SUPER::new( $parent, $id, $title, $pos, $size, $style, $name );
	$self->{find_label} = Wx::StaticText->new($self, -1, "Search Term:", wxDefaultPosition, wxDefaultSize, );
	$self->{find_combo} = Wx::ComboBox->new($self, -1, "", wxDefaultPosition, wxDefaultSize, [], wxCB_DROPDOWN|wxCB_DROPDOWN);
	$self->{find_button} = Wx::Button->new($self, wxID_FIND, "");
	$self->{type_label} = Wx::StaticText->new($self, -1, "File Type:", wxDefaultPosition, wxDefaultSize, );
	$self->{type_combo} = Wx::ComboBox->new($self, -1, "", wxDefaultPosition, wxDefaultSize, [], wxCB_DROPDOWN);
	$self->{cancel_button} = Wx::Button->new($self, wxID_CANCEL, "");
	$self->{directory_label} = Wx::StaticText->new($self, -1, "Directory:", wxDefaultPosition, wxDefaultSize, );
	$self->{directory_combo} = Wx::ComboBox->new($self, -1, "", wxDefaultPosition, wxDefaultSize, [], wxCB_DROPDOWN);
	$self->{directory_button} = Wx::Button->new($self, -1, "Browse");

	$self->__set_properties();
	$self->__do_layout();

# end wxGlade
	return $self;

}


sub __set_properties {
	my $self = shift;

# begin wxGlade: Padre__Wx__Dialog__FindInFiles2::__set_properties

	$self->SetTitle("Find in Files");
	$self->{find_combo}->SetSelection(-1);
	$self->{find_button}->SetDefault();
	$self->{type_combo}->SetSelection(-1);
	$self->{directory_combo}->SetSelection(-1);

# end wxGlade
}

sub __do_layout {
	my $self = shift;

# begin wxGlade: Padre__Wx__Dialog__FindInFiles2::__do_layout

	$self->{sizer} = Wx::FlexGridSizer->new(3, 3, 5, 5);
	$self->{sizer}->Add($self->{find_label}, 0, wxLEFT|wxTOP|wxALIGN_CENTER_VERTICAL, 5);
	$self->{sizer}->Add($self->{find_combo}, 0, wxTOP|wxEXPAND|wxALIGN_CENTER_VERTICAL, 5);
	$self->{sizer}->Add($self->{find_button}, 0, wxRIGHT|wxTOP|wxALIGN_CENTER_VERTICAL, 5);
	$self->{sizer}->Add($self->{type_label}, 0, wxLEFT|wxALIGN_CENTER_VERTICAL, 5);
	$self->{sizer}->Add($self->{type_combo}, 0, wxBOTTOM|wxEXPAND|wxALIGN_CENTER_VERTICAL, 5);
	$self->{sizer}->Add($self->{cancel_button}, 0, wxRIGHT|wxALIGN_CENTER_VERTICAL, 5);
	$self->{sizer}->Add($self->{directory_label}, 0, wxLEFT|wxBOTTOM|wxALIGN_CENTER_VERTICAL, 5);
	$self->{sizer}->Add($self->{directory_combo}, 0, wxALL|wxEXPAND|wxALIGN_CENTER_VERTICAL, 0);
	$self->{sizer}->Add($self->{directory_button}, 0, wxRIGHT|wxBOTTOM|wxALIGN_CENTER_VERTICAL, 5);
	$self->SetSizer($self->{sizer});
	$self->{sizer}->Fit($self);
	$self->{sizer}->SetSizeHints($self);
	$self->{sizer}->AddGrowableCol(1);
	$self->Layout();
	$self->Centre();

# end wxGlade
}

# end of class Padre__Wx__Dialog__FindInFiles2

1;

package Padre__Glade;

use base qw(Wx::App);
use strict;

sub OnInit {
	my( $self ) = shift;

	Wx::InitAllImageHandlers();

	my $find_in_files = Padre__Wx__Dialog__FindInFiles2->new();

	$self->SetTopWindow($find_in_files);
	$find_in_files->Show(1);

	return 1;
}
# end of class Padre__Glade

package main;

unless(caller){
	my $app = Padre__Glade->new();
	$app->MainLoop();
}
