---
name: PPIx-EditorTools
version: 0.03
author:
  - |-
    Steffen Mueller C<smueller@cpan.org>.
    Repackaged by Mark Grimes C<mgrimes@cpan.org>.
abstract: Utility methods and base class for manipulating Perl via PPI
license: perl
resources:
  license: http://dev.perl.org/licenses/
requires:
  Class::XSAccessor: 0
  PPI: 0
  perl: 5.010
build_requires:
  Test::Differences: 0
provides:
  PPIx::EditorTools:
    file: lib/PPIx/EditorTools.pm
    version: 0.03
  PPIx::EditorTools::FindUnmatchedBrace:
    file: lib/PPIx/EditorTools/FindUnmatchedBrace.pm
    version: 0.02
  PPIx::EditorTools::FindVariableDeclaration:
    file: lib/PPIx/EditorTools/FindVariableDeclaration.pm
    version: 0.02
  PPIx::EditorTools::IntroduceTemporaryVariable:
    file: lib/PPIx/EditorTools/IntroduceTemporaryVariable.pm
    version: 0.02
  PPIx::EditorTools::RenamePackage:
    file: lib/PPIx/EditorTools/RenamePackage.pm
    version: 0.02
  PPIx::EditorTools::RenamePackageFromPath:
    file: lib/PPIx/EditorTools/RenamePackageFromPath.pm
    version: 0.02
  PPIx::EditorTools::RenameVariable:
    file: lib/PPIx/EditorTools/RenameVariable.pm
    version: 0.02
generated_by: Module::Build version 0.32
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.2.html
  version: 1.2
