package Padre::Plugin::Fix::FBP::Preview;

## no critic

# This module was generated by Padre::Plugin::FormBuilder::Perl.
# To change this module edit the original .fbp file and regenerate.
# DO NOT MODIFY THIS FILE BY HAND!

use 5.008005;
use utf8;
use strict;
use warnings;
use Padre::Wx ();
use Padre::Wx::Role::Main ();
use Padre::Wx::Editor ();

our $VERSION = '0.01';
our @ISA     = qw{
	Padre::Wx::Role::Main
	Wx::Dialog
};

sub new {
	my $class  = shift;
	my $parent = shift;

	my $self = $class->SUPER::new(
		$parent,
		-1,
		Wx::gettext("Preview"),
		Wx::DefaultPosition,
		[ 538, 399 ],
		Wx::DEFAULT_DIALOG_STYLE,
	);

	my $tree_label = Wx::StaticText->new(
		$self,
		-1,
		Wx::gettext("List of Changes:"),
	);
	$tree_label->SetFont(
		Wx::Font->new( Wx::NORMAL_FONT->GetPointSize, 70, 90, 92, 0, "" )
	);

	$self->{tree} = Wx::TreeCtrl->new(
		$self,
		-1,
		Wx::DefaultPosition,
		Wx::DefaultSize,
		Wx::TR_DEFAULT_STYLE,
	);

	Wx::Event::EVT_TREE_SEL_CHANGED(
		$self,
		$self->{tree},
		sub {
			shift->on_tree_selection_changed(@_);
		},
	);

	my $preview_label = Wx::StaticText->new(
		$self,
		-1,
		Wx::gettext("Preview"),
	);
	$preview_label->SetFont(
		Wx::Font->new( Wx::NORMAL_FONT->GetPointSize, 70, 90, 92, 0, "" )
	);

	$self->{preview} = Padre::Wx::Editor->new(
		$self,
		-1,
	);

	$self->{static_line} = Wx::StaticLine->new(
		$self,
		-1,
		Wx::DefaultPosition,
		Wx::DefaultSize,
		Wx::LI_HORIZONTAL,
	);

	$self->{ok_button} = Wx::Button->new(
		$self,
		Wx::ID_OK,
		Wx::gettext("&OK"),
		Wx::DefaultPosition,
		Wx::DefaultSize,
	);

	$self->{cancel_button} = Wx::Button->new(
		$self,
		Wx::ID_CANCEL,
		Wx::gettext("&Cancel"),
		Wx::DefaultPosition,
		Wx::DefaultSize,
	);

	my $button_sizer = Wx::BoxSizer->new(Wx::HORIZONTAL);
	$button_sizer->Add( 0, 0, 1, Wx::EXPAND, 5 );
	$button_sizer->Add( $self->{ok_button}, 0, Wx::ALL, 5 );
	$button_sizer->Add( $self->{cancel_button}, 0, Wx::ALL, 5 );

	my $sizer = Wx::BoxSizer->new(Wx::VERTICAL);
	$sizer->Add( $tree_label, 0, Wx::EXPAND | Wx::LEFT | Wx::RIGHT | Wx::TOP, 5 );
	$sizer->Add( $self->{tree}, 1, Wx::ALL | Wx::EXPAND, 5 );
	$sizer->Add( $preview_label, 0, Wx::ALL, 5 );
	$sizer->Add( $self->{preview}, 1, Wx::ALL | Wx::EXPAND, 5 );
	$sizer->Add( $self->{static_line}, 0, Wx::EXPAND | Wx::ALL, 5 );
	$sizer->Add( $button_sizer, 0, Wx::EXPAND, 5 );

	$self->SetSizer($sizer);
	$self->Layout;

	return $self;
}

sub on_tree_selection_changed {
	$_[0]->main->error('Handler method on_tree_selection_changed for event tree.OnTreeSelChanged not implemented');
}

1;

# Copyright 2008-2012 The Padre development team as listed in Padre.pm.
# LICENSE
# This program is free software; you can redistribute it and/or
# modify it under the same terms as Perl 5 itself.

